### ISSUE TITLE
Update codelyzer support for Angular v13

### ISSUE THREAD

**Issue by langthiennhai** [mgechev/codelyzer#1019]
OS: Window 10
Angular 13
Node 14.15.0

**Peer dep missing:**
npm ERR! peer dep missing: @angular/core@>=2.3.1 <13.0.0 || ^12.0.0-next || ^12.1.0-next || ^12.2.0-next, required by codelyzer@6.0.2

**Comment by renemadsen** [comment]
Any update on this @mgechev ?

**Comment by afnecors** [comment]
> We’re deprecating the use of TSLint and Codelyzer in version 11.

[https://blog.angular.io/version-11-of-angular-now-available-74721b7952f7](https://blog.angular.io/version-11-of-angular-now-available-74721b7952f7)

**Comment by mgechev** [comment]
For v11+ I recommend you moving to ESLint.
