### ISSUE TITLE
component-selector-prefix should match first word of selector instead of prefix

### ISSUE THREAD

**Issue by chrisse27** [mgechev/codelyzer#103]
If I have the component-selector-prefix rule configured such that the prefix is set to "app" then the rule still allows me to use "apps-my-component" as selector.

I think it would be better if the component-selector-prefix rule would match the first word of the selector against the configured prefix. The scanning algorithm to find the first word should depend on the configured value for the "component-selector-name" rule.

Alternatively, a new rule called component-selector-first-word rule should be introduced that implements the described behavior.

**Comment by mgechev** [comment]
Yes, we'll make a lot of improvements in near future (next release) here are some more details https://github.com/mgechev/codelyzer/issues/15.
