### ISSUE TITLE
Error on `@Pipe` decorator

### ISSUE THREAD

**Issue by aitboudad** [mgechev/codelyzer#111]
```ts
@Pipe
export class Foo implements PipeTransform {}
```

```
TypeError: Cannot read property 'text' of undefined
    at node_modules/codelyzer/pipeNamingRule.js:52:39
```

**Comment by preslavsh** [comment]
This error occurs from lack of metadata.

**Comment by mgechev** [comment]
I will take this issue, we had it some time in the past for components.

**Comment by mgechev** [comment]
@aitboudad in the next a couple of days the fix will be in master and after that we'll push it to npm.

**Comment by aitboudad** [comment]
awesome! thanks ;)
