### ISSUE TITLE
Support template directives

### ISSUE THREAD

**Issue by wesleycho** [mgechev/codelyzer#114]
I am using directives with selector of the form `template[myPrefixDirectiveName]` in my app, ala what [ng-bootstrap](https://ng-bootstrap.github.io/) does currently (see the documentation for the modal for example and the note on the `<template ngbModalContainer>` usage), and get warning messages like
```
The selector of the directive "Foo" should be used as attribute (https://goo.gl/QS8kEs)
The selector of the directive "Foo" should have prefix `my` (https://goo.gl/uacjKR)
```
This should be supported by Codelyzer IMO.

**Comment by mgechev** [comment]
We're working on improving the selector-related rules so "[prefixRest].bar" and "[prefixBar][foo]" will work.

The selector of the template directives doesn't have to include element so most likely even after the improvements your selector is going to fail for directive-selector-type.

**Comment by phil123456** [comment]
does not work for directives

**Comment by timvl** [comment]
@phil123456  this should work:

```javascript
@Directive({
  /* tslint:disable-next-line:directive-selector */
  selector: 'card-row'
})
```
