### ISSUE TITLE
no-access-missing-member rule not considering ES6 property getters

### ISSUE THREAD

**Issue by cyrilletuzi** [mgechev/codelyzer#118]
ES6 property getters are not considered by codelyzer, so the "no-access-missing-member" rule is raising an error in such cases :

```
@Component({
    template: `<div>{{text}}</div>`
})
export class MyComponent {

    public get text() {
        return 'something';
    }

}
```

**Comment by mgechev** [comment]
Good catch! I'll fix this during the weekend and push the update early next week.
