### ISSUE TITLE
no-access-missing-member rule not considering template references

### ISSUE THREAD

**Issue by cyrilletuzi** [mgechev/codelyzer#119]
Angular template references are not considered by codelyzer, so the "no-access-missing-member" rule is raising an error (on loginForm) in such cases :

```
@Component({
    template: `<form #loginForm="ngForm">
<button type="submit" [disabled]="!loginForm.valid">Se connecter</button>
</form>`
})
```

**Comment by mgechev** [comment]
This might get tricky. I'm not sure the template references are resolvable without collecting metadata/compilation of templates.

**Comment by cyrilletuzi** [comment]
Would like to help but not used to that kind of stuff. Can't we just regexp the template to find "#" ?

**Comment by abbazabacto** [comment]
not sure if this is the place, but automated generated references like `$event` aren't considered as well...

```
@Component({
    template: `<form #loginForm="ngForm" (submit)="submit($event)">...</form>`
})
```

**Comment by mgechev** [comment]
@abbazabacto this one will be fixed by [this PR](https://github.com/mgechev/codelyzer/pull/124/files). Here's [the test](https://github.com/mgechev/codelyzer/pull/124/files#diff-30955923cbafc5a4ecbec285d88d5a56R468).

**Comment by abbazabacto** [comment]
@mgechev sorry just realised the `$event` as an argument of function isn't checked in the current version at all...

The no-access-missing-member error regarding `$event` I got was when I used it in the template directly f.e.
```
@Component({
    template: `<input (keypress)="$event.stopPropagation()">`
})
```
For now bypassed it by passing it to a method handling the stopPropagation.

Your test succeeding might be because it just doesn't check the arguments...

**Comment by mgechev** [comment]
@abbazabacto should be fine [here](https://github.com/mgechev/codelyzer/pull/124/files#diff-968ef9a197df82277aff3a1da77e646cR126). I'm maintaining a symbol table currently containing only variable name.

**Comment by mgechev** [comment]
It was fixed in the previous release. Now the template references can also be configured in `.condelyzer.js` because the tool doesn't analyze the entire component tree.
