### ISSUE TITLE
Do not recompute Angular component metadata

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#125]
At this point we recompute the metadata for components in different linting rules and the logic for gathering this metadata is with **coincidental cohesion** spread inside the `utils` directory which sucks.

Define a class `Metadata` which contains the metadata for Angular components/directives (such as template, styles, view encapsulation, is a template/style external, etc.). Define a class `ShallowMetadataCollector` which collects this data and use it inside `Ng2Walker` in order to populates an instance of the `Metadata` class. Provide this metadata as context for all the template/style/expression visitors.

Note: There's a metadata collector which is already available and feature rich, part of the AoT compiler. For linting we need only a light version of it so we can build a custom one.

**Comment by ghsyeung** [comment]
Is "recompute" referring to parsing template AST multiple times for each lint rule?

And the reference to metadata collector in AoT, are you referring to this?
https://github.com/angular/angular/blob/76dd026447011823770e23fb5c4168c7d96a494b/modules/%40angular/compiler/src/metadata_resolver.ts#L119

**Comment by mgechev** [comment]
Here is [the collector](https://github.com/angular/angular/blob/14ee75924b6ae770115f7f260d720efa8bfb576a/tools/%40angular/tsc-wrapped/src/collector.ts). Not parsing the template/styles for each rule is the next step. First, when we find an Angular component/directive we need to extract the data from it's class decorator and store it into an object. For instance:

```ts
@Component({
  moduleId: module.id,
  templateUrl: 'foo.html',
  encapsulation: core.ViewEncapsulation.None,
  styles: [`.foo { color: red }`]
})
...
```

Should become:

```ts
{
   templateUrl: "ROOT/foo.html",
   styles: ['.foo { color: red }'],
  encapsulation: 0,
}
```

It is mostly related to normalizing/extracting the property values. For instance, the template can be defined with:

```
template: '\nfoobar'
```

or

```
template: '\n' +
  'foobar'
```

or

```
template: `
  foobar`
```

Using the produced by TypeScript AST we can resolve the template value differently. The idea is to keep the logic for normalizing/extracting properties in a single class and reuse the resulted values.

PS: We won't support:

```ts
const template = 'foobar';
@Component({
  template
})
```

...at first.

**Comment by ghsyeung** [comment]
Spend a bit of time researching the code. I'll restate the problem here to make sure I have the correct understanding.

So basically in `Ng2Walker.visitClassDecorator`, `ShallowMetadataCollector` would extract and normalize the `ts.ObjectLiteralExpression` into something like `type Metadata = ComponentMetadata | DirectiveMetadata`. 

Then, utils like `getDecoratorPropertyInitializer` would group under `ShallowMetadataCollector`.

One question about the using of  `Metadata`. You mention that it would get passed into the template/style/expression visitors. Do you mean it would be passed as the 2nd argument to `BasicTemplateAstVisitor.visit` (and other visitor base classes)? Can you give me a use case when the `Metadata` would be useful inside these visitors?

**Comment by mgechev** [comment]
Yes, correct. I am also thinking of including one more field in the `Metadata` class which references to the class's AST (i.e. `ClassDeclaration`). This way it'll be easier to extract other data which doesn't exist in `Metadata`.

> One question about the using of Metadata. You mention that it would get passed into the template/style/expression visitors. Do you mean it would be passed as the 2nd argument to BasicTemplateAstVisitor.visit (and other visitor base classes)? Can you give me a use case when the Metadata would be useful inside these visitors?

Not sure how to approach here. Maybe it'll be better to keep the metadata as property inside these visitors. For instance now some of them have `this.context` which points to the component's class (or controller, depending on the context).

**Comment by ghsyeung** [comment]
How about start with `ShallowMetadataCollector` first? I think passing as `this.context` would be a good first step. Once that is cleaned up, it'll be easier to see how some of the rules can be refactored.

One thing I notice is `Ng2Walker` may be exposing too much API. For example, `SelectorNameValidatorWalker` overrides `visitClassDeclaration` which in the ideal scenario, if there's `ComponentMetadata`, then there can be a `ComponentWalker` that doesn't expose `visitClassDeclaration`.

**Comment by mgechev** [comment]
You can take a look at the styles branch for the latest version of what we have.

I thought about having a separate visitor for Angular and probably it will be cleaner, following the interface segregation principle stricter. What bothers me with this approach is that we will have 5 visitors - 4 ng specific (template, styles, expressions, the directive/component classes) and the previous one, otherwise we have only 4.

On the other hand, both options seems similar in sense of how easy it will be to migrate to another linting platform (we use tslint now but why not to be compatible with eslint or something custom).

In addition to the Metadata class, probably it should also include fields for the components inputs, outputs, host listeners, etc. For some rules this data wont applicable, because we validate the used syntax now the values themselves but in general it should be helpful.
