### ISSUE TITLE
feature: if class uses lifecycle hooks it must had proper name decorator

### ISSUE THREAD

**Issue by ValeryVS** [mgechev/codelyzer#126]
For example, `ngOnInit` or `ngOnDestroy` can be used on service, but it is component/directive hooks.

``` typescript
import {
    Injectable,
    OnInit,
    OnDestroy,
} from '@angular/core';

@Injectable()
export class MyService implements OnInit, OnDestroy {
    ngOnInit() {
    }

    ngOnDestroy() {
    }
}
```

Lifecycle sequence
https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html
Some are "component-only", some - "directive/component".

Variant 1
- show error when class have not `@Component` or `@Directive` decorator

Variant 2
- show error when class have `@Injectable` decorator, because it is not work on services

**Comment by mgechev** [comment]
@ValeryVS at the moment I'm working on other parts of codelyzer. Would appreciate a PR!

**Comment by mgechev** [comment]
This can get tricky with inheritance. It also doesn't fit very well with the shallow code analysis we provide which aims enforcement of common style, rather than caching logical errors.
