### ISSUE TITLE
Feature request: Enforce value of @Component.changeDetection

### ISSUE THREAD

**Issue by philipbulley** [mgechev/codelyzer#135]
In the project I'm currently working on, it'd be useful to ensure that all components are set to use `changeDetection: ChangeDetectionStrategy.OnPush`.

**Comment by mgechev** [comment]
Sounds good, I'm only afraid it could be misleading for components which produce/rely on side-effects.

I'm not sure there's a good way to predict if a component is suitable for `OnPush` `ChangeDetectionStrategy`. Do you have any ideas?

**Comment by mgechev** [comment]
Let's close it since it's very hard to guess if a component produces a side-effect &/|| depends on global state or not.

**Comment by guojenman** [comment]
@mgechev How about enforcing the existence of changeDetection? At least this way, it's a conscious decision by the developer to say whether it is or not. This would prevent accidental default change detection by an accidental omission.

**Comment by jobvanstiphout** [comment]
@mgechev A rule for this is landing soon in material2, would be nice to include this rule in codelyzer. It uses a whitelist to disable it for certain components.

**Comment by mgechev** [comment]
Okay, lets reopen the issue.

**Comment by jobvanstiphout** [comment]
An even more beautiful rule has landed in material2, to lint any properties of any decorator:
https://github.com/angular/material2/blob/master/tools/tslint-rules/validateDecoratorsRule.ts

**Comment by dominique-mueller** [comment]
In our case, we're developing an Angular component library in which every component *must* have set the change detection strategy to `OnPush`. We also try to build our applications using `OnPush` everywhere.

Thus, it would be awesome to have linting rule for that!

**Comment by mgechev** [comment]
Okay, lets do that. Maybe as argument of the rule we can provide a regex for matching the components which should have `OnPush`. By default it can be `.*`.

**Comment by amcdnl** [comment]
Whats the status on this? Would love to incorporate this.

**Comment by wKoza** [comment]
I think that you can do it. If we want bypass this rule, we can also simply mark our component with `tslint:disable:onPushStrategy`(with a comment)

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by buu700** [comment]
>I'm not sure there's a good way to predict if a component is suitable for `OnPush` `ChangeDetectionStrategy`. Do you have any ideas?

What about validating that every variable referenced in the template is either `@Input()` or `readonly` (with the latter intended to cover static values and observables)? (There's also the issue of getters — that feels hairier to properly address, but maybe just validate that they don't blatantly reference non-read-only class members?)

There would probably be some exceptions where users need to disable the rule for certain components, like when relying on manual change detection initiation, but unless I'm forgetting something I think just about any ideal/idiomatic `OnPush`-compatible code would comply with the above.

**Comment by mrmeku** [comment]
+1 vote. If and when you decide to go ahead with this @mgechev I'd be willing to try and implement it. I think detecting whether something should be OnPush is nearly impossible as you've said, but requiring that you add your component to a whitelist of things that are exempt is super easy. That's what I'm voting for

**Comment by dominique-mueller** [comment]
Assuming there is no relevant difference between defining a whitelist array in the tslint file vs. using tslint:disable comments, I would certainly prefer the comment-based solution.

In my opinion, tslint:disable comments are much easier to maintain because the linting exception is closer to the actual source code it affects.

**Comment by mrmeku** [comment]
I would too. I used the term white list intentionally ambiguous just in
case other people felt differently.

**Comment by mgechev** [comment]
@dominique-mueller I agree with you. @mrmeku feel free to take this! If you do, just let me know so I can assign you to the issue.

**Comment by mrmeku** [comment]
I'll take it! Assign it to me :D

**Comment by mgechev** [comment]
@mrmeku I'll assign it to myself so that nobody takes it. GitHub does not allow me to attach the issue to you.

**Comment by ajantsch** [comment]
We're working on optimizing on of our apps right now, and one of the measures we take is to make all the components to use `ChangeDetectionStrategy.onPush`, while during the transition period we would also like to whitelist some components that haven't been updated yet. So this feature would be very beneficial for us 👍

**Comment by lazarljubenovic** [comment]
Why don't you just the use the comments to disable linting? Whitelisting in a separate file is cumbersome, you have info about the class scattered around.

```ts
// why like this?
whitelist: ["FooCmp"]

class FooCmp {}
```

```ts
// when you can do this!
// whitelist
class FooCmp {}
```

The exact same rationale is in Angular's own styleguide for using `inputs: []` vs `@Input`.

```ts
// why like this?
inputs: ['foo']

public foo: string
```

```ts
// when you can do this!
@Input()
public foo: string
```

---

Imagine if tslint config had a whitelist for lines you want to disable it in:

```ts
// why like this?
"max-line-length": [true, 140, {"whitelist": ["path/to/file#L20", "path/to/other/file#L30"]}]

// path/to/file
20 | (super long line)

// path/to/other/file
30 | (super long line)
```

```ts
// when you can do this!
// path/to/file
19 | // tslint:disable-next-line:max-line-length
20 | (super long line)

// path/to/other/file
29 | // tslint:disable-next-line:max-line-length
30 | (super long line)
```

It's always better to define things about X near X instead of a config file which references X.

**Comment by mgechev** [comment]
Anyone wants to take this issue? I'll be happy to assist if needed.

**Comment by snowinmars** [comment]
num13ru/eslint-plugin-change-detection-strategy#1
