### ISSUE TITLE
directive-selector-prefix rule clashes (sort of) with no-input-rename

### ISSUE THREAD

**Issue by karptonite** [mgechev/codelyzer#138]
A common use case for an attribute directive is some sort of decoration, passing an input.

For example, you might have a selector, `[prefixHighlightColor]`, and want to pass it as an input without the prefix, `@Input('prefixHighlightColor') highlightColor: string;`.

It seems that removing the prefix should not count as "renaming" for the no-input-rename rule. That rule seems sensible rule in any other case I can think of, so it would be a shame not to use it.

**Comment by mgechev** [comment]
@karptonite the issue makes sense. Probably we should move the discussion at https://github.com/angular/angular.io/issues. Please mention me in the issue if you open one there.

**Comment by mgechev** [comment]
Just for completeness: the rules can be disabled by setting:

```js
"no-input-rename": false,
"no-output-rename": false
```

in your tslint.json file.
