### ISSUE TITLE
selectors with classes

### ISSUE THREAD

**Issue by elijahiuu** [mgechev/codelyzer#14]
This selector is not passing the checker:

```ts
@Component({
  selector: 'abc.xyz'
})
class Foo {...}
```

it supposed to target `<abc class="xyz"></abc>`.

**Comment by preslavsh** [comment]
What is your typescript version?

**Comment by mgechev** [comment]
The selector `abc.xyz` is not kebab-case so this is the expected behavior.

You can disable the rule by:

```
 "component-selector-name": false
```

**Comment by mgechev** [comment]
@elijahiuu although I think in this case we need to rise a warning, there's still issue in our selector validators that is [addressed here](https://github.com/mgechev/codelyzer/issues/15).
