### ISSUE TITLE
Warn if @Injectable() not included on exported class with no other Decorators  

### ISSUE THREAD

**Issue by MarkPieszak** [mgechev/codelyzer#140]
Issue described here: https://github.com/angular/angular/issues/12745

It'd be great to provide some type of warning message when there's

            // <-- Warning: Are you forgetting Injectable() ? 
    export class SomeService { }

Maybe some better phrasing :)

**Comment by mgechev** [comment]
We can take this even further and warn only when:

- The class is exported.
- The class has non-primitive arguments of it's constructor.

**Comment by UnwrittenFun** [comment]
Perhaps an option to only warn if the class name ends in Service, not all exported classes we use are services.

**Comment by mgechev** [comment]
Lets close this issue for now. It'll be great if anyone is willing to open a PR!
