### ISSUE TITLE
[Proposal] Visual Studio IDE integration

### ISSUE THREAD

**Issue by MarkPieszak** [mgechev/codelyzer#141]
I'm not sure if it's a limitation of VStudio or not, and I can most definitely help look into this if pointed in the right direction @mgechev!

It'd be great to have similar real-time analyzing that's in Atom or VSCode.

Just creating an issue so it's on the radar.

Codelyzer 💯

**Comment by fabianluque** [comment]
Count me in here if you need any help. I'd love to have this in VS.

**Comment by mgechev** [comment]
Should be possible through [Web Analyzer](https://visualstudiogallery.msdn.microsoft.com/6edc26d4-47d8-4987-82ee-7c820d79be1d).

**Comment by MarkPieszak** [comment]
Web Analyzer doesn't work with 2015, but great news! @fabianluque 
The very latest "preview" of .NET Core **1.1.0** automatically has TSLint etc in it, so it works!

![image](https://cloud.githubusercontent.com/assets/2574412/20151746/4f9925d4-a689-11e6-9187-03ba7e53d28f.png)

Added PR #143 to note it in the readme for codelyzer @mgechev

**Comment by fabianluque** [comment]
Yes, I knew about the extension but it's not the same thing:

- It does not support custom rules like codelyzer
- It displays the errors in the error list pane instead of inside the editor

In that particular screenshot you've shared, it's actually TS compiler that's warning you, not TSLint.

**Comment by MarkPieszak** [comment]
Oh shoot, let me test. Have you tried the 1.1.0-preview and had no luck?

**Comment by MarkPieszak** [comment]
You're right for example:

    "component-selector-prefix": [ true, "app" ],

Doesn't get triggered if I remove the prefix `app-` from a Component's selector.
Hmm what is missing here...

**Comment by fabianluque** [comment]
Like I said above, it's not supported. The extension was the former WebAnalyzer and now they are bundling it with ASP.NET Core Tooling extension.

It also does not support using a different TSLint version, so for example if you switch to TS 2.0, you get a lot of wrong warnings.

See here: https://github.com/aspnet/Tooling/issues?utf8=%E2%9C%93&q=is%3Aissue%20tslint%20

**Comment by michaeljota** [comment]
I think this should be more like creating a proper TSLint extension for VS IDE, instead of creating a Codelyzer extension.

**Comment by MarkPieszak** [comment]
@michaeljota Yeah I think that's what we've realized, it's the lack of a good TSLinter in VStudio that's the problem :/

**Comment by mgechev** [comment]
I'll close the issue for now since it's related to tslint integration in the IDE, doesn't seem codelyzer specific.
