### ISSUE TITLE
this codelyzer check seems broken for pipes

### ISSUE THREAD

**Issue by xtianus79** [mgechev/codelyzer#145]
when using this command

"use-pipe-transform-interface": false, // what is this -- seems to be broken

it always fails and the code seems correct

````Here is the code
@Pipe({name: 'orderByActive'})
export class OrderByActivePipe implements PipeTransform {
````

**Comment by mgechev** [comment]
I have the following code:

```ts
import { Component, PipeTransform, Pipe } from '@angular/core';
import { Config } from './shared/index';
import './operators';

@Pipe({name: 'orderByActive'})
export class OrderByActivePipe implements PipeTransform {
  transform() {
    return true;
  }
}
```

It works fine for me. Can you reproduce the issue on http://codelyzer.com?

**Comment by xtianus79** [comment]
@mgechev i put it in codelyzer and it says no issue... 

however the same error is occuring.... 

src/app/components/admin/person/order-by-active.pipe.ts[4, 1]: The OrderByActivePipe class has the Pipe decorator, so it should implement the PipeTransform interface

**Comment by antonybudianto** [comment]
looks like #142

**Comment by khodev** [comment]
npm will install typescript 2.1.x

codelyzer/src/util/syntaxKind.ts > SyntaxKind.current().ImplementsKeyword returns 106 where it should be 107 starting from TypeScript version 2.1.0

The breaking change is here:

https://github.com/Microsoft/TypeScript/commit/6814c1d883791a1ad976f3146315de30e00dc0b9#diff-9a9b25e2950a3c3c611c9e2e095e2e41

before: ImplementsKeyword = 106
after: ImplementsKeyword = 107

**Comment by mgechev** [comment]
@khodev, thanks for pointing this out! Here's the fix https://github.com/mgechev/codelyzer/commit/d49cc26bb7d554da55ae71cda8a9fba0ff522d10.

**Comment by xtianus79** [comment]
@mgechev just to ask what is the latest version?  I don't see releases...

**Comment by mgechev** [comment]
The latest version is `beta.4`:

```
npm i codelyzer@1.0.0-beta.4
```
