### ISSUE TITLE
directive-selector-name can't handle multiple selectors

### ISSUE THREAD

**Issue by jstuparitz** [mgechev/codelyzer#146]
I have a custom Angular 2 directive with a selector like:

selector: '[equalValidator][formControlName],[equalValidator][formControl],[equalValidator][ngModel]'

This doesn't pass tslint, but this does

selector: '[equalValidator][formControlName]'

Also, the disable comment doesn't work.  Though it might be how I'm using it

  // tslint:disable-line:directive-selector-name
  selector: '[equalValidator][formControlName],[equalValidator][formControl],[equalValidator][ngModel]'

**Comment by mgechev** [comment]
Thanks for reporting this! It is a known issue aimed to be resolved by an open PR.
