### ISSUE TITLE
Develop selector validators compatible with spec

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#15]
Currently the selectors' validators are not compatible with [spec](https://www.w3.org/TR/css3-selectors/).

**Comment by mgechev** [comment]
During the last meeting, we decided to use the `CssSelector` and it's `parse` method from `@angular/compiler`. This way we'll be able to have semantical check based on the selector type.

For instance, for `@Component`s the check should look like:

```ts
const selector = CssSelector.parse(component.selector);
if (selector.element !== null) {
  // validate if it is a valid kebab-case elector, if not, throw a warning
} else {
  // throw a warning that the component doesn’t use element selector
}
```

**Comment by preslavsh** [comment]
#137  Needs reviewing

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/codelyzer/commit/3373dffe7962f5e919161d60bc152f0d82dcb5d2.
