### ISSUE TITLE
Can't resolve template variables

### ISSUE THREAD

**Issue by michaeljota** [mgechev/codelyzer#151]
I try to search for this, but I did not find anything, so sorry if this is duplicated. When using template variables, inside the template they are not recognized and throws cause they don't exist in the class component. 

```html
<form
    (ngSubmit)="addTodo(todoForm)"
    autocomplete="off"
    #todoForm="ngForm"
  >

    <input
      type="text"
      name="todo-text"
      placeholder="insert todo"
      [(ngModel)]="todoModel.text"
      required
      autofocus
    />
    <button type="submit" [disabled]="!todoForm.form.valid">Add Todo</button>
  </form>
```

throws: `The property "todoForm" that you're trying to access does not exist in the class declaration.`

Edit: It is related to #123

**Comment by michaeljota** [comment]
Thanks!

**Comment by mgechev** [comment]
Thanks for pointing this out!
