### ISSUE TITLE
Upgrade to tslint 4

### ISSUE THREAD

**Issue by rolandjitsu** [mgechev/codelyzer#157]
It would be nice to upgrade the tslint version to v4.

**Comment by mgechev** [comment]
Thanks for the suggestion! The migration is completed here https://github.com/mgechev/codelyzer/pull/158.

**Comment by paralin** [comment]
Can you roll a release with this?

**Comment by mgechev** [comment]
Yes, in a few days. It will be part of a big release which introduces support for external templates.

**Comment by mgechev** [comment]
You can now use `2.0.0-beta.1` which works with tslint 4.

**Comment by paralin** [comment]
Thanks :)
