### ISSUE TITLE
Emacs integration

### ISSUE THREAD

**Issue by altschuler** [mgechev/codelyzer#160]
Are there any plan for integration with Emacs? If not, are there any pointers for how to integrate in new editors?

**Comment by mgechev** [comment]
We reuse the error reporting mechanism of tslint. If there's a tslint plugin for emacs, or anything like syntastic/neomake, you should be able to integrate it in your editor.

**Comment by altschuler** [comment]
Roger, got it working. For reference, make sure that `tslint` is globally installed, then it should work out of the box with flycheck. Thanks!
