### ISSUE TITLE
Widget Proposal

### ISSUE THREAD

**Issue by michaeljota** [mgechev/codelyzer#167]
I like this tool, cause it enforce consistency through the code, like all linters I guess. In my projects I use the concept of `widget`, witch are 'dummy components'. I would like to be able to set a rule, that allows the name of `widget`, and ensure, or try hard to, the component only have inputs and outputs properties.

## Motivation
React community have develop their own 'dummy components', and 'smart components'. The dummy are those that does not interact with the state of the application, but their state it's giving from a higher component. The smart are those that dispatch events to the state, binds the events from the dummy with those dispatches, and sent the data that the dummy should display. 

In React, the dummy are called components, and the smart are called containers. However, Angular 2 conventions, every component can be smart, cause 2 way data binding and other feats that allows Angular application components to manage the state in a proper way. 

A widget however, it's used to name a piece of something that only display information, and I think that's really what the dummy components are about, show information and send events to be handle by the component.

Currently, all the components are called the same, but I would like to suggest this name style for the dummy components.

**Comment by mgechev** [comment]
Hey @michaeljota as part of the next release we'll introduce an option to set a custom suffix for your components & directives which by default will be `Component` & `Directive`. This way you'll be able to easily introduce custom naming convention.

For further details take a look at this issue https://github.com/mgechev/codelyzer/issues/132.

**Comment by michaeljota** [comment]
@mgechev I see the new option. I would want to suggest to this option to accept an array of suffixes, cause in a project it may get sense to have more than one suffix.

**Comment by mgechev** [comment]
I'm not sure that this will be with alignment with the style guide. It suggest only a single suffix, also we did an exception for Ionic 2 where we allow `Page` suffix.
