### ISSUE TITLE
Cannot find module 'tslint/lib/lint'

### ISSUE THREAD

**Issue by piq9117** [mgechev/codelyzer#168]
When I dug into the node_modules/codelyzer/importDestructuringSpacingRule.js I see 
```
var Lint = require('tslint/lib/lint')
```
and the same thing in node_modules/codelyzer/importDestructuringSpacingRule.d.ts, its importing
```
import * as Lint from 'tslint/lib/lint'
```
and if I change the path to `tslint/lib/index` it totally  works. <br />
So, I forked the `codelyzer` project to see what's going on. I ran `build` and `prepare:package`, and it gives out the right path. It has 
```
import * as Lint from 'tslint'
```
 What is going on?

**Comment by mgechev** [comment]
Duplication of https://github.com/mgechev/codelyzer/issues/165. Downgrade to tslint 3.x.x until we release the next version.

**Comment by mgechev** [comment]
You can use `2.0.0-beta.1` which works with tslint 4.

**Comment by piq9117** [comment]
wow! a personal message from the main contributor. thanks @mgechev! Your project has been helping me tremendously!
