### ISSUE TITLE
TypeError: Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by crebuh** [mgechev/codelyzer#171]
Hi guys! First of all I like the idea of this project very much.

Unfortunatley I have problems running the linting tool on my project. I'm running the following versions:

    chuber@XIAOMI-MI:~$ tsc -v
    Version 2.2.0-dev.20161128
    chuber@XIAOMI-MI:~$ tslint -v
    4.0.2

But when I try to run the linter via the command line like:

     ./node_modules/.bin/tslint -c tslint.json src/app/app.ts

I'm justing getting the following error: 

      /home/chuber/Projects/app/node_modules/tslint/lib/tslint-cli.js:234
    throw error;
    ^

     TypeError: Cannot read property 'parse' of undefined
    at SelectorValidatorWalker.extractMainSelector (/home/chuber/Projects/app/node_modules/codelyzer/selectorNameBase.js:151:36)
    at /home/chuber/Projects/app/node_modules/codelyzer/selectorNameBase.js:122:39
    at Array.forEach (native)
    at SelectorValidatorWalker.validateSelector (/home/chuber/Projects/app/node_modules/codelyzer/selectorNameBase.js:121:18)
    at SelectorValidatorWalker.validateDecorator (/home/chuber/Projects/app/node_modules/codelyzer/selectorNameBase.js:113:18)
    at Array.forEach (native)
    at SelectorValidatorWalker.visitClassDeclaration (/home/chuber/Projects/app/node_modules/codelyzer/selectorNameBase.js:103:14)
    at SelectorValidatorWalker.SyntaxWalker.visitNode (/home/chuber/Projects/app/node_modules/tslint/lib/language/walker/syntaxWalker.js:298:22)
    at /home/chuber/Projects/app/node_modules/tslint/lib/language/walker/syntaxWalker.js:505:63
    at visitEachNode (/home/chuber/Projects/app/node_modules/typescript/lib/typescript.js:8247:30)

I also added the configuration for Visual Studio Code, but I also dont get any feedback from the editor. I guess I'm using the wrong versions?

**Comment by mgechev** [comment]
At the moment codelyzer [doesn't support TypeScript 2.2.x](https://github.com/mgechev/codelyzer/blob/master/src/util/syntaxKind.ts#L2442-L2463), although I'm not sure the local version of tslint you're running uses your global `tsc`. Would you give me the output of:

```
./node_modules/.bin/tsc -v
./node_modules/.bin/tslint -v
```

It will be also great if you can share the content of `src/app/app.ts` so I can fix the issue and introduce a test case.

Most likely the tslint plugin for VSCode crashes silently that's why you're not getting any errors.

**Comment by crebuh** [comment]
@mgechev 

thx for the quick response here is the output within the project folder:

    chuber@XIAOMI-MI:~/app$ ./node_modules/.bin/tsc -v
    Version 2.0.2
    chuber@XIAOMI-MI:~/app$ ./node_modules/.bin/tslint -v
    4.0.2

the project is still using typescript 2.0.2. here is a copy of my app.ts http://pastebin.com/mk0GK0hN

I am not sure maybe the project it self is causing problems? Currently I am working on an angular universal (https://github.com/angular/universal) project.

**Comment by mgechev** [comment]
Great! Thanks for the information; I will see if I can publish a fix as part of the next release.

Until then you can disable tslint or just a subset of rules for the files where codelyzer fails.

**Comment by mgechev** [comment]
@crebuh what version of Angular are you using? Did you get any peerDependencies errors? This doesn't seem like an issue in codelyzer, most likely the version of `@angular/compiler` that you have in your `node_modules` doesn't export `CssSelector`.

**Comment by crebuh** [comment]
@mgechev 

I'm using angular at version 2.1.0. also the compiler

**Comment by mgechev** [comment]
Yes, this is a violation of the `peerDependencies`, which require Angular `^2.2.0`. You can update the dependencies of your project and it should work.
