### ISSUE TITLE
Does this check template if its in a seperate file using TemplateUrl?

### ISSUE THREAD

**Issue by surenrao** [mgechev/codelyzer#176]
I am not able to get any warnings or error when the template is a file. Is there a setting i am missing? or it only supports inline template? Thanks

**Comment by mgechev** [comment]
What version are you using? Are you running the linter over command line or you're expecting warnings inline in your text editor/IDE? The later is not going to work for now since I'm reusing the tslint plugin for VSCode/Atom/etc. which lints only ts & tsx files.

**Comment by surenrao** [comment]
i am using latest angular 2.2 and codelyzer 0.0.26. I am using webpack in dev mode under console.

**Comment by mgechev** [comment]
You need codelyzer@2.0.0-beta.1.

**Comment by sgronblo** [comment]
I am trying to get this working in 2018 with codelyzer@4.2.1 and it doesn't seem to be working.
