### ISSUE TITLE
Component as attribute

### ISSUE THREAD

**Issue by mastertinner** [mgechev/codelyzer#178]
The rule `component-selector-name` allows to only allow components either to be elements **or** attributes. We would like to allow both in our project but still keep the rule for its other aspects (e.g. checking if component's selectors are kebab-case). Is that somehow possible? It would be nice to be able to specify the following:

`"component-selector": [true, ["attribute", "element"], "ec", "camelCase"]`

Generally we don't want to allow components as attributes but there are cases where we think it's needed. Here's an example: We are trying to `ngFor`-loop a `<tr>` element with a template. So the `<tr>` needs to be a component. If we do that using an element selector, the table breaks because the structure of the final HTML is:

```html
<table>
  <tbody>
    <my-component>
      <tr>
        <td>January</td>
        <td>$100</td>
      </tr>
    </my-component>
    <my-component>
      <tr>
        <td>February</td>
        <td>$80</td>
      </tr>
    </my-component>
  </tbody>
</table>
```

We would, however, need it to be (which works using the component as an attribute of <tr>):

```html
<table>
  <tbody>
    <tr>
      <td>January</td>
      <td>$100</td>
    </tr>
    <tr>
      <td>February</td>
      <td>$80</td>
    </tr>
  </tbody>
</table>
```

Is there any other way of doing that except for using the component as an attribute?

**Comment by mgechev** [comment]
I understand there are some cases when using components as attributes is required, another example is a resizable component. For such cases I'd recommend disabling the rule for the specific line. We're still using tslint as error reporting mechanism so you can take advantage of the ["disabled intervals"](https://palantir.github.io/tslint/usage/rule-flags/).
