### ISSUE TITLE
False positive of no-access-missing-member

### ISSUE THREAD

**Issue by mastertinner** [mgechev/codelyzer#179]
I think the rule `no-access-missing-member` is throwing false positives in the following case of a component template:

```html
<my-component [thing]="myThing">
  <div #myThing></div>
</my-component>
```

In this case, I'm getting `The property "myThing" that you're trying to access does not exist in the class declaration.` which shouldn't matter because `myThing` is defined in the HTML. Does it need to be defined again in the class? I think adding it as a `#myThing` attribute should be sufficient.

**Comment by mgechev** [comment]
Yes, this seems like an issue. I haven't formed properly the "symbol table" that I use for checking for existing in case of references.

**Comment by mgechev** [comment]
@mastertinner the fix will be published in the next beta.

**Comment by mastertinner** [comment]
Awesome! Thx, @mgechev!
