### ISSUE TITLE
Angular 2.3.0

### ISSUE THREAD

**Issue by nicolashenry** [mgechev/codelyzer#182]
Can you update the peer dependencies to the version 2.3.0 ?

I got this message updating angular :
```
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/compiler@~2.2.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/core@~2.2.0 but none was installed.
```

**Comment by mgechev** [comment]
Fixed here https://github.com/mgechev/codelyzer/commit/20ce61a64346b9ac17a1d5d5f364889ef90e6d47. Will be released by the end of the day (hopefully).

**Comment by nicolashenry** [comment]
@mgechev Thanks!
