### ISSUE TITLE
transformStyle eats errors

### ISSUE THREAD

**Issue by UnwrittenFun** [mgechev/codelyzer#196]
Given this in .codelyzer.js

```js
module.exports = {
    transformStyle(code, url, decorator) {
        throw new Error('Something went horribly wrong');
    },
};
```

When running the lint task it will not display the error, which makes it look like the styles are passing lint!

transformTemplate does not suffer from the same issue.

Node: 6.9.1
Tslint: 4.0.2
Codelyzer: 2.0.0-beta.3
Angular: 2.2.3

**Comment by mgechev** [comment]
It's intentional to not throw when a style is not transformed successfully but this doesn't eat linting errors.

**Comment by UnwrittenFun** [comment]
😕 Lost a couple hours due to this. No warning whatsoever that your transform or styles are broken is pretty worrying to me

**Comment by mgechev** [comment]
I agree, I will add a bolded warning to the `README.md` file.
