### ISSUE TITLE
no-access-missing-member and template local variables

### ISSUE THREAD

**Issue by alain38** [mgechev/codelyzer#198]
I get _"The property "loginControl" that you're trying to access does not exist in the class declaration"_ when i try to tslint the following template (this is  in a template driven form)

### The template
          <div class="form-group" [ngClass]="{'has-success': loginControl.valid, 'has-danger': !loginControl.valid && loginControl.dirty}">
          <label for="login" class="sr-only">Your name</label>
          <input type="text" id="login" name="login"
                 [(ngModel)]="credentials.login"
                 class="form-control form-control-success"
                 placeholder="Enter your name"
                 minlength="3"
                 #loginControl="ngModel"
                 required autofocus />
          <div id="login-length-error" *ngIf="loginControl.hasError('minlength') && loginControl.dirty">
            <small class="form-text text-muted">Your login should be at least 3 characters</small>
          </div>

The line giving the error is the first line:
`<div class="form-group" [ngClass]="{'has-success': loginControl.valid, 'has-danger': !loginControl.valid && loginControl.dirty}">`

I think i get an error because the loginControl variable is defined forward (but bootstrap wants you to put the class has-error on the div with class form-group containing the input text)

The line : 
`<div id="login-length-error" *ngIf="loginControl.hasError('minlength') && loginControl.dirty">`
 does not give any error.

### The component class:
```
export class LoginComponent {
  credentials = {
    login: '',
    password: ''
  };
  authenticationFailed: boolean = false;
  authenticate() {...
}
```

tslint 4.0.2
codelyzer 2.0.0-beta.3
typescript 2.1.4

Thank you for examining the problem.

**Comment by mgechev** [comment]
With the`predefinedDirectives` which you can declare in `.codelyzer.js`, you can declare that you have: `{ selector: "[ngModel]", exportAs: "ngModel" }`.

Take a look at this issue https://github.com/mgechev/codelyzer/issues/173

**Comment by alain38** [comment]
Thank you very much. I should have read the advanced documentation.
this code did the trick in .codelyzer.js for the example above

```
module.exports = {
  predefinedDirectives: [
    {
      selector: '[ngModel]',
      exportAs: 'ngModel'
    },
    {
      selector: 'form',
      exportAs: 'ngForm'
    }
  ]
};
```

**Comment by mgechev** [comment]
No problem. I will add all these by default on the next release.
