### ISSUE TITLE
New beta release possible?

### ISSUE THREAD

**Issue by clydin** [mgechev/codelyzer#201]
Time permitting, is there any chance a beta4 could be released with the tslint peer dep update?

**Comment by clydin** [comment]
Also, I added a PR (#202) to update the dependencies for angular 2.4.

**Comment by mgechev** [comment]
Thanks for the PR! I'll try to publish new version tomorrow morning.

**Comment by mhoyer** [comment]
@mgechev what do you think about my comment https://github.com/mgechev/codelyzer/pull/202#pullrequestreview-13933863

**Comment by mgechev** [comment]
Beta.4 is out.
