### ISSUE TITLE
TypeError: Cannot read property 'AbstractRule' of undefined

### ISSUE THREAD

**Issue by loicsalou** [mgechev/codelyzer#205]
facing blocking issue when trying to use codelyzer in my projects.
Stack is
TypeError: Cannot read property 'AbstractRule' of undefined
    at Object.<anonymous> (C:\tools\Workspaces\Angular2\zas-angular2-starter\node_modules\codelyzer\propertyDecoratorBase.js:34:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\tools\Workspaces\Angular2\zas-angular2-starter\node_modules\codelyzer\useInputPropertyDecoratorRule.js:7:31)
    at Module._compile (module.js:570:32)

I'm using libraries as described in attached package.zip

**Comment by loicsalou** [comment]
can't seem to be able to attach zip I'm afraid. So here's my package.json deps part:

>   "dependencies": {
>     "@angular/common": "~2.4",
>     "@angular/compiler": "~2.4",
>     "@angular/core": "~2.4",
>     "@angular/forms": "~2.4",
>     "@angular/http": "~2.4",
>     "@angular/platform-browser": "~2.4",
>     "@angular/platform-browser-dynamic": "~2.4",
>     "@angular/router": "~3.4",
>     "core-js": "~2.4.1",
>     "lodash": "~4",
>     "ng2-translate": "~5",
>     "oblique-ui": "1.3.0",
>     "rxjs": "~5.0",
>     "ts-helpers": "~1.1",
>     "zas-web-components": "~0",
>     "zone.js": "~0.7"
>   }

**Comment by mgechev** [comment]
It does, you need codelyzer 2.0.0-beta.4.

**Comment by loicsalou** [comment]
that's the one I'm using...
Any clue / adivce I can investigate in order to solve this ?
Thanks

**Comment by mgechev** [comment]
You need tslint@^4.0.0.

**Comment by loicsalou** [comment]
using 4.2.0.
my command-line: "tslint \"components/**/*.ts\" -o linters/tslint.txt -t verbose"

**Comment by mgechev** [comment]
Use `./node_modules/.bin/tslint "components/**/*.ts" -o linters/tslint.txt -t verbose`.

**Comment by loicsalou** [comment]
exactly the same result (tslint is installed globally and same version locally). As you closed the issue I suppose I have missed something. Still got the issue on 2 projects. Will note here if I can find a solution.

**Comment by mgechev** [comment]
It's a version mismatch between codelyzer and tslint.

You can try the ["Custom setup"](https://github.com/mgechev/codelyzer#custom-setup) in another directory and verify if everything works together.

**Comment by loicsalou** [comment]
So this is the end. Thanks for helping you are totally right I had a version mismatch with tslint. I ended specifying tslint+codelyzer in the dev dependencies of my projects in order to make sure each of them is using consistent versions in all linters.
my current versions are tslint 4.2.0 and codelyzer-2.0.0-beta.4.

**Comment by mgechev** [comment]
Awesome! I am glad it worked in the end.

**Comment by grahamfowles** [comment]
I was seeing this issue with the atom-typescript plugin, every time i typed a key an error message appeared which was more than a little annoying

You solution worked for me, thanks

**Comment by shortthirdman** [comment]
Facing the same issue with the following configuration in my `poackage.json`.

`"dependencies": {
    "@angular/animations": "~5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/router": "~5.0.0",
    "@angular/upgrade": "~5.0.0",
    "angular-in-memory-web-api": "~0.1.8",
    "bootstrap": "^3.3.7",
    "c3": "^0.4.18",
    "clipboard": "~1.5.10",
    "core-js": "^2.4.1",
    "d3": "^4.12.2",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "primeng": "~5.0.0",
    "primeui": "4.1.15",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.0.0",
    "systemjs": "~0.19.39",
    "zone.js": "~0.8.4"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.44",
    "@types/node": "^9.3.0",
    "codelyzer": "2.0.0-beta.4",
    "concurrently": "^3.0.0",
    "del": "2.2.2",
    "gulp": "github:gulpjs/gulp#4.0",
	"gulp-changed": "~1.3.0",
    "gulp-concat": "~2.6.0",
    "gulp-connect": "~2.2.0",
    "gulp-if": "~2.0.0",
    "gulp-imagemin": "~3.0.3",
    "gulp-inject": "~3.0.0",
	"gulp-inline-ng2-template": "~0.0.10",
    "gulp-load-plugins": "~1.1.0",
    "gulp-preprocess": "~2.0.0",
    "gulp-protractor": "~2.1.0",
    "gulp-sass": "~2.2.0",
    "gulp-sass-lint": "~1.1.0",
    "gulp-size": "~2.0.0",
    "gulp-sourcemaps": "~1.6.0",
    "gulp-tslint": "~4.1.2",
    "gulp-typedoc": "~1.2.1",
    "gulp-typescript": "~2.10.0",
    "gulp-uglify": "~1.5.1",
    "phantomjs-prebuilt": "2.1.6",
    "remap-istanbul": "0.4.0",
    "systemjs-builder": "^0.15.19",
    "tslint": "~3.15.1",
    "typescript": "^2.0.2",
    "typings": "~2.0.0"
  }`
