### ISSUE TITLE
RFC: Allow attribute selectors for SVG

### ISSUE THREAD

**Issue by SteveVanOpstal** [mgechev/codelyzer#208]
SVG does not allow the use of custom elements like HTML5 does. SVG's will not render the contents of a custom element ([example](https://plnkr.co/edit/7xXFQ5?p=preview)). The solution for that is to use attribute selectors (https://github.com/angular/angular/issues/1632#issuecomment-152285672).

**Current behavior**
Codelyzer does not allow attribute selectors on components (Due to [style guide 05-03](https://angular.io/docs/ts/latest/guide/style-guide.html#!#05-03)):
``` TypeScript
@Component({
  selector: 'g[appCustom]'
  ...
```

> [tslint] The selector of the component "CustomComponent" should be named kebab-case and include dash (https://goo.gl/mBg67Z) (component-selector)

**Desired behaviour**
A new config for SVG components:
``` JSON
"svg-component-selector": [
  true,
  "element",
  "app",
  "camelCase"
],
```

The [style guide](https://angular.io/docs/ts/latest/guide/style-guide.html) does not mention SVG components and how to handle them but [this comment](https://github.com/angular/angular/issues/1632#issuecomment-98933990) confirms that SVG support is intended.

Figuring out if a component is an SVG component is quite easy as Angular 2 requires the `svg` namespace to be given on the root element (https://github.com/angular/angular/issues/7216#issuecomment-246158949).

**Comment by mgechev** [comment]
Sounds like a good to have feature. I'll include it into the backlog.

Until it's implemented, you can disable the rule for this file/component.

**Comment by mgechev** [comment]
Lets close the issue for now and reopen it if there's more interest.

**Comment by yluijten** [comment]
@mgechev do you have any idea when this issue will be picked up?

**Comment by mgechev** [comment]
You can disable the codelyzer rule for a specific component.

**Comment by yluijten** [comment]
@mgechev can this one be reopened? Looks like there's enough interest for it.

**Comment by subramaniashiva** [comment]
I am facing the same issue. Would be happy if this reopened
