### ISSUE TITLE
Support the tslint fix

### ISSUE THREAD

**Issue by Bigous** [mgechev/codelyzer#211]
Hi,

This is a feature request.

Some rules can be automatically fixed by tslint. They've created a mechanism to know if it's a [fixable](https://github.com/palantir/tslint/blob/master/src/rules/quotemarkRule.ts#L32) rule and creates a [fix](https://github.com/palantir/tslint/blob/master/src/rules/quotemarkRule.ts#L125) if it was required.

Some of codelyzer rules are fixable, (white space for example). And I think it would be very nice to have this rules fixed automagically when possible (specially if you have a project without that rule and starts using the rule).

**Comment by mgechev** [comment]
Autofixes are in the roadmap. Since I have a few other things on my plate before that, it'll be lovely if anyone is willing to help.

The API is user friendly. (Un)Fortunately because of the current format of the TypeScript AST it is mostly an abstraction on top of primitive string manipulations.

**Comment by Bigous** [comment]
I'll try to help in this.

**Comment by GregOnNet** [comment]
Hi,

I also tried to add a fix for #300 like described in the docs of tslint: https://palantir.github.io/tslint/develop/custom-rules/

My orovided fix was recognised by VS Code but unfortunately was not applied when clicking on the tooltip.

Do you know what is needed to get tslint fixes to work?

Kind regards
Gregor

**Comment by mgechev** [comment]
We're working incrementally on supporting tslint fixes. We have them for all newly implemented rules.

Closing this one since it's quite generic.
