### ISSUE TITLE
no-access-missing-member reporting missing member for referenced template variables

### ISSUE THREAD

**Issue by Delagen** [mgechev/codelyzer#213]
```html
<div #aaa="aaa">
   <span *ngIf="aaa.property">
```

**Comment by mgechev** [comment]
You need to declare the template reference in `.codelyzer.js`. Take a look at the advanced configuration in the readme.

**Comment by Delagen** [comment]
So this not usable in production, cause nobody do writing list of this in large project

**Comment by mgechev** [comment]
If you have that many template references that you can't list in a file, you can disable this rule/do not use the tool.
