### ISSUE TITLE
Warn me when I break AoT 

### ISSUE THREAD

**Issue by ocombe** [mgechev/codelyzer#215]
Hello,

I would love if Codelyzer could warn me when I do something in my code that will break AoT.
The current error messages when you try to add AoT to an existing app are really cryptic and not useful at all.

Do you think that Codelyzer could check for that? I think that it would make this lib so useful that it would be included in all angular apps :-)

Let's start a list of the things that break AoT to see what could be checked (correct me if I'm wrong):
- [x] private / protected properties used in templates
- [ ] using external values insides string templates (with `${...}`) instead of class properties
- [ ] using require() (instead of import) to load angular code that uses decorators, or to load template/styles
- [ ] not exporting interfaces / types (even if you don't use them outside of the current file)
- [ ] using "export default"
- [ ] using form.controls.controlName instead of form.get('controlName')
- [ ] using control.errors?.someError instead of control.hasError(‘someError’)
- [ ] using functions in decorators (especially routes / ng modules) instead of using the reference to an exported function
- [ ] using external angular libs that don't include *.metadata.json files

Do you know of any other things that break AoT? Do you think you could check for some (of most) of these?

**Comment by teropa** [comment]
See also this documentation gist by @chuckjaz https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60

**Comment by ocombe** [comment]
Interesting, thanks @teropa ! This explains a lot of the errors that I listed and should be helpful to @mgechev if he decides to do that :)

**Comment by mgechev** [comment]
Nice list! We have partial support at the moment by warning when you try to bind to missing or non-public properties or methods.

I'm not sure to what extent it's worth implementing the above rules in case soon in development we switch to ngc from tsc and get all the errors from there. I will sync with Alex Eagle on that.

**Comment by mgechev** [comment]
I think it'll be better to wait until `ngc` becomes the default in Angular CLI and we get the compiler errors during the incremental compilation.

This should happen at some point (hopefully soon). However, if anyone is willing to help with the listed rules I'll be happy to assist. Otherwise, there are a few more critical issues to take care about such as missing context for the template parser and incorrect symbol references.

**Comment by shamim4063** [comment]
dynamic-component-loader will not work but it will not throw any error in compile time.
