### ISSUE TITLE
Bug: Component Inheritance is not getting inferred

### ISSUE THREAD

**Issue by amcdnl** [mgechev/codelyzer#219]
If I have a component that inherits from another component and the template of the inherited component accesses variables from the base component, those variables are not being inferred on the inherited component.

Error:
```
WARNING in ./src/components/dialog/alert/alert.component.ts
[15, 23]: The property "title" that you're trying to access does not exist in the class declaration.
```

Example:

In base class, I define `title`...

```
@Component({
  selector: 'my-dialog',
  template: `
    <div>{{title}}</div>
  `
})
export class DialogComponent {
  @Input() title: string;
}
```

then inherited class template, I use `title`...

```
@Component({
  selector: 'my-dialog',
  template: `
    <div>{{title}}</div>
  `
})
export class AlertDialog extends DialogComponent  { }
```

**Comment by mgechev** [comment]
Hey, this is a known issue https://github.com/mgechev/codelyzer/issues/191. I will work on it soon, I hope. In the mean time, if anyone finds some spare time a PR will be appreciated.
