### ISSUE TITLE
Template micro-syntax closure and 'bind only to public class members'

### ISSUE THREAD

**Issue by artaommahe** [mgechev/codelyzer#220]
This
```html
<div *ngFor="let smile of smile">
  <smile-cmp [smile]="smile"></smile-cmp>
</div>
```
```ts
constructor(private smile: SmileService,
```
will provide error
```
You can bind only to public class members.
```

**Comment by mgechev** [comment]
Good catch! I'll include fix in one of the next releases. Since the issue is not very high-priority, the fix might not be introduced as part of beta.5.

**Comment by Shahor** [comment]
Having the same exact problem right now. 
Quite annoying :D

**Comment by mgechev** [comment]
In fact, there are two issues here:

- The `smile` inside `ngFor` should be reported, since it's not public.
- The `smile` declared in the lexical scope of `<div/>` should not be reported.

Publishing a fix for the second one.
