### ISSUE TITLE
Compilation with `declaration` enabled doesn't work

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#221]
After the recent refactoring the generation of type definitions stopped working.

@ghsyeung would you have chance to take a look at it?

**Comment by ghsyeung** [comment]
will take a look tonight

**Comment by ghsyeung** [comment]
how can I reproduce? "npm run release"?

**Comment by mgechev** [comment]
Thanks! Yes, I'm assigning it to you.

**Comment by ghsyeung** [comment]
Took a look last night, still deciding how not to leak implementation types
at the library level.
I should have something ready soon.
