### ISSUE TITLE
Patterns proposal (input-set and template-get)

### ISSUE THREAD

**Issue by michaeljota** [mgechev/codelyzer#222]
This is just an idea that I've seen in a couple of projects, and I want your opinion about it. The main principle behind them, it's to decouple the properties that have to be exposed to the template, off the properties that the component receives with an input.

Input-Set 
----------
The properties that need to be `input`ed, should be just set functions to a private property.

Using model:
```json
{
  "user": {
    "type": "object",
    "properties": {
      "firstName": {
        "type": "string"
      },
      "lastName": {
        "type": "string"
      }
    }
  }
}
```

So, instead of:
```ts
class Component {
...
  @Input() public user: User;
...
}
```
I propose:
```ts
class Component {
...
  @Input() public set user(value: User) {
    this._user = value;
  }

  private _user: User;
...
}
```

Template-get
---------------

Now, as our properties are now set-only, we should be able to allow for some kind of reading from the template. But, instead of just bind the property as a whole, it would be a waste of time I believe, just bind the properties of that `input`ed property that the template will really show, as it will show them. 

Instead of:
```ts
class Component {
...
  // Autobinding with template as a public property with not constrains. 
  @Input() public user: User;
...
}
```
or
```ts
class Component {
...
  // Property binding with template as a public property returning the same `input`ed object. 
  public get user(): User {
    return this._user;
  }
  private _user: User;
...
}
```
Both with template using:
```html
<div> First Name: {{ user.firstName }} </div>
<div> Last Name: {{ user.lastName }} </div>
```

I propose:
```ts
class Component {
...
  // Property binding with template as a collection of public properties returning the desires properties of that object. 
  public get firstName(): string{
    return this._user.firstName.;
  }
  public get lastName(): string{
    return this._user.lastName.;
  }
  private _user: User;
...
}
```
To template using:
```html
<div> First Name: {{ firstName }} </div>
<div> Last Name: {{ lastName }} </div>
```

Reasoning
---

- Separations of concerns. The template should not be aware of the properties that are being `input`ed, nor the properties that this have. This should concern only to the Component.
- Composability. This patterns allows for the component to compose special properties for the template to consume. 

Sorry for the long issue. I don't have any potatoes right now. I hope you like this, and find this useful.

**Comment by mgechev** [comment]
Sounds like a reasonable idea. I'll suggest to propose it at [angular.io](https://github.com/angular/angular.io/issues) and if it gets approved, we can implement a corresponding rule.

If you open an issue there, please add link in the discussion here.

Until the proposition gets approved, I'd suggest to close this issue.

**Comment by michaeljota** [comment]
I did not forget about this, I just wanted to give a better example and be clearer about it. Thanks you for the guidance and the assistance.
