### ISSUE TITLE
Installation Fail  (Failed at the node-sass@4.5.0 install script 'node scripts/install.js'.)

### ISSUE THREAD

**Issue by RuSTer1241** [mgechev/codelyzer#228]
**

[npm-debug.log.tar.gz](https://github.com/mgechev/codelyzer/files/751114/npm-debug.log.tar.gz)

Ubuntu terminal log:**
developer@image-4963-l:~/Projects/angular-quickstart/angular_tutor/codelyzer_demo$ **sudo npm install -g @angular/cli**
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng

> node-sass@4.5.0 install /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
/usr/local/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.
npm ERR! Linux 3.13.0-88-generic
npm ERR! argv "/opt/node/bin/node" "/usr/local/bin/npm" "install" "-g" "@angular/cli"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/developer/Projects/angular-quickstart/angular_tutor/codelyzer_demo/npm-debug.log
npm ERR! code 1
developer@image-4963-l:~/Projects/angular-quickstart/angular_tutor/codelyzer_demo$ ll
total 704
drwxrwx--- 3 developer developer   4096 лют  3 19:07 ./
drwxrwx--- 7 developer developer   4096 лют  3 18:00 ../
drwxrwx--- 9 developer developer   4096 лют  3 18:38 angular-seed/
-rw-r----- 1 root      root      705557 лют  3 19:07 npm-debug.log

**Comment by mgechev** [comment]
Is it related to codelyzer or an angular-cli issue?

**Comment by RuSTer1241** [comment]
Angular CLI!  I tried to install angular CLI.

**Comment by dylanjmorgan** [comment]
I am also unable to install angular cli becasue of this...

**Comment by k1xme** [comment]
+1, trying to install Laravel Mix but failed in there

**Comment by Xertz** [comment]
Did not happen when I'd install it, but when I tried to create a new project.

After all files were created and started to install packages, it throws this error. The weird thing is that inside **package.json** there is no **node-sass** as a dependency whatsoever.`
