### ISSUE TITLE
Better logging of errors required

### ISSUE THREAD

**Issue by negberts** [mgechev/codelyzer#229]
With the new package we get errors like 'You can bind only to public class members.' with occur to happen at line 1, column 1 of the HTML template. But the template has `<div class="main-menu-button"> `on the first line. 

If I look to the code of the templatesUsePublicRule the specific member is known. So could we at least have the name of the member or method that is causing the error in the error message and not a generic error?

**Comment by mgechev** [comment]
Yes, I'll include this in the backlog.

**Comment by mgechev** [comment]
@negberts it'll be amazing if you have time to open a PR! The change will not require deep understanding of the project.

**Comment by negberts** [comment]
Sorry, just had a little baby girl so no spare time left :) But I see somebody else was helpfull!
