### ISSUE TITLE
Atom Issues

### ISSUE THREAD

**Issue by t0rrro** [mgechev/codelyzer#23]
I have a tslint.json in my base directory with 
`"rulesDirectory": ["node_modules/codelyzer/dist/src"]`

But I get constant errors from Atom saying Could not find custom rule directory: /node_modules/codelyzer/dist/src

I saved codelyzer to both global and as a dev dependency

**Comment by bluEEil** [comment]
I had similiar problem
I changed it to the following:
"rulesDirectory": ["node_modules/codelyzer"]

after that I still had problem that it missed the typescript package in my project (I had it in the global node_modules folder and not the project one) so I added the typescript folder to the project node_modules and than it worked

**Comment by t0rrro** [comment]
Still can't find it. I see the codelyzer folder in node_modules

**Comment by mgechev** [comment]
Go to Settings -> Packages -> Linter Tslint

In "Custom rules directory (absolute path)" add the absolute path pointing to your rules directory (in my case "/Users/mgechev/Projects/angular2-seed/node_modules/codelyzer").

**Comment by bluEEil** [comment]
Is the path you stated "node_modules/codelyzer/dist/src" really exists? for me it was incorrect after installing like the README said (I had not dist folder in there)

**Comment by mgechev** [comment]
Today I just changed codelyzer...let me update the readme.

**Comment by t0rrro** [comment]
Yep, that fixed it for me. Thanks
