### ISSUE TITLE
Document all rules in a single place

### ISSUE THREAD

**Issue by lestard** [mgechev/codelyzer#230]
At the moment it's quite hard to find out what the reasons for some of the rules is because (as far as I know)  there is no single place where all rules are documented.

In the past I've worked with Java checking tools and they typically have a good documentation of all rules including the reasoning behind the rule, examples for failing code and configuration parameters. 

Examples:
- [PMD](https://pmd.github.io/pmd-5.5.3/pmd-java/rules/java/controversial.html)
- [Checkstyle](http://checkstyle.sourceforge.net/config_naming.html#AbstractClassName)

When a rule breaks the error message already includes the link to the specific rule so that you can easily read what is wrong.

This way a code analyzing tool does not only help to prevent errors but helps the developers to learn by describing *why* something is wrong.

**Comment by ghsyeung** [comment]
I think rules follows mostly 3 categories, 

1. Angular style guide (https://angular.io/styleguide)
2. AOT related
3. others

Category 1 should be just adding a link to the Angular style guide page.
I am not sure if there's a single source on category 2. 

Maybe we can start a wiki page to organize rules into categories and then evolve from there?

**Comment by mgechev** [comment]
This issue is related to https://github.com/mgechev/codelyzer/issues/234. If anyone is willing to add the metadata we can automatically generate the documentation.

At the moment I'm working on the metadata collection, support for inheritance and testing improvements. Help will be appreciated!

**Comment by mgechev** [comment]
http://codelyzer.com/rules/
