### ISSUE TITLE
"templates-use-public" results in a false-positive when inheritance is in play

### ISSUE THREAD

**Issue by DethAriel** [mgechev/codelyzer#232]
Consider this code:

```ts
export abstract class MyAbstractComponent {
  public something: any;
}

@Component({ 
  template: `{{ something }}`,
})
export class MyRealComponent extends MyAbstractComponent {
}
```

If you run `tslint` with `"templates-use-public"` rule enabled, you'll get an error:

> The property "something" that you're trying to access does not exist in the class declaration.

which is kinda true, but this is still a false positive.

**Comment by ghsyeung** [comment]
Related to #191

**Comment by DethAriel** [comment]
@ghsyeung I would even say that it's a duplicate. Closing the issue
