### ISSUE TITLE
Rules destination

### ISSUE THREAD

**Issue by laco0416** [mgechev/codelyzer#24]
I think `node_modules/codelyzer/dist/src` is not intuitive. Mainly **dist/src** part.

I'd like to import rules from `node_modules/codelyzer/dist/rules` or `.../dist/ng2lint`

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/codelyzer/commit/c8217cbeda1e79639f858fe234b57a32cac9202e.

**Comment by laco0416** [comment]
Thank you!
