### ISSUE TITLE
Analyze Html interpolated strings for custom localization

### ISSUE THREAD

**Issue by ndcunningham** [mgechev/codelyzer#243]
It would be a great feature if we could have our html interpolation satisfy one or many rules especially for localization.  

Example
`<div>{{ myVariable }}</div>` 

A rule for interpolated strings would be it needs to call a given function which would translate if necessary. This is really helpful if we have split teams and during a push, we could just check the _lint_ to see if all strings used inside the template are called by that function

So it would display a warning / error saying that the string doesn't satisfy localization.

`<div> {{ localeService.localize(myVariable) }} </div>`

Would satisfy the rule condition for string interpolation.

Might be a crude way of looking at it, just what i thought and the problem our team is facing.

**Comment by mgechev** [comment]
That's for the detailed description. `localeService` doesn't seem to be part of the official Angular i18n API, right?

I'm not sure if we should support third-party solutions since the scope of the project will constantly grow.

**Comment by ndcunningham** [comment]
That's true, I just wanted to know if you would support something like this.

**Comment by mgechev** [comment]
At this point I think it's better to not include such rule.

Once I move the parsing logic into a separate class, you'll be able to reuse it and write a custom rule for your specific case.
