### ISSUE TITLE
Template parsing

### ISSUE THREAD

**Issue by akhileshcoer** [mgechev/codelyzer#247]
I'm trying to write custom rule by parsing HTML files or template in ts files.
What is right way to start on, any links would be appreciated.

**Comment by mgechev** [comment]
You can use [this rule as a base](https://github.com/mgechev/codelyzer/blob/master/src/noAccessMissingMemberRule.ts).

At some point I'll extract the parsing logic [as a separate package](https://github.com/mgechev/ngast).
