### ISSUE TITLE
Cannot read property 'full' of undefined

### ISSUE THREAD

**Issue by jdjuan** [mgechev/codelyzer#252]
The following set of rules are giving me an error when I run `npm run lint`:

**Context**

1. I created an Angular 2 project using the CLI (using `ng new`)
2. Upgraded to tslint version: ^4.4.2
3. Upgraded to codelyzer version: ^3.0.0-beta.0
4. Angular version used: 2.2.1
5. Run the commands using: `npm run lint` or `ng lint`

**Rules causing it:**

1. "no-attribute-parameter-decorator": true
2. "no-input-rename": true
3. "no-output-rename": true
4. "pipe-naming": [true, "camelCase", "app"]
5.  "component-class-suffix": true
6.  "directive-class-suffix": true
7.  "templates-use-public": true
8.  "no-access-missing-member": true
9.  "invoke-injectable": true

For the rest: It works just fine

**Stack trace:**

```
C:\Users\projects-folder\ng-core-2\node_modules\tslint\lib\runner.js:120
            throw error;
            ^

TypeError: Cannot read property 'full' of undefined
    at Object.<anonymous> (C:\Users\juan.herrera\proyectos\brainshark\ng-core-2\node_modules\codelyzer\util\ngVersion.js:4:58)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\juan.herrera\proyectos\brainshark\ng-core-2\node_modules\codelyzer\angular\templates\templateParser.js:5:19)
    at Module._compile (module.js:541:32)
```

**Comment by mgechev** [comment]
I'll take a look at this issue today. At first, it looks like`version` imported from `@angular/core` is undefined but looks unlikely.

**Comment by jdjuan** [comment]
@mgechev my bad, when I installed the latest version of Codelyzer I didn't notice the UNMET PEER DEPEDENCY warning of @angular packages (core, compiler, compiler-cli). After updating them as well, I had it working. Thanks for your time @mgechev , sorry for this unnecessary issue.

**Comment by mgechev** [comment]
Thanks for sharing your comment!

**Comment by NKjoep** [comment]
@mgechev I have this issue when an older version of @angular/core is resolved (or stays unresolved). This happens if you have an old project or your main package.json is outdated.

I would suggest to add a fallback or throw a friendlier error. `ngVersion.js` is something like:

```js
  "use strict";
  var core_1 = require("@angular/core");
  var semver_dsl_1 = require("semver-dsl");
  exports.SemVerDSL = semver_dsl_1.SemVerDSL(core_1.VERSION.full);
```

That would be nice to prevent `.VERSION.full` to fail

**Comment by mgechev** [comment]
What's the value of `.Version.full` in that older version? I suppose `Version` is not exported?

**Comment by NKjoep** [comment]
Exactly, there's no `VERSION` at all, unfortunately.
