### ISSUE TITLE
Warn for redundant NgModule imports

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#256]

**Comment by lazarljubenovic** [comment]
Do you have an outline about what is considered a "redundant" import? I'm interested in working on it.

**Comment by mgechev** [comment]
Here's an example:

```ts
@NgModule({
  export: [CommonModule, ...]
})
class ImportModule {}

@NgModule({
  imports: [CommonModule, ImportModule]
})
class AppModule {}
```

The `CommonModule` import in `AppModule` is not required, since `ImportModule` exports it.

This seems like an interesting problem to solve. Probably, it'll require linting of all classes decorated with `@NgModule` and extracting their direct and transitive dependencies using `ngast`.

You can take a look at the `3.0.0-beta.x` branches and [ngast](https://github.com/mgechev/ngast) for further information.

**Comment by HideDev** [comment]
A very useful rule, we are waiting!

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
