### ISSUE TITLE
Set the peerDependency ngast to ^0.0.4

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#257]

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/codelyzer/commit/30e921a48fb98b9d929d46f905aa87d3d7e81d98.

**Comment by Owain94** [comment]
npm ERR! notarget No compatible version found: ngast@^0.0.4
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.0, 0.0.1, 0.0.2, 0.0.3, 0.0.5

**Comment by mgechev** [comment]
You can try with codelyzer@3.0.0-beta.3.

**Comment by Owain94** [comment]
Builds are passing with beta 3 again, thanks!
