### ISSUE TITLE
Methods not exist in the class when class extended with decorator

### ISSUE THREAD

**Issue by rokerkony** [mgechev/codelyzer#258]
Hey guys,
I'm getting an error from templates:
`The method "areElementsValid" that you're trying to access does not exist in the class declaration.`

I will try to describe my case.

I have a component where I define form and this component is extended by decorator `@AddValidationHandling()` which is extending prototype of the class with some methods including `areElementsValid`. So code itself is working and methods are accessible but I get all the errors from codelyzer about methods not exist.

Simplified decorator:
```ts
export function AddValidationHandling (): Function {
    return (target: any): Function => {
        target.prototype = Object.assign(ValidationForm.prototype, target.prototype);
        return target;
    };
}

function ValidationForm (): void {}
ValidationForm.prototype. areElementsValid = function (formGroup: FormGroup, elementNames: string|string[]): boolean {
        // ...
        return isValid;
    }
};
```

and usage:

```ts
@Component({
    // ...
})
@AddValidationHandling()
export class OfferFormComponent {
    // ...
}
```

**Comment by mgechev** [comment]
@rokerkony codelyzer does static code analysis. In `@AddValidationHandling` you dynamically set the prototype of the target class.

There are a lot of dynamic constructs which are not statically analyzable, i.e. not supported by codelyzer. 

Does this code compilers with Angular's AoT compiler?

**Comment by rokerkony** [comment]
Angular CLI with `--aot=true` does all the magic... at least I tried on as minimal example as possible:
```ts
import {Component} from '@angular/core';

function AddCallMe (): Function {
  return (target: any): Function => {
    target.prototype = Object.assign({
      callMe: function (value: any) {
        console.log('called with: ', value);
      }
    }, target.prototype);
    return target;
  };
}

@Component({
  selector: 'app-root',
  template: `see call method in console {{callMe(12)}}`,
})
@AddCallMe()
export class AppComponent {}
```

any idea if it is achievable by codelyzer as well in the future?

looks like it could be related with https://github.com/Microsoft/TypeScript/issues/4881
