### ISSUE TITLE
Do we need "Invoke Injectable" rule?

### ISSUE THREAD

**Issue by lazarljubenovic** [mgechev/codelyzer#260]
Do we really need this as a rule? TypeScript simply fails if it's not invoked:

```
Error:(16, 1) TS1238:Unable to resolve signature of class decorator when called as an expression.
  Supplied parameters do not match any signature of call target.
```

I see it being suggested in https://github.com/mgechev/codelyzer/issues/70, but is really all that "mysteriously"? My IDE (WS) also clearly underlines it.

**Comment by mgechev** [comment]
Good point. There should be a clean-up. Few rules which are no longer required are:

- templates-use-public
- no-access-missing-member
- invoke-injectable

The final one is handled by the tsc, first two by ngc.

**Comment by mgechev** [comment]
https://github.com/mgechev/codelyzer/issues/264

**Comment by t-ricci-molecle** [comment]
wow, I took some time to figure out why `ng lint --type-check` was giving me errors about missing rules after the update. I couldn't find documentation about these rules until I found this issue and found out they were removed by a codelyzer new version

**Comment by t-ricci-molecle** [comment]
Nevermind, I figured out I should've gone to read the changelog instead of googleing the rule

https://github.com/mgechev/codelyzer/blob/master/CHANGELOG.md
