### ISSUE TITLE
import-destructuring-spacing should be configurable

### ISSUE THREAD

**Issue by lazarljubenovic** [mgechev/codelyzer#262]
Sometimes I feel like I'm the only person in the world who prefers _no_ spaces inside braces :smile: Not sure about naming though.

**Comment by mgechev** [comment]
Hey @lazarljubenovic I dropped this rule from version 3 because it's not Angular related style. Also, there's an existing [tslint implementation](https://palantir.github.io/tslint/rules/whitespace/).

**Comment by dereklin** [comment]
I have this rule
```
    "whitespace": [true, "check-branch", "check-decl", "check-operator",
        "check-separator", "check-typecast", "check-type",
        "check-typecast", "check-module"],
```
It's still not complaining about this:
```
import {BrowserAnimationsModule } from '@angular/platform-browser/animations';
```

**Comment by mgechev** [comment]
@dereklin would you report this to the [tslint project](https://github.com/palantir/tslint)?

**Comment by dereklin** [comment]
done https://github.com/palantir/tslint/issues/2401
