### ISSUE TITLE
no-input-rename should be configurabile

### ISSUE THREAD

**Issue by lazarljubenovic** [mgechev/codelyzer#263]
Sometimes you want to align an input name with a common, well-known HTML attribute, [such as `aria-`](https://github.com/angular/material2/blob/master/src/lib/icon/icon.ts#L88). There are two ways I see this can be configured to allow some (sensible) freedom.

# Allow a certain prefix

We could allow users to list prefixes (such as `"aria"`) in their config file which would allow all `@Input('aria-*')` renames. 

# Allow change to kebab-case

This might make even more sense, and my vote goes to this one (unless we decide to do both). We allow renaming the input when all it does is changing from camelCase to kebab-case:

```
@Input('aria-label') ariaLabel: string; // should be allowed with this config
```

 This seems like a pretty sensible solution to me and doesn't clash with [the rationale](https://angular.io/styleguide#!#05-13) behind the rule:

> Two names for the same property (one private, one public) is inherently confusing.

**Comment by mgechev** [comment]
Here's another related issue https://github.com/mgechev/codelyzer/issues/224.

>Allow change to kebab-case

Since the Angular compiler is case sensitive and the recommendation for naming attributes (from directive selectors) is to use camelCase literals, I'm not sure we should go this way.

Maybe, developers can provide key-value pairs of `propertyName: rename` as a whitelist. Ones the property name matches the `propertyName` value and the new name matches the `rename`, we can ignore the rule. This covers both cases from above with a bit more explicitness.

What do you think?

**Comment by lazarljubenovic** [comment]
Personally, I dislike too much lint configuration. If you think you have a valid reason to break the rule a lot, you should just disable it in my opinion.

Whitelisting renames is pretty much disabling a next line with a source code comment. Otherwise it would require changing the lint configuration a lot during development, which shouldn't be the case. Config should stay more or less the same and not change frequently.

**Comment by mgechev** [comment]
>Whitelisting renames is pretty much disabling a next line with a source code comment. Otherwise it would require changing the lint configuration a lot during development, which shouldn't be the case. Config should stay more or less the same and not change frequently.

Yep, I agree. Let's keep the rule as it is for now.

**Comment by MickL** [comment]
I think it should configurable, too. Best example is a component having the input `class` which sets class in html. But variable `class` is reserved.

```
@Input() src: string;
@Input('class') classes: string;
@Input() alt = '';
```

<img [src]="src" [class]="classes" [alt]="alt">
