### ISSUE TITLE
Prefix output warnings with codelyzer

### ISSUE THREAD

**Issue by kpaxton** [mgechev/codelyzer#265]
I just ran into an issue where I was getting the "Unused Styles" warnings in my tslint output. I was unaware that codelyzer had a rule for no-unused-css which was actually throwing the warning. Putting some indication that a codelyzer rule was triggered would help with understanding what is what and whether it's a standard Angular rule or Typescript.
Codelyzer: 2.0.0
Typescript: 2.2
TsLint: 4.5.0

**Comment by Splaktar** [comment]
I agree. I'm seeing some error output in my production build, but I can't be sure what is generating it. If codelyzer gave some indication that it had generated those warnings, it would have saved me a lot of time and confusion.

**Comment by mgechev** [comment]
I'll close this issue for now. Not sure how it aligns with the future vision of the project.
