### ISSUE TITLE
Public properties of extended class not found

### ISSUE THREAD

**Issue by tipag** [mgechev/codelyzer#269]
I get a warning like: "The property "x" that you're trying to access does not exist in the class declaration." for all properties in a base class.

**Comment by samuel1ee** [comment]
I've set "no-access-missing-member": false, rule to omit that error

**Comment by mgechev** [comment]
Also, fixed in https://github.com/mgechev/codelyzer/releases/tag/3.0.0-beta.0.

**Comment by tipag** [comment]
Please reopen!
Can confirm that it works in 3.0.0-beta.0 but not in 3.0.1.

**Comment by mscelina** [comment]
Probably it's the same as #238
