### ISSUE TITLE
Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

### ISSUE THREAD

**Issue by ctrl-brk** [mgechev/codelyzer#272]
v. 3.0.0-beta.4 gives this.
ng 4.0.0-rc.5
@angular/cli 1.0.0-rc.2

**Comment by mgechev** [comment]
codelyzer@3.0.0-beta.x does not have official integration with the CLI.

You can either configure it manually or use 2.x.x which is the stable release.
