### ISSUE TITLE
Prefix order problem with multiple prefixes for selector

### ISSUE THREAD

**Issue by sheridjs** [mgechev/codelyzer#275]
I noticed an issue with multiple selector prefixes. There seems to be an order dependency when one prefix contains another.

Example app component:
```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'abc-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'app works!';
}
```

tslint.json properties:
```json
    "directive-selector": [true, "attribute", ["ab", "abc"], "camelCase"],
    "component-selector": [true, "element", ["ab", "abc"], "kebab-case"],
```

With this setup, I get a TSLint error on the selector saying that it "should have one of the prefixes: ab,abc".

If I switch the selector to `ab-app`, there is no error. If I switch the prefix list to `["abc", "ab"]`, there is no error on either `ab-app` or `abc-app`.

I'm using an Angular 4 seed app with the following dependencies (plus more):
```json
    "@angular/core": "^4.0.0",
    "@angular/cli": "1.0.0",
    "codelyzer": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
```

**Comment by mgechev** [comment]
Thanks for the catch and for the detailed description. This rule is implemented [here](https://github.com/mgechev/codelyzer/blob/master/src/selectorNameBase.ts). I'll fix it and publish the release after ng-conf.
It'll be great if you have time to open a PR with a fix.

**Comment by sheridjs** [comment]
Thanks! I'll see if I can find some time soon.
