### ISSUE TITLE
templates-use-public rule does not fail when violated

### ISSUE THREAD

**Issue by basst314** [mgechev/codelyzer#278]
I've noticed a problem with the rule `"templates-use-public": true` in my `tslint.json` file, in that this rule will not trigger `ng lint` to report errors when it is violated.

**Steps to reproduce:**

1. create a new Angular-CLI Project with `ng new lint-test`
2. inside `app.component.ts` change accessor for property `title` to `private`. Title is accesses from html-template (via `{{title}}`).
3. run `ng lint` 

**Result:**
no errors are listed: `All files pass linting.`

**Expected behavior:**
Rule violation when running `ng lint`, saying that private accessor on the title property should be replaced with public.

**Versions:**
tslint@4.5.1
codelyzer@2.0.1
@angular/cli: 1.0.0
node: 6.7.0
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

Regards!

**Comment by mgechev** [comment]
Works for me in codelyzer@2.1.1 that just released. Let me know if it helps.

**Comment by basst314** [comment]
Hi @mgechev, the new release fixed this issue for me.
Thanks!
