### ISSUE TITLE
Support for tslint^5

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#281]

**Comment by jskrzypek** [comment]
Fwiw, I've started taking a stab at refactoring some of the rules to be compatible with tslint^5
It's currently on my branch here: https://github.com/jskrzypek/codelyzer/tree/feat/tslint-5

Let me know if I should make a PR now or wait till this is more mature

**Comment by mgechev** [comment]
Thanks for the help! PR sounds good. We should think how to release them. Probably introducing codelyzer@3.0.0 and pushing the features in the current 3.0.0 branches to 4.0.0 sounds reasonable.
Let me sync with the Angular CLI guys before we go any further.

**Comment by jskrzypek** [comment]
I'll massage the commit based on @ajafff's comments and make a PR later today

**Comment by jvbianchi** [comment]
[tslint v5.1.0](https://github.com/palantir/tslint/releases/tag/5.1.0) was released.

Will you support this version too?

**Comment by mgechev** [comment]
Since it's a minor release, in case we support 5.0.0 we'll automatically have support for 5.1.0.

Over the weekend I'll work on the migration to version 5 and open a PR in the CLI once done.

**Comment by mgechev** [comment]
The support for tslint@5 just landed in master. I'll publish a new release over the weekend.

**Comment by mgechev** [comment]
Closing the issue. 3.0.0 should be available tomorrow, followed by PR to the CLI.

**Comment by mgechev** [comment]
Codelyzer 3.0.0 is published https://www.npmjs.com/package/codelyzer.

**Comment by cexbrayat** [comment]
@mgechev Thank you for this! 

PR for the CLI pending for review https://github.com/angular/angular-cli/pull/6058
