### ISSUE TITLE
Module 'ts' has no exported member 'NoSubstitutionTemplateLiteral'.

### ISSUE THREAD

**Issue by MohammedSabbah** [mgechev/codelyzer#288]
Hi I was working on angular 2 project and everything was OK. Suddenly I have faced this problem when compiled the project

> ERROR in /home/sabbah/Desktop/Here-you-will-work/watania_live/Devlop/node_modules/codelyzer/util/astQuery.d.ts (6,101): Module 'ts' has no exported member 'NoSubstitutionTemplateLiteral'.
/home/sabbah/Desktop/Here-you-will-work/watania_live/Devlop/node_modules/codelyzer/util/astQuery.d.ts (13,67): Module 'ts' has no exported member 'NoSubstitutionTemplateLiteral'.

I tracked the error and found this

![screenshot from 2017-04-02 09-44-49](https://cloud.githubusercontent.com/assets/22482236/24607817/3d4f7c24-187c-11e7-804a-8c2362d3f053.png)

I also tracked NoSubstitutionTemplateLiteral and found it inside `enum SyntaxKind`
![screenshot from 2017-04-02 09-46-45](https://cloud.githubusercontent.com/assets/22482236/24607937/cfb4c5ec-187c-11e7-892d-5d25cebff628.png)

I solved the problem by just delete  `| ts.NoSubstitutionTemplateLiteral` from its place! is it save to do that?
what the preferred solution?

**Comment by mgechev** [comment]
What's your TypeScript version? Maybe there's mismatched peer dependency.

**Comment by MohammedSabbah** [comment]
@mgechev 
here are my package.json
`
  "dependencies": {
    "@angular/common": "^2.4.7",
    "@angular/compiler": "^2.4.7",
    "@angular/compiler-cli": "^2.4.7",
    "@angular/core": "^2.4.7",
    "@angular/forms": "^2.4.7",
    "@angular/http": "^2.4.7",
    "@angular/platform-browser": "^2.4.7",
    "@angular/platform-browser-dynamic": "^2.4.7",
    "@angular/router": "^3.4.7",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.20",
    "@types/node": "^6.0.63",
    "angular2-universal": "^2.1.0-rc.1",
    "body-parser": "^1.17.1",
    "codelyzer": "^2.0.0",
    "core-js": "^2.4.1",
    "express": "^4.15.2",
    "jquery": "^3.1.1",
    "ng2-bootstrap": "^1.3.3",
    "ng2-file-upload": "^1.1.4-2",
    "ng2-meta": "https://github.com/chocobozzz/ng2-meta#build",
    "ng2-page-transition": "^0.2.6",
    "ng2-pagination": "^2.0.1",
    "preboot": "^4.5.2",
    "rxjs": "^5.1.1",
    "ts-helpers": "^1.1.1",
    "web-animations-js": "^2.2.2",
    "zone.js": "^0.7.7"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3",
    "html-loader": "^0.4.3"
  }
}
`

**Comment by mgechev** [comment]
Doesn't seem problem related to codelyzer itself, most likely it's something in your build. The type declarations of this package should not be a part of it.
