### ISSUE TITLE
Support for `as` syntax in template

### ISSUE THREAD

**Issue by johnrbaur** [mgechev/codelyzer#289]
This line:
` <ng-container *ngIf="employee$ | async as emp">`

currently produces this error:
`The property "emp" that you're trying to access does not exist in the class declaration.`

The feature was added to Angular in this PR: https://github.com/angular/angular/pull/15025

**Comment by mgechev** [comment]
Thanks for reporting this out! I'll work on it in the next week or two.

**Comment by mgechev** [comment]
Did you check if you're getting any mismatched `peerDependencies`? For me the new syntax works.
