### ISSUE TITLE
Support for multiple selector type in directive-selector and component-selector rules

### ISSUE THREAD

**Issue by eugechielli** [mgechev/codelyzer#290]
The rules directive-selector and component-selector should allow the directives/components to accept both element and attribute type . With the rule definition, I'm forced to choose between an element and an attribute because If I don't respect it I get the following warning: "this.typeValidator is not function"

I would be great if I can set this type as null (so it would accept elements and attributes) or as a string/array with the both types accepted. For example:

"directive-selector": [true, null, "bm", "kebab-case"]
or
"directive-selector": [true, "attribute|element", "bm", "kebab-case"]
or
"directive-selector": [true, [ "attribute", "element" ], "bm", "kebab-case"]

Thanks for taking a look at it :)

**Comment by mgechev** [comment]
It makes sense to be more configurable. I'll try to introduce it as part of 3.0.0.

**Comment by karol-depka** [comment]
Hi. Thanks for taking care of this.
Is the doc updated?
http://codelyzer.com/rules/component-selector/

Currently, the schema there says:

> {
>       "enum": [
>         "element",
>         "attribute"
>       ]
>     },
> 

What is the syntax to allow both attribute selector and element-based selector?
Is it this, as in changelog?

> "component-selector": [true, ["element", "attribute"], "sg", "kebab-case"],

Can I submit a pull request to the docs?

Thanks!

**Comment by mgechev** [comment]
The schema has different format compared to the example. This seems corrext to me.

**Comment by karol-depka** [comment]
@mgechev Not sure what you mean.

Consider:

> 1. "element" or "attribute" forces components either to be elements or attributes.

*either*

-- http://codelyzer.com/rules/component-selector/

It does not mention the option of allowing both.

Another thing is how to use it to allow both: is it:

> "component-selector": [true, ["element", "attribute"], "sg", "kebab-case"],

?

I guess you understood that I confused/assumed that the schema should look the same as the example :). Which is not the case. I think the schema in the doc should have `"oneOf"` allowing enum or array.

**Comment by mgechev** [comment]
Yes, "either" might not be the most appropriate. I'll be happy to merge a more detailed description of the configuration options if you want to open a PR.

**Comment by karol-depka** [comment]
https://github.com/mgechev/codelyzer/compare/master...karol-depka:patch-1 - wdyt?

**Comment by mgechev** [comment]
LGTM! Open the PR so I can merge.

**Comment by AbakumovAlexandr** [comment]
@mgechev , can you provide an example of how the rule should look like to set up kebab style for elements and camel case for attributes, please?
