### ISSUE TITLE
Rule to check source file names

### ISSUE THREAD

**Issue by kylecordes** [mgechev/codelyzer#291]
Feature request...

A rule to check source file names, configuring in such a way that it can check that components, services, etc follow the file name patterns shown in the style guide.

For example, check that component `class MyComponent` resides in a file named `my.component.ts`.

**Comment by mgechev** [comment]
That's a good candidate and should be relatively straightforward to implement. Do you have suggestion for the rule's config?

**Comment by kylecordes** [comment]
How about something like this?

```
"directive-file-name": [true, "snake", "directive"],
```

true: means this is on.

snake: means to look for `the-words` not `theWords`.

directive: means to look for `the-words.directive.ts`.

Of course, similar settings for component, module.

This could handle projects that follow the style guide closely:

`some-name.component.ts`

and also projects that choose another variation:

`someName.cmp.ts`

**Comment by mgechev** [comment]
This way we need to have:

- `pipe-file-name`
- `component-file-name`
- `service-file-name`
- `module-file-name`
- `component-file-name`
- file name for a custom symbol?

We should come up with a more generic configuration which will not require declaration of 5 or more individual rules.

**Comment by vmasek** [comment]
In our team we also use the `name.model.ts` notation to mane files storing data structure and API Interfaces

**Comment by michaeljota** [comment]
I don't think this would be a easy configuration model, but still would be so useful to use this. 
Maybe we can use something like

```json
  "check-file-name": [
    true,
    {
      "type": "component" | "directive" | "pipe" | "service" | "module" | "model" | "*",
      "rule": "kebab-case" | "camelCase" | "PascalCase",
      "suffix": "*" // default: same as type
    }
  ],
```
Underneath this could have some default configuration that follows the standard guide style, as usual. 
```json
  "check-file-name": true,
```
But allow configuration per objects.
```json
  "check-file-name": [
    true,
    {
      "type": "component",
      "rule": "PascalCase",
      "suffix": "Cmp"
    }
  ],
```
> This would look for `AnyTitleCmp.ts` files and ensure there is an `AnyTitleCmp` class using `@Component` decorator (If that is something is the scope of this rule).
Or just set the `rule` or `casing` that would check that this rule would check
```
```json
  "check-file-name": [
    true,
    "rule": "PascalCase",
    // could also be
    "casing": "PascalCase",
  ],
```
> This would look for standards files and ensure they are using PascalCase, and there is a class using the corresponding decorator.

**Comment by HideDev** [comment]
Any news?

**Comment by bhaskerchari** [comment]
Hi @mgechev ,

Any news or update on this? When is this planned to be fixed & released ?

Thanks,
Bhasker

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by michaeljota** [comment]
Just want to say I hate the feature request process that Lodash has. But, I understand you would like to close some issues if they won't be implemented anytime soon. Thanks for the notice.

**Comment by mgechev** [comment]
Actually, that's a feature great for people who want to contribute to codelyzer! There's no AST traversal required.

**Comment by rafaelss95** [comment]
Just want to point that a similar rule has landed recently in tslint: [`file-name-casing`](https://github.com/palantir/tslint/pull/3978).

Also, there's some suggestions to improve this rule: https://github.com/palantir/tslint/issues/4050 (for exclusions) and https://github.com/palantir/tslint/issues/4071 (for pattern matching).
