### ISSUE TITLE
Enforce View & Container Components

### ISSUE THREAD

**Issue by davidbarratt** [mgechev/codelyzer#293]
To separate concerns, and make components more reusable, it is probably a good idea to not store state within a component, but rather store that in a service (multiple or a single service like @ngrx [store](https://github.com/ngrx/store)). However, there is nothing (that I'm aware of) to enforce not storing state within the component itself.

It would be really helpful if there was some sort of "no-component-state" rule that enforced:
* All properties must be `@Input()`, `@Output()`, or an injected service

It would be even better if this went a step further and separated "view" components from "container" components (in the filename?):

View:
* All properties must be `@Input()` or `@Output()`

Container:
* All properties must be `@Input()`, `@Output()`, or an injected service
* Must contain at least one child view component.

This would better separate views (that can be reused) from containers (that are connected to the store).

**Comment by mgechev** [comment]
Enforcing pure components sounds like a good idea to me. As discussed previously, it's impossible to support the entire TypeScript syntax and verify for lack of side-effects. Unfortunately, lack of component state doesn't guarantee independence from global state.

I like the rule suggestion, it'll be great if anyone is willing to contribute with initial version. The description by @davidbarratt sounds like a good starting point for an implementation.

**Comment by mgechev** [comment]
This seems out of the scope of the current implementation of codelyzer. Closing it for now.
