### ISSUE TITLE
Can't resolve template variable in mdAutocomplete

### ISSUE THREAD

**Issue by damsorian** [mgechev/codelyzer#297]
Hi! I have this error after update to 3.0.0 with the [mdAutocomplete component](https://material.angular.io/components/component/autocomplete)

`The property "auto" that you're trying to access does not exist in the class declaration.`

The code:
```html
<md-input-container>
  <input type="text" mdInput placeholder="Search..." [mdAutocomplete]="auto" />
  <md-autocomplete #auto="mdAutocomplete">
    <md-option *ngFor="let item of options" [value]="item">{{item.name}}</md-option>
  </md-autocomplete>
</md-input-container>
```

Any idea? thanks!

**Comment by mgechev** [comment]
3.0.0 does "flat analysis", i.e. it won't consider the entire project (won't collect the entire metadata for your project) which means that it will not be able to discover the `mdAutocomplete` template reference.

Take a look at this section for [more details](https://github.com/mgechev/codelyzer#advanced-configuration). Also, you may consider going back to 3.0.0-beta.x https://github.com/mgechev/codelyzer/issues/191#issuecomment-296697740.

**Comment by leocaseiro** [comment]
As a workaround, you can instantiate using the `@ViewChild` decorator on your `@Component`, like so:
```
@ViewChild('auto') auto: ElementRef;
```

**Comment by damsorian** [comment]
thanks @leocaseiro , it works!
