### ISSUE TITLE
ExportAs and no-access-missing-member

### ISSUE THREAD

**Issue by killzoner** [mgechev/codelyzer#298]
Hi,

I recently switched to codelyzer@3 and have encountered an issue that was not given in codelyzer@2. Actually i don't really know if it's real issue or on purpose, so the question here is rather open.

Here is the new "issue" in codelyzer3.
Given : 

```
@Directive({
    selector: '[docTest]',
    exportAs: 'docTest'
})
export class TestDirective {
    @Input('docTest')
    public value;
}
```
and 
```
<div docTest="myvalue" #localVar="docTest">
       {{localVar.value}}
</div>
```
produces a warning related to "no-access-missing-member" rule : 
```
The property "localVar" that you're trying to access does not exist in the class declaration.
```

To me, the property is only a template local ref so it shouldn't actually be throwing an error since we dont use it anywhere else than in the template, but i'm curious to know your thoughts about it.

Thanks

**Comment by mgechev** [comment]
Take a look at https://github.com/mgechev/codelyzer/issues/297

**Comment by killzoner** [comment]
Thanks, should have seen it in existing issues, sorry
