### ISSUE TITLE
Missing usePipeDecoratorRule from 3.0.0 build

### ISSUE THREAD

**Issue by sebek64** [mgechev/codelyzer#299]
probably because it is missing in index.ts.

**Comment by mgechev** [comment]
Yes, I don't see it exported but it shouldn't prevent you from using it since tslint will look at the files `node_modules/codelyzer/*Rule.js`.

What is the error that you get?

**Comment by sebek64** [comment]
The problem is that is is missing in this directory:

$ ls node_modules/codelyzer/*Rule.js
node_modules/codelyzer/componentClassSuffixRule.js
node_modules/codelyzer/componentSelectorRule.js
node_modules/codelyzer/directiveClassSuffixRule.js
node_modules/codelyzer/directiveSelectorRule.js
node_modules/codelyzer/importDestructuringSpacingRule.js
node_modules/codelyzer/invokeInjectableRule.js
node_modules/codelyzer/noAccessMissingMemberRule.js
node_modules/codelyzer/noAttributeParameterDecoratorRule.js
node_modules/codelyzer/noForwardRefRule.js
node_modules/codelyzer/noInputRenameRule.js
node_modules/codelyzer/noOutputRenameRule.js
node_modules/codelyzer/noUnusedCssRule.js
node_modules/codelyzer/pipeImpureRule.js
node_modules/codelyzer/pipeNamingRule.js
node_modules/codelyzer/templatesUsePublicRule.js
node_modules/codelyzer/templateToNgTemplateRule.js
node_modules/codelyzer/useHostPropertyDecoratorRule.js
node_modules/codelyzer/useInputPropertyDecoratorRule.js
node_modules/codelyzer/useLifeCycleInterfaceRule.js
node_modules/codelyzer/useOutputPropertyDecoratorRule.js
node_modules/codelyzer/usePipeTransformInterfaceRule.js

**Comment by mgechev** [comment]
Ah, I see. Let me publish 3.0.1.

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/codelyzer/commit/c5869e04cdfedb1c58fac9c0f6bef027a745badf. You can try `npm i codelyzer@3.0.1`.

**Comment by sebek64** [comment]
Yes, it works. Thank you for a quick fix.
