### ISSUE TITLE
component/directive selector rules doesn't work with es6 template string literals

### ISSUE THREAD

**Issue by Hotell** [mgechev/codelyzer#30]
I know it's strange to use string literals for selectors, but it's valid js :)

used rules:
```json
    "directive-selector-name": [true, "camelCase"],
    "component-selector-name": [true, "kebab-case"],
    "directive-selector-type": [true, "attribute"],
    "component-selector-type": [true, "element"],
```

![codelyzer-bug-es6-string-literals](https://cloud.githubusercontent.com/assets/1223799/15077929/0bf79f92-13b1-11e6-9f11-e07c53cd756e.gif)

**Comment by preslavsh** [comment]
Thank you for mentioning. We will take a look.

**Comment by Hotell** [comment]
I'm already working on fix ;) PR incoming

**Comment by mgechev** [comment]
Soon we'll add the evaluator from the metadata collector and such issues will be gone.
