### ISSUE TITLE
Enforce View Encapsulation

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#300]
Enforce `ViewEncapsulation.Emulated` or `ViewEncapsulation.Native`.

**This rule is good for first time contributors**.

I'd love to assist to the one willing to take the feature.

**Comment by GregOnNet** [comment]
I would be honored to take this task to get into this topic.
:-)

**Comment by mgechev** [comment]
I can't assign it to you since you're not yet a collaborator. I'll assign it to myself to show that there's someone working on it.

**Comment by GregOnNet** [comment]
Nice, thank you.

**Comment by GregOnNet** [comment]
Hi,

I did my first steps writing the TSLint rule. :-)
[see first try](https://github.com/GregOnNet/codelyzer/blob/view-encapsulation/src/useViewEncapsulationRule.ts)

I need some help concerning `NgWalker`.
I want to output the position of ViewEncapsulation`.None` if it has been set. (see [spec](https://github.com/GregOnNet/codelyzer/blob/view-encapsulation/test/useViewEncapsulationRule.spec.ts#L10))
Unfortunately I don't know how I can walk through the AST to point to that node.

@mgechev Could you assist me in that question, please?

Kind Regards
Gregor

**Comment by mgechev** [comment]
@GregOnNet good job! You can take a look at [this function](https://github.com/GregOnNet/codelyzer/blob/view-encapsulation/src/noUnusedCssRule.ts#L35-L50). `encapsulation.name.text` contains also the position of the node.

**Comment by GregOnNet** [comment]
I thank you very much this has helped me a lot.
