### ISSUE TITLE
Issue #189 (View-only variable - does not exist in the class declaration ) regression in codelyzer 3.0.1 

### ISSUE THREAD

**Issue by DaemonMM** [mgechev/codelyzer#303]
View-only variable - does not exist in the class declaration

Problem exist in codelyzer 3.0.1 ( vs tslint@^5.0.0), however, is fixed in codelyzer3.0.0-beta.1 (vs tslint@^4.0.0).

**Comment by mgechev** [comment]
https://github.com/mgechev/codelyzer/issues/297#issuecomment-296857427
