### ISSUE TITLE
Feature Request: Ability to lint AOT template warnings/errors

### ISSUE THREAD

**Issue by leocaseiro** [mgechev/codelyzer#305]
Currently, there's a bug ([#4252](https://github.com/angular/angular-cli/issues/4252)) on @angular-cli with `ng serve --aot`, so I'm not using aot for development.
However, I'm gettings lot's of errors and warnings on my `ng build --prod` which checks for AOT errors ([#5623](https://github.com/angular/angular-cli/issues/5623)) and quits the build.

At the moment, I have two git hooks: `ng lint --type-check` and `ng test`, however, the AOT errors are not showing on `ng lint` which triggers codelyzer.

It 'd be good if we could check for these errors (such as private properties that are used in the template and should be converted to public), with the lint(codelyzer).

In the cli, I was thinking of something like: `ng lint --aot` or even a new command, like: `ng lint-aot`.

> I posted this [issue on the cli repo](https://github.com/angular/angular-cli/issues/6116#issuecomment-299585264), and they suggested me to open an issue here.

**Comment by mgechev** [comment]
The compilation errors should be reported by the Angular compiler. All the linting errors (including style guide related warnings and other **non compile-time errors**), should be reported by tslint.

This issue seems out of the scope of codelyzer.
