### ISSUE TITLE
Type Hinting on suffix rules enforcing boolean values

### ISSUE THREAD

**Issue by jensbodal** [mgechev/codelyzer#310]
The generated `componentClassSuffixRule.d.ts` and `directiveClassSuffixRule.d.ts` files require a boolean value for validation, whereas either:

```
"component-class-suffix": true,
"directive-class-suffix": true,
```

or

```
"component-class-suffix": [true, "Component"],
"directive-class-suffix": [true, "Directive"],
```

appear to be supported

**Comment by mgechev** [comment]
Would you give me more information for what you mean here?

I'm not sure I understand the problem.

**Comment by jensbodal** [comment]
Sure thing.

When adding `component-class-suffix` or `directive-class-suffix` rules to your `tslint.json`, the type hinter tells you that a `boolean` is expected.  This is a fairly low hanging fruit issue, either rule works, but if using the `[true, "Component"]` syntax the type hinter will complain.  Here's an example from Visual Studio Code:

![image](https://user-images.githubusercontent.com/5542624/26961603-d5422972-4c94-11e7-8510-9a1f869f42b0.png)

**Comment by mgechev** [comment]
I see, thanks. Will work on this tomorrow.

**Comment by mgechev** [comment]
Opened PR here https://github.com/SchemaStore/schemastore/pull/306.
