### ISSUE TITLE
no-access-missing-member doesn't work with external HTML

### ISSUE THREAD

**Issue by fr0** [mgechev/codelyzer#311]
When using a separate `.html` file (via `templateUrl` in the `@Component` decorator) instead of an inline template, `no-access-missing-member` doesn't complain about using properties (e.g. in an `*ngIf` expression) that don't exist in the class definition.

To reproduce:
1. Use Angular CLI to create a new project, e.g.: `ng new test-playground`
2. Edit the generated `src/app/app.component.html` to add `*ngIf="foobar"` to the `h1` tag. (Do not add a `foobar` property to the class)
3. Run `ng lint`. The output will be `All files pass linting.` It seems to me that it should complain about the use of the `foobar` property that does not exist.

**Comment by mgechev** [comment]
Would you provide a sample component I can use to reproduce the issue?

**Comment by fr0** [comment]
Are you able to reproduce it using the instructions I just added to my original post?

**Comment by mgechev** [comment]
I will try, thanks.

**Comment by fr0** [comment]
For reference, the output of `ng --version`:

@angular/cli: 1.0.1
node: 6.10.2
os: darwin x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.3

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/codelyzer/issues/319
Will release in the next days.
