### ISSUE TITLE
Element is not known

### ISSUE THREAD

**Issue by broodjetom** [mgechev/codelyzer#316]
Hi, I don't know if I am doing something wrong, so maybe someone can help me with this.

In my main module I imported a module that has components in it. In my main component I use those components. But my VSCode TSLint says these components are not known.

```
/newmodule
    new.module.ts
    new.component.ts
-app.module.ts
-app.component.ts
```

Inside the app.component.ts I use the component from the new.component.ts. I have imported the newmodule in the appmodule.

The error i get is:

> 'new-component' is not a known element.
> 1. If 'new-component' is an Angular Component, then verify that is part of this Module.
> 2. If 'new-component' is a web-component then add 'CUSTOM_ELEMENT_SCHEMA' to the '@NgModule.schemas' of this component to surpress this message.

**Comment by mgechev** [comment]
That's not an error coming from codelyzer. Most likely you've forgot to include a component with selector `new-component` in the `NgModule` where you're using it.
