### ISSUE TITLE
rules name in documentation aren't consistent

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#325]
For instance, in the documentation, we display the name use-input-property-decorator-rule for a rule named use-input-property-decorator in tslint.json.

@mgechev ,  are you interested in renaming this rules ? (I can propose a PR)

**Comment by mgechev** [comment]
Yes. The documentation is being automatically generated with [this](https://github.com/mgechev/codelyzer/blob/master/build/buildDocs.ts) script, so you will have to change the source code.
