### ISSUE TITLE
Check for unused template-ref

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#329]
Source https://github.com/mgechev/codelyzer/issues/314

**Comment by wKoza** [comment]
@mgechev, Codelizer will be able to control this code without launching a false positive ?


```js
@Component({
  selector: 'app-my',
  template: `<p #wrapper>
  <ng-content></ng-content>
  </p>`
})
export class MyComponent implements  AfterContentInit {

  @ViewChild('wrapper') el: ElementRef;

  ngAfterContentInit() {
    console.log(' Init : ' + this.el.nativeElement.innerText)
  }

```

**Comment by mgechev** [comment]
No, template references won't work with the shallow parsing we perform. I suppose we can drop this from the roadmap.
