### ISSUE TITLE
[feat] Can we store the default prefix?

### ISSUE THREAD

**Issue by antonybudianto** [mgechev/codelyzer#33]
Hi @mgechev , thanks for a great Codelyzer!
I would like to integrate it with my [starter](https://github.com/antonybudianto/angular2-starter), so far no issue, but I found some rules value is repetitive, for example:
```json
"directive-selector-prefix": [true, "as"],
"component-selector-prefix": [true, "as"],
"pipe-naming": [true, "camelCase", "as"],
```

the repetitive part is `"as"` one, it'd be cool if I can store the prefix default in variable like
```json
"prefix-default": "as",
"directive-selector-prefix": [true],
"component-selector-prefix": [true],
"pipe-naming": [true, "camelCase"]
```
so I need to change only one part to reflect all of them, of course we can override the default one with usual way

It'd be great to have this feature
Thank you!

**Comment by mgechev** [comment]
At the moment we're not planning to implement such feature but we can consider it in future once we catch-up with more critical functionality.

Lets close the issue for now.
