### ISSUE TITLE
Ensure whitespaces after semicolon in structural dir

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#330]
This rule should extend `angular-whitespace`.

Source https://github.com/mgechev/codelyzer/issues/314

**Comment by wKoza** [comment]
I take it !

**Comment by mgechev** [comment]
@wKoza we can move this issue to the next milestone?

**Comment by wKoza** [comment]
Yes, no problem. I had just started.

**Comment by mgechev** [comment]
Ok, moving to the next milestone so we can focus on the remaining two issues.
