### ISSUE TITLE
Angular Whitespace "check-interpolation" fails

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#335]
...with `{{ foo}}` and `{{foo }}`.

**Comment by slimlime** [comment]
I had an issue with angular-whitespace or one of the fixers that seemed to identify angular moustache templates in my typescript files (no templates) and 

```ts
import {
  FormControl,
  FormGroup,
  FormBuilder,
  Validators,
  FormArray
} from "@angular/forms";

```
became 
```ts
imp; }}t{{ { {  }}{  }} {  }} {  }}
  }}ormArray,
  FormBuilder,
  FormGroup,
  Validators;
} from; '@angular/forms';
```

I had ridiculously run the tslint --fix autofix while working out how to use tslint and ended up replacing even more `}}` 🤣.

I'm still trying to track things down.
