### ISSUE TITLE
Bug since Angular 4.2.O 

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#337]
Since Angular 4.2.0, Codelizer 3.0.1 doesn't seem to work anymore.

**Comment by mgechev** [comment]
Yes, the fix is in master. Once 3.1.0 gets stable we can publish it.

**Comment by mgechev** [comment]
The fix itself https://github.com/mgechev/codelyzer/commit/b60829663383adcaa8b2570f56242ce34e1d94a1
