### ISSUE TITLE
TS2.4, NG 4.2.3 - Pipe operator should be surrounded by one space

### ISSUE THREAD

**Issue by intellix** [mgechev/codelyzer#343]
Was just testing the new stuff added in 3.1.0 and noticed that the "check-pipe" property never works for me. I've essentially copy/pasted from the tests so they should be supported:
```html
<div>{{ foo + bar | pipe }}</div>
```
Error:
```
Warning: Cannot read property 'expression' of undefined

ERROR: /Users/dominicwatson/Sites/stash/xcaf/xc-r2d2/src/app/payment/fees/fees.component.html[1, 18]: The pipe operator should be surrounded by one space on each side, i.e. " | ".
```

My versions:
```
tslint: 5.3.2
typescript: 2.4.0
codelyzer: 3.1.0
@angular/cli: 1.1.2
node: 8.0.0
os: darwin x64
@angular/animations: 4.2.3
@angular/cli: 1.1.2
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/compiler-cli: 4.2.3
@angular/core: 4.2.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/service-worker: 1.0.0-beta.5
@angular/language-service: 4.2.3
```

**Comment by mgechev** [comment]
Hm, there's a spec [for this](https://github.com/mgechev/codelyzer/blob/master/test/angularWhitespaceRule.spec.ts#L65-L75), which passes successfully.

**Comment by mgechev** [comment]
Got it. That's an external template, right?

**Comment by intellix** [comment]
Yep, it was in an external template :) thanks so much

**Comment by intellix** [comment]
Still having issues with this one. I'm running 3.1.1 and I'm still getting:
```
Warning: Cannot read property 'expression' of undefined
```

On stuff like:
```
<footer class="game-footer" [ngSwitch]="isUserLoggedIn | async"></footer>
```

Also, it seems the reported line/columns are wrong for those. I'm getting much less violations though than I did on 3.1.0

**Comment by wKoza** [comment]
check-pipe seems to work only in interpolation.

looks like #346
