### ISSUE TITLE
check-pipe breaks with ngFor

### ISSUE THREAD

**Issue by cexbrayat** [mgechev/codelyzer#346]
It looks like the new `check-pipe` rule breaks with ngFor (as of 3.1.1):

    <div *ngFor="let user of users | slice:0:4">

Throws:

    The pipe operator should be surrounded by one space on each side, i.e. " | "

See #347 for a unit test reproducing the issue.

**Comment by intellix** [comment]
and an ngSwitch at least. Not sure which others are missing

**Comment by mgechev** [comment]
Thanks for reporting the issue. I will take a look during the weekend on AngularUP.

**Comment by rokerkony** [comment]
Other cases which fail on the `check-pipe` rule:

1.  `{{ (foo) | pipe }}` our code example: `{{ (totalPrice || price.total) | eur }}`
2. `<div *ngIf="items$ | async as items; else loading;"></div>`

**Comment by rokerkony** [comment]
@mgechev this issue is closed but the use case n.2 was not fixed... can you take a look on it?

**Comment by mgechev** [comment]
There's another issue related to `"check-pipe"` https://github.com/mgechev/codelyzer/issues/365. Looks the same as the one reported by you.

**Comment by rokerkony** [comment]
ok, thx :)

**Comment by cexbrayat** [comment]
@mgechev I tried 3.1.2 but it still fail for `ngFor` in a simple use case, with an external template.

See #368 for a unit test reproducing the issue.

**Comment by mgechev** [comment]
See https://github.com/mgechev/codelyzer/issues/365

**Comment by cexbrayat** [comment]
@mgechev Ha sorry, I thought #365 was unrelated to this one (the title was not really explicit :) ).

**Comment by mgechev** [comment]
No worries
