### ISSUE TITLE
Possibility of disable some rules in specific file/line

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#348]
It would be great to have some way to disable rule(s) in specific file or line, like this does in `tslint`:

```
// tslint:disable-next-line:rule-name
some_content
```

A simple use case:

Let's suppose that I want to disallow the use of `ViewEncapsulation.None` in all my components, except in one component.

**Comment by wKoza** [comment]
You can use this : 
```js
// tslint:disable use-view-encapsulation
  encapsulation : ViewEncapsulation.None
  // tslint:enable use-view-encapsulation
```

**Comment by rafaelss95** [comment]
Oh, thanks @wKoza

**Comment by mlevinem6** [comment]
Just an update for anyone who happens upon this page as I did, it currently would be done like this:
```
/* tslint:disable:use-component-view-encapsulation */
```
