### ISSUE TITLE
"no-access-missing-member" rule doesn't see properties from base classes.

### ISSUE THREAD

**Issue by supamax** [mgechev/codelyzer#349]
Angular 4.2.4.
Codelyzer 3.1.1.

Example:
ERROR: (no-access-missing-member) ********: The property "model" that you're trying to access does not exist in the class declaration.

But model property exists in the base class of Component class.
Have to disable it now.

On 3.0.1 there were no errors.

**Comment by wKoza** [comment]
Hi,
Can you give us an example of code with a Component and a template ?

**Comment by mgechev** [comment]
@supamax, please use the search for details.

**Comment by Almar** [comment]
I'm experiencing the same problem. I searched for other issues and I think #285 is relevant but I that doesn't bring me closer to a solution.
@mgechev, could you please explain a little more?
