### ISSUE TITLE
kebab-case shouldn't allow non-hyphened string

### ISSUE THREAD

**Issue by laco0416** [mgechev/codelyzer#35]
As [Style Guide](https://angular.io/styleguide#!#components) says, a component name should be named in kebab-case. And it should follow Custom Elements spec.

> Style 05-02
> Do use kebab-case for naming the element selectors of our components.
> Why? Keeps the element names consistent with the specification for [Custom Elements](https://www.w3.org/TR/custom-elements/).

Custom Elements spec says the following:

> The custom element type identifies a custom element interface and is a sequence of characters that must match the NCName production [XML-NAMES], must contain a U+002D HYPHEN-MINUS character, and must not contain any uppercase ASCII letters [HTML]. The custom element type must not be one of the following values:

But currently codelyzer allows a name doesn't contain hyphen as kebab-case.

- `selector: "foobar"` : passed
- `selector: "foo-bar"` : passed
- `selector: "fooBar"` : invalid

**Expected**

`selector: "foobar"` should be an error in kebab-case rule.

**Comment by Igonato** [comment]
Wait. What if the name is just one word? Like "person" or "toolbar"?

**Comment by Igonato** [comment]
Nevermind. There is #68 with more info
