### ISSUE TITLE
VSCode not showing errors

### ISSUE THREAD

**Issue by jordidiaz** [mgechev/codelyzer#351]
Hi,

I'm trying to configure Codelyzer's VSCode error highlight. I have an angular-cli setup:

```
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
    "arrow-return-shorthand": true,
    "callable-types": true,
    "class-name": true,
    "comment-format": [
...
```

settings.json looks like:

```
"tslint.rulesDirectory": "Client/node_modules/codelyzer",
"typescript.tsdk": "Client/node_modules/typescript/lib"
```
 I have the tslint extension for VSCode installed, and those are my package.json's related dependencies:

```
"codelyzer": "3.0.1"
"tslint": "5.4.3"
"typescript": "2.3.4"
```

I see the errors using `ng lint` but no error highlight is shown in VSCode.

Thank you very much.

**Comment by mgechev** [comment]
Do you see any taking errors at all?

**Comment by jordidiaz** [comment]
Hi Minko,

I'm working with another computer now and the error hightlight is working for the rest of projetcs. It seems that the settings.json configuration is not being able to reach the tsserver. I'm going to check my project differences (folder structure seems to be the problem) with others working and I'll share the results.

**Comment by jordidiaz** [comment]
Problem solved!

Being the app's root folder where .vscode settings folder is located I had my angular-cli app bootstrapped in the 'Client' folder. I just moved all the app to the 'root folder', delete the 'Client' path from the settings and now works like a charm. Is it any known restriction @mgechev?

**Comment by mgechev** [comment]
No, it isn't. Thanks for posting the solution you found!
