### ISSUE TITLE
bug(no-unused-css-rule)

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#352]
I have the following config in `tslint.json`:

```
"angular-whitespace": [true, "check-interpolation", "check-pipe"],
"banana-in-box": true,
"templates-no-negated-async": true,
"directive-selector": [true, ["attribute"], ["app"], "camelCase"],
"component-selector": [true, ["element"], ["app"], "kebab-case"],
"use-input-property-decorator": true,
"use-output-property-decorator": true,
"use-host-property-decorator": true,
"use-pipe-decorator": true,
"no-attribute-parameter-decorator": true,
"no-input-rename": true,
"no-output-rename": true,
"no-forward-ref": true,
"no-unused-css-rule": true,
"use-view-encapsulation": true,
"use-life-cycle-interface": true,
"use-pipe-transform-interface": true,
"pipe-naming": [true, "camelCase"],
"pipe-impure": true,
"component-class-suffix": true,
"directive-class-suffix": true,
"import-destructuring-spacing": true,
"templates-use-public": true,
"no-access-missing-member": true,
"invoke-injectable": true,
"template-to-ng-template": true
```  

When I ran `npm run lint` I get the following warning:

> Could not find implementations for the following rules specified in the configuration:
>     no-unused-css-rule
> Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
> If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
> Warning: Cannot read property 'expression' of undefined

Versions:

Codelyzer: 3.1.1
Tslint: 5.4.3

**Comment by mgechev** [comment]
You should remove the rule suffix from the rule name.

**Comment by rafaelss95** [comment]
@mgechev  Thanks!

I just pick this name from [**docs**](http://codelyzer.com/rules/no-unused-css-rule)

**Comment by wKoza** [comment]
Hi @mgechev, can you reopen this issue ? Indeed, the rule's name is wrong.

**Comment by Martin-Wegner** [comment]
@mgechev http://codelyzer.com/rules/ links to http://codelyzer.com/rules/no-unused-css which not exists. http://codelyzer.com/rules/no-unused-css-rule exists...

**Comment by mgechev** [comment]
@Martin-Wegner the update is in master, haven't updated the docs yet https://github.com/mgechev/codelyzer/pull/355.
