### ISSUE TITLE
import-destructing-spacing or import-destructuring-spacing?

### ISSUE THREAD

**Issue by Martin-Wegner** [mgechev/codelyzer#358]
The docs say `import-destructing-spacing` but the real implementation is `import-destructuring-spacing`.

I think you should rename `docs/rules/import-destructing-spacing/index.html` to `docs/rules/import-destructuring-spacing/index.html` and replace all `import-destructing-spacing` with `import-destructuring-spacing` in `docs/rules/import-destructuring-spacing/index.html`, `src/importDestructuringSpacingRule.ts`, `docs/dist/src/importDestructuringSpacingRule.js` and `docs/_data/rules.json`.

**Comment by mgechev** [comment]
Hey @Martin-Wegner, we generate the `docs` directory. Would you open a PR updating the rule name in the `importDestructuringSpacingRule.ts` file?

**Comment by Martin-Wegner** [comment]
@mgechev OK: https://github.com/mgechev/codelyzer/pull/360
