### ISSUE TITLE
check-pipe should ignore i18n meaning and description | separator

### ISSUE THREAD

**Issue by Martin-Wegner** [mgechev/codelyzer#359]
`"angular-whitespace": [true, "check-pipe"]` complains about the i18n meaning and description | separator (see https://angular.io/guide/i18n#help-the-translator-with-a-description-and-meaning). For example: `<h1 i18n="site header|An introduction header for this sample">Hello i18n!</h1>`

**Comment by wKoza** [comment]
thank for your issue ! We will work on it !
