### ISSUE TITLE
no-access-missing-member doesn't look in a Component's base class(es)

### ISSUE THREAD

**Issue by fr0** [mgechev/codelyzer#361]
Example:

```
export class ComponentBase {
  foo = 0;
}

@Component({
  selector: 'app-actual',
  template: `<div>{{foo}}</div>` // or, in a .html file
});
export class ActualComponent extends ComponentBase {
}
```

`ng run lint` will complain about the usage of `foo`, noticing that it is not in `ActualComponent`, and will not think to look in `ComponentBase`.

This is with Codelyzer v3.1.1, and angular/cli v1.3.0-beta.0.

**Comment by mgechev** [comment]
Take a look at the existing issues. This rule will be removed.
