### ISSUE TITLE
Compiler should throw an error if I use @HostListener in a service

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#363]
> I'm submitting a ...
> 
> 
> [ ] Regression (behavior that used to work and stopped working in a new release)
> [ ] Bug report 
> [ X ] Feature request
> [ ] Documentation issue or request
> [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
> Current behavior
> 
> I'm allowed to put @HostListener in a service, even if it doesn't work
> 
> Expected behavior
> 
> The compiler should fail (or at least emit a warning?) telling me that the use of @HostListener within a service (or any other place that doesn't have a host) won't work.
> 
> Minimal reproduction of the problem with instructions
> 
> What is the motivation / use case for changing the behavior?
> 
> Just a quality-of-life improvement

By @adamdport 
Source https://github.com/angular/angular/issues/17847

**Comment by wKoza** [comment]
At first, we can focus on decorators like @HostListener, @HostBinding, @Input, @Output, ... But it would be interesting to work on the life cycle in another rule.
