### ISSUE TITLE
check-interpolation checks non-interpolation expressions

### ISSUE THREAD

**Issue by SteveVanOpstal** [mgechev/codelyzer#367]
``` HTML
<sg-example *ngFor="let test of tests" [test]="test"></sg-example>
```
> Missing whitespace in interpolation; expecting {{ expr }}

The Angular guidelines seem to allow non-interpolations in a input/attribute:
https://angular.io/guide/styleguide#style-05-17
Assuming from the `[hero]="hero"`, although they do not specifically mention it.

The expression should not raise an error for whitespaces issues.

**Comment by mgechev** [comment]
`[hero]="hero"` this is not an interpolation syntax. The `angular-whitespace` rule will not run against the snippet above.

Would you give more details about the issue?

**Comment by SteveVanOpstal** [comment]
For some reason the error logging indicated the wrong line, made me assume it was referring to the attribute.
