### ISSUE TITLE
no-access-missing-member throw an error with template reference variable.

### ISSUE THREAD

**Issue by Orodan** [mgechev/codelyzer#369]
Hi,

When using template reference variable, codelyzer throw an error related to "no-access-missing-member". Here is an example : 

```
<ul class="nav nav-tabs">
   <li [class.error]="!mainMetadata.valid>Main metadata</li>
</ul>

<div class="tab" #mainMetadata="ngModelGroup">
  ...
</div>
```

And the report from tslint : The property "mainMetadata" that you're trying to access does not exist in the class declaration.

I know there is already some issues related to this problem like [189](https://github.com/mgechev/codelyzer/issues/189) but I still got the error.

tslint: 5.4.3
codelyzer: 3.1.2

**Comment by wKoza** [comment]
Hi, take a look at #213

**Comment by Orodan** [comment]
Well I don't think you should close it for now : there is nothing in the readme advanced configuration example that helps me, and the other solution is to disable the rules.

**Comment by wKoza** [comment]
This rule will be removed in a next release. You should use the language service Angular for catch this. And if you want failures of the build when there's a missing property , you can just run a build with aot and it will throw errors.

**Comment by Orodan** [comment]
Thanks for the idea of Angular service language ! I just find it a bit disappointing that the "no-access-missing-member" rule is not able to detect correctly template reference variable. 

One last thing : may I ask why this rule will be removed in the next release ? It's still usefull in most cases.

**Comment by wKoza** [comment]
In **a** next release (Probably  with 4.0.0). The language service Angular is THE good candidat for this. Codelyzer aims to provide linting for style errors which can be found by providing a "shallow analysis". "No-access-missing-member" requires a deep analysis sometime.
