### ISSUE TITLE
Add a rule which verifies the use of the life cycle methods according to the type of class (Component, Directive, Service, ...)

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#371]
Related to #363

**Comment by mgechev** [comment]
@wKoza would you want to keep it in the next release or schedule it for future releases?

**Comment by wKoza** [comment]
In the next release ! Tonight, It's holiday time ;)

**Comment by mgechev** [comment]
Sounds good! I am planning to focus on making existing rules stable (check-pipe, especially) and working on i18n.
