### ISSUE TITLE
(no-access-missing-member) failing on update from 3.0.1 to 3.1.x

### ISSUE THREAD

**Issue by DouglasWebster** [mgechev/codelyzer#372]
I have a section of HTML (from ngx-bootstrap demo) that is now failing the no-access-missing-member rule.  The section of code is 
```
<h4>Static modal</h4>
    <button type="button" class="btn btn-primary" (click)="staticModal.show()">Static modal</button>
    <div class="modal fade" bsModal #staticModal="bs-modal" [config]="{backdrop: 'static'}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
      aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title pull-left">Static modal</h4>
            <button type="button" class="close pull-right" aria-label="Close" (click)="staticModal.hide()">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            This is static modal, backdrop click will not close it. Click <b>&times;</b> to close modal.
          </div>
        </div>
      </div>
```
The offending bit of code is `(click)="staticModal.show()"` which is giving the following error
`ERROR: (no-access-missing-member) /.../modal-sample.component.html[14, 59]: The method "staticModal" that you're trying to access does not exist in the class declaration.`

The `staticModal` is not in the class declaration as it is referencing the `#staticModal`  in the next line of code which is a valid class that does have a show() member. 

As the offending code is part of a project that builds and runs without problem should not the line of code be accepted?  If so is there a workaround that would enable me to inhibit the rule for the lines in question  in the meantime.  (I don't want to inhibit globally and trying  `<!-- tslint:disable-next-line -->` doesn't seem to work!

**Comment by mgechev** [comment]
Take a look at the issue tracker and in the readme for existing issues related to template references.
