### ISSUE TITLE
feat: Add a rule to ensure that the decorator has parentheses after it

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#373]
Actually if you forget to put the parentheses after `@Input`, for example, it doesn't give any hint/warning, just the generic error:

> Can't bind to 'myInput' since it isn't a known property of 'my-component'

Also, according to [Angular's DI docs:](https://angular.io/guide/dependency-injection#why-injectable)

> Always write @Injectable(), not just @Injectable. The application will fail mysteriously if you forget the parentheses.

.. it also happens to `@Injectable`.

My suggestion is to provide a simple rule that ensure that the decorator has parentheses after it.

@mgechev What do you think?

**Comment by mgechev** [comment]
This will be handled by ngc and respectively the language service. There's already existing rule which verifies that `@Injectable` is invoked, however, this rule will be dropped in future releases.

**Comment by rafaelss95** [comment]
Well, as I mentioned in the case of `@Input` it'll **throw** that generic error, and devs may get stuck with this simple thing. The same happens for `@Output`.

**Comment by mgechev** [comment]
This seems like opportunity for improvement in ngc. Let me sync with the Angular team and come back to you.

**Comment by mgechev** [comment]
@rafaelss95 tsc itself reports the error in case you don't pass argument to the `@Inject` property decorator.
