### ISSUE TITLE
Add new `max-import-line-length` rule

### ISSUE THREAD

**Issue by SchnWalter** [mgechev/codelyzer#375]
It would be nice to have a larger line length limit for import rules. Depending on the project, the 140 characters limit sometimes isn't enough.

Here's an example:
```
import { OrganizationErpConnectionSyncStatusComponent } from 'app/MYORG-modules/admin/pages/organizations/components/organization-erp-connection-sync-status/organization-erp-connection-sync-status.component';
```

Thank you!

**Comment by mgechev** [comment]
That's not an Angular specific rule. You can try opening a feature request in the tslint repository.
