### ISSUE TITLE
[feat] warn when lazy loaded module is imported statically

### ISSUE THREAD

**Issue by reppners** [mgechev/codelyzer#376]
It would be nice if there is a warning when a module that is "referenced" in a route by `loadChildren` is imported statically somewhere. As soon as a module is lazy loaded AND imported statically it is almost certainly an error.

Is this possible with the metadata at hand / ngast? I'm happy to work on this but would need directions to get started.

**Comment by mgechev** [comment]
Yes, that's a rule which I've been considering for a while. It's definitely a good idea.

I'll add it to the release 4.x.x. `ngast` is a good candidate but it'll require further design. I'll spend time in August to write a design doc and release it publicly.

**Comment by mgechev** [comment]
Let's close this issue for now. Codelyzer is performing local analysis (i.e. per file).
