### ISSUE TITLE
i18n best practices

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#377]
Consider to add the following i18n best practice:

> ## Set a custom id to improve search and maintenance
> 
> The angular i18n extractor tool generates a file with a translation unit entry for each i18n attribute in a template. By default, it assigns each translation unit a unique id such as this one:
> 
>  content_copy
> <trans-unit id="ba0cc104d3d69bf669f97b8d96a4c5d8d9559aa3" datatype="html">
> This id is obscure and difficult for humans to read or remember.
> 
> Worse, when you change the translatable text, perhaps to fix a typo, the extractor tool generates a new id for that translation. You will lose the translation unless you update it with the new id. That complicates maintenance.

- [x] - Look for elements without custom ID.
- [x] - Look for elements with text content but no i18n attribute.

https://angular.io/guide/i18n#set-a-custom-id-to-improve-search-and-maintenance

**Comment by abierbaum** [comment]
Would it be possible to also add a rule that looks for elements in component templates that have text content but no i18n attribute?

One issue we are having on our team is simply enforcing that people mark all the exposed strings for extraction and translation.

**Comment by mgechev** [comment]
This should be relatively straightforward. I will add it as part of this issue.

**Comment by abierbaum** [comment]
@mgechev Awesome.  Thanks!!!

**Comment by mgechev** [comment]
@abierbaum both rules are implemented. Should be ready to use in codelyzer@3.2.0.

**Comment by panuruj** [comment]
In general, I would not recommend overriding the auto-generated ID. In a project that have thousands of strings to be translated, it is error prone to rely on the developer to ensure that the ID is unique across the entire application.

**Comment by abierbaum** [comment]
@mgechev Thanks for adding this!!!
