### ISSUE TITLE
[feat] add a warning when not using trackBy with ngFor

### ISSUE THREAD

**Issue by mattlewis92** [mgechev/codelyzer#378]
Even though its considered best practise, I always forget to add a trackBy when using ngFor. It would be awesome to have a rule to enforce this in templates. Since invalid usage of trackBy is currently swallowed silently by angular, as a stretch it would be cool if the rule validates the trackBy expression as well. If you're in favour of this I would love to take a go at a PR for this feature. Thanks! 😄

**Comment by mgechev** [comment]
Sounds like a good suggestion. There's issue related to the errors reporting in ngFor. Once this is fixed it'll be relatively easy to implement.

**Comment by maxime1992** [comment]
I came here to post that but @mattlewis92 did it 2 days ago :smile:  !
Indeed, I think it would be a really nice feature! :beers:

**Comment by mgechev** [comment]
Will move it to the next release in order to not bloat this one.

**Comment by markwhitfeld** [comment]
This would be an amazing feature!
... and it even looks like @maxime1992 offered some beer to get it fixed 😉

**Comment by wKoza** [comment]
I keep track of that ;)
