### ISSUE TITLE
some rules report false positives

### ISSUE THREAD

**Issue by rolandjitsu** [mgechev/codelyzer#379]
I just discovered some weird cases where `angular-whitespace` complains about:
- `<div fxLayout="column">` (the `l` - as in the letter `L` - must be the confusing part)
- `<md-icon *ngIf="isOnline | async; else offline">cloud_off</md-icon>`
- `<md-toolbar color="primary">` - might be the same case as the first one
- `<rj-image-filters (queryChange)="updateFilters($event)"></rj-image-filters>` - could be the same case with the letter `L`
- `<!-- Setttings -->` - might be the `!` sign there, nonetheless, comments should be ignored
- `<md-select [(ngModel)]="timeRangeKey">` - could be the `L` again
- `*ngIf="query.isUpdating | async as isUpdating"` - there's obviously space there, so not sure what the problem is

And `banana-in-a-box`:
- `<a md-list-item (click)="navigate(['/resources'])">` - confuses what's inside the quotes I guess

Finally `no-access-missing-member `:
- complains about a prop not existing on the class, but it's actually a local var
```html
<rj-paginated-resources *ngIf="query"
							#pagination="rjPagination"
							[type]="type"
							[query]="query | async">
	<div fxLayout="row"
		 fxLayoutWrap
		 class="images"
		 padding>
		<ng-container *ngFor="let image of pagination.items | async; trackBy: trackByImage">
			<div class="image">
				<rj-image-card [image]="image"></rj-image-card>
			</div>
		</ng-container>
	</div>
</rj-paginated-resources>
```

**Comment by wKoza** [comment]
Thanks you for your issue report. For the last point, there are many issues in the tracker related to template references. For the others, we will investigate.

**Comment by wKoza** [comment]
Can you give me an example of log for this item : `<div fxLayout="column">` ?

Concerning the check-pipe, can you remove it form your configuration for this moment because there is an issue opened (issue #365 ).

**Comment by rolandjitsu** [comment]
Definitely:
```text
/users/rolandjitsu/projects/test/src/app/test.component.html
ERROR: 4:4    angular-whitespace        The pipe operator should be surrounded by one space on each side, i.e. " | ".
```

**Comment by wKoza** [comment]
And if you remove the check-pipe in your lint, what's happening ?

**Comment by rolandjitsu** [comment]
If I remove that, I get no errors 😄

**Comment by wKoza** [comment]
Ok nice. You can monitor this issue for resolution. Otherwise, there is indeed a problem with the rule "banana-in-a-box". I will take a look at this weekend.

**Comment by rafaelss95** [comment]
Maybe it worth to create a new issue for this, but since the title is a bit generic, let's report it here:

Having:

```
<md-input-container
  <input type="text"
         placeholder="Some placeholder"
         mdInput
         [mdAutocomplete]="auto"
</md-input-container>

<md-autocomplete #auto="mdAutocomplete">
  <md-option [value]="value" *ngFor="let value of values">
    {{ value }}
  </md-option>
</md-autocomplete>
```

Results in: the property "auto" that you're trying to access does not exist in the class declaration.

**Comment by mgechev** [comment]
That's the expected behavior from the rule [`template-use-public`](https://github.com/mgechev/codelyzer/blob/master/src/templatesUsePublicRule.ts).

**Comment by mgechev** [comment]
Lets reopen the issue since there are problems in other rules (`angular-whitespace` has some flaws).

**Comment by mgechev** [comment]
The problem in all rules which involve `EmbeddedTemplate` is that the syntax is being desugared from:

```
<li *ngFor="let foo of bar"></li>
```

to:

```
<li ngFor let-foo [ngForOf]="bar"></li>
```

which breaks our mapping. Here's [the solution by the language service](https://github.com/angular/angular/blob/master/packages/language-service/src/completions.ts#L300-L375). It's not straightforward. Most likely I'll reuse it, however, we risk to have frequent breaking changes given the private APIs being used there.

**Comment by wKoza** [comment]
mmhm, i hope this will be okay ...

**Comment by mgechev** [comment]
I'm afraid we'll need to [keep this](https://github.com/mgechev/codelyzer/blob/master/src/angular/templates/basicTemplateAstVisitor.ts#L12-L78). It can be implemented with a strategy, doesn't have to be in a long function but the logic will remain.

**Comment by wKoza** [comment]
Hi @mgechev, have you progress in this issue ?

**Comment by mgechev** [comment]
Haven't done anything here yet. The way to go is custom expression parser for *-prefixed attributes.

**Comment by wKoza** [comment]
ok, I'll look at this If I have time.

**Comment by rolandjitsu** [comment]
I'm still seeing some problems with the `check-pipe` rule for:
```html
<p *ngIf="(items | async)?.length as length" class="mat-caption">
```

```html
<span *ngIf="product.propagationTolerance" class="label">&plusmn; {{ product.propagationTolerance | number }}</span>
```

For the latter, removing `&plusmn;` seems to fix it.

**Comment by mgechev** [comment]
@rolandjitsu thanks for pointing this out! I'll move it to a separate issue. Hopefully we'll be able to soon clean the glitches and open a PR to Angular CLI with the new features.
