### ISSUE TITLE
no-access-missing-member rule ignores template scope variables (let-item syntax)

### ISSUE THREAD

**Issue by alienlike** [mgechev/codelyzer#380]
Codelyzer flags the following code with the error `The property "phone" that you're trying to access does not exist in the class declaration.`

```
<ng-template ngFor let-phone [ngForOf]="phoneNumbers">
    {{phone.formattedNumber}}
    <br />
</ng-template>
```

**Comment by mgechev** [comment]
Take a look at https://github.com/mgechev/codelyzer/issues/264
