### ISSUE TITLE
component-selector: selector: 'a.ch-test-list-item'

### ISSUE THREAD

**Issue by cherzog** [mgechev/codelyzer#382]
The following code give me an error, but - in my opionion - should be ok:
the selector of the component should be named kebab-case and include dash

```
import { Component, Input } from '@angular/core';

import { Test } from '../shared/test';

@Component({
  selector: 'a.ch-test-list-item',
  templateUrl: './test-list-item.component.html'
})
export class TestListItemComponent {

}

```

**Comment by wKoza** [comment]
In your case, there is an another problem because, the selector should begin by a prefix followed by a dash. 
Concerning the dot, the element must be consistent with the specification for Custom Elements which seems to allow the dot. Indeed, it may be something to do .

cc @mgechev ?

**Comment by cherzog** [comment]
To make it clear, this is the calling template:

`<a class="ch-test-list-item" *ngFor="let t of tests" [test]="t" (click)="showTest(t)"></a>`

The prefix is "ch"

**Comment by mgechev** [comment]
Not sure if using class selector for components could be considered a best practice.

According to the style guide we worked on, components should be used with elements selectors.

@cherzog if this rule doesn't align with your internal style guidelines, you can disable it locally with `/* tslint:disable:rule-name */`.
