### ISSUE TITLE
Prefixes are not necessarily at the beginning of the string

### ISSUE THREAD

**Issue by Foxandxss** [mgechev/codelyzer#39]
We could have something like:

```
@Directive({
  selector: 'template[myFoo]`
})
```

That won't work even if it has the correct prefix.

![](http://puu.sh/oPLli/0049ea3dd8.png)

As a bonus, it doesn't think it is an attribute directive.

**Comment by mgechev** [comment]
This is duplication of https://github.com/mgechev/codelyzer/issues/15. Currently we support only basic selectors but this is in the roadmap for sure.

**Comment by Foxandxss** [comment]
Welp, I swear I looked.

**Comment by mgechev** [comment]
Haha, no worries!
