### ISSUE TITLE
[feat] Lint passing function ref to output handlers

### ISSUE THREAD

**Issue by lazarljubenovic** [mgechev/codelyzer#390]
As somebody who switches a lot between Angular, React and Vue, I often make mistakes in templates because of their different syntax. While most of mistakes simply produce syntax errors, there's one which keeps driving me mad:

```
<button (click)="onClick">
```

In React and Vue, you pass in a reference to the function which will be called when `click` event occurs. In Angular, you _have_ to write an expression. You almost definitely wanted:

```
<button (click)="onClick()">
```

Lintes already have the "Expression statement is not assignment or call" rule warning you for having things like `this.onClick` in code, without assigning the function ref or calling it, so I thought this would be great addition. 

In Angular, template expressions/statements is not _exactly_ the same as JavaScript expressions/statements. Docs are very clear about the definition of those, however.
- [Template expressions in Angular](https://angular.io/guide/template-syntax#template-expressions)
- [Template statements](https://angular.io/guide/template-syntax#template-statements)

**Comment by mgechev** [comment]
This looks useful.

It could be generalized to: "Verify that event handlers produce side effect".

In case the expression is something like: `(click)="foo(bar)"` and `foo` is a pure function, the handler is pointless. Not sure how trivial this will be.

**Comment by wKoza** [comment]
The language service already proposes this with this error "Unexpected callable expression. Expected a method call" in our templates.  This is not what you are looking for ?

**Comment by mgechev** [comment]
Cool, lets close the issue for now then.
