### ISSUE TITLE
Why explicitly exclude Angular 5?

### ISSUE THREAD

**Issue by whyboris** [mgechev/codelyzer#391]
Sorry I am unsure where/whether to ask:

Why is Angular 5 explicitly excluded as a peer dependency in _package.json_?
see: https://github.com/mgechev/codelyzer/blob/master/package.json#L75

```
  "peerDependencies": {
    "@angular/compiler": "^2.3.1 || >=4.0.0-beta <5.0.0",
    "@angular/core": "^2.3.1 || >=4.0.0-beta <5.0.0",
```

**Comment by mgechev** [comment]
Because we're not sure if there won't be any breaking changes in the internal APIs that we're using.

**Comment by whyboris** [comment]
Thank you 👍
