### ISSUE TITLE
"Property doesn't exist" warning appears for extended classes

### ISSUE THREAD

**Issue by SridharSathya** [mgechev/codelyzer#392]
Hi team,

The package is really nice to have good coding practice. But there is one problem which I face.

In my component1.ts I have the variable 
export class firstComponent{
@Input editable: boolean = false;
....
...

I am extending component1.ts in component2.ts like below

export class secondComponent extends firstComponent{
....
....

And in my component2.html, I am using 
<button [disabled] = "editable></button>

But codelyzer showing warning 

**The property "editable" that you're trying to access does not exist in the class declaration.**

Kindly please check on this.

**Comment by mgechev** [comment]
Please, take a look at existing issues.
