### ISSUE TITLE
use-host-property-decorator: case with route animations

### ISSUE THREAD

**Issue by DmitryEfimenko** [mgechev/codelyzer#393]
The case when you'd want to use `host` property for route animation is quite common:
```
@Component({
  selector: 'help-page',
  templateUrl: './help.component.html',
  animations: [routerTransition()],
  host: {'[@routerTransition]': ''}
})
export class HelpComponent  { }
```
You would not want to use HostBinding in the class because this property would just be unused, and possibly trigger another linting error.

Perhaps, use-host-property-decorator should have an exception for the animation bindings.
I also feel this should be added to the [style guide](https://angular.io/guide/styleguide#hostlistenerhostbinding-decorators-versus-host-metadata), but not sure where to submit this thought. Any pointers are appreciated!

**Comment by wKoza** [comment]
You can suggest this thought here with the prefix `docs(aio): `.

**Comment by mgechev** [comment]
Lets close this issue and keep the discussion in the Angular issue tracker when initiated.
