### ISSUE TITLE
[feature] Friendlier checking of validator directive names

### ISSUE THREAD

**Issue by RandomShaper** [mgechev/codelyzer#397]
Angular builtin validators are suffixed with `Validator`, not `Directive`.

Would it be possible to allow directives to follow that, as long as they implement the `Validator` interface?

**Comment by wKoza** [comment]
it seems to make sense. I'm ok.

**Comment by wKoza** [comment]
I had thought about that, but as you say, its not context dependent.  I prefer the second option even if it's not extensible. 
We should also manage the case of `AsyncValidator`.

**Comment by RandomShaper** [comment]
Yes, the second option seems the way to go.

And in addition to `AsyncValidator`, suffix `ValueAccesor` for the `ControlValueAccessor` interface.

I've checked the Angular API for more interesting directive naming cases and I don't see any other naming schema of interest for developers. Either they begin with `Ng` (which seems to give them permission to skip the naming guidelines) or are too core to think someone will need to do anything similar.

And if someone does, well, after all you are not following the guidelines, so a lint is what you deserve. :)

**Comment by wKoza** [comment]
mhm, i'm not in favour of implementing a rule for a `ControlValueAccessor `. For me, it's just a Component with a specific behaviour. @mgechev , an opinion ?

**Comment by RandomShaper** [comment]
The check would be for directives implementing that interface, allowing/forcing them to have the right suffix in their name.

That is, leaving components alone.

**Comment by mgechev** [comment]
@wKoza, this sounds good.

**Comment by mgechev** [comment]
Will take this one right now.
