### ISSUE TITLE
[feature] Don't warn about abstract components not declared

### ISSUE THREAD

**Issue by RandomShaper** [mgechev/codelyzer#398]
If a `Component` class is declared abstract you should not get this warning for it:

> Component '???' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration

What do you think?

**Comment by mgechev** [comment]
@RandomShaper this warning comes from the language service, codelyzer doesn't perform such check.

**Comment by RandomShaper** [comment]
Oops. Sorry then! :)

**Comment by mgechev** [comment]
No worries.
