### ISSUE TITLE
Error on @Pipe decorator

### ISSUE THREAD

**Issue by leonadler** [mgechev/codelyzer#399]
Follow-up on #111, this code we use for mocking pipes in unit tests throws `TypeError: Cannot read property 'text' of undefined
    at node_modules/codelyzer/pipeNamingRule.js:98:44`:

```TypeScript
export function mockPipe(name: string): any {
    @Pipe({ name })
    class MockPipe implements PipeTransform {
        transform(input: any): any {
            return input;
        }
    }
    return MockPipe;
}
```

Instead of throwing, maybe the rule can ignore variables in the decorator?

```TypeScript
// could be ignored by codelyzer
@Pipe({ name }) class DynamicPipe { ... }

// could be ignored by codelyzer
@Pipe({ name: variableName }) class DynamicPipe { ... }

// should be checked by codelyzer
@Pipe({ name: 'some-name' }) class RegularPipe { ... }
```

Alternatively, a meaningful error message (like in #111) mentioning the file in question would be better than throwing.

---

codelyzer@3.1.2
npm@5.3.0
node@8.1.4

---

Thanks for your great work!

**Comment by leonadler** [comment]
To clarify: The same code works and does not break codelyzer when rewritten like this:
```TypeScript
export function mockPipe(name: string): any {
    return Pipe({ name })(
        class MockPipe {
            transform(input: any): any {
                return input;
            }
        }
    );
}
```
However, knowing that this file is the culprit instead of getting a 'property of undefined' error thrown would be preferrable.
[This is the method that throws](https://github.com/mgechev/codelyzer/blob/83ece6906384e2443b8b99d2f842e288b8864873/src/pipeNamingRule.ts#L104) since it is called with a `property` without an `initializer`.

**Comment by mgechev** [comment]
Yes, codelyzer should ignore variables. Thanks for reporting the issue, I'll be on it.
