### ISSUE TITLE
Add a status for each rule

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#408]
We now have many rules offered by Codelyzer. However, some are experimental, others deprecated and many are stable.
it would be nice to give clarity on this to our users.
Maybe we can add a property in `IRuleMetadata`.

**Comment by mgechev** [comment]
@wKoza good idea!

**Comment by michahell** [comment]
Agree.

```
Could not find implementations for the following rules specified in the configuration:
    template-to-ng-template
    templates-use-public
    no-access-missing-member
    invoke-injectable
```

... nor could I :-)

**Comment by mgechev** [comment]
We have this in the readme.
