### ISSUE TITLE
Request for (beta) support for angular 5 (currently beta 6)

### ISSUE THREAD

**Issue by williamBurgeson** [mgechev/codelyzer#409]
Noticed when experimentally upgrading my ng 4 (angular-cli) project to ng 5 (beta 6) there was a codelyzer warning that it only supports < 5.0.0

I've run ng test and ng build without any problems, other than a build warning (although I didn't do code coverage, or ng build --prod for that matter)

Just one to put on the work path so when ng 5 goes live we don't get warnings.

**Comment by mgechev** [comment]
Angular 5 has breaking changes for codelyzer. There's no longer `JitReflector`. 

In the next a couple of days I'll see how much changes will be required and push an update.
