### ISSUE TITLE
Forbidden Imports

### ISSUE THREAD

**Issue by nerumo** [mgechev/codelyzer#41]
I'd like to forbid imports to a certain file to avoid that too much code is loaded even if not all is used. As an example I want to import rxjs. I do that through 

```ts
import {Observable} from 'rxjs/Rx';
```

and wow, I have all the operators available and no further import statement has to be made. But this loads all the 100 operators event if I just need the 'map' operator. What I should import is only

```ts
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/map';
```

I'd like to tell codelyzer that 'rxjs/Rx' is a forbidden import.

**Comment by mgechev** [comment]
Seems useful, I'm not sure how Angular specific it is.

I'll suggest to close it for now and limit the scope of the tool until we reach a point where we can afford to spend effort on similar enhancements.

**Comment by guojenman** [comment]
@nerumo 

I also wanted this feature today, so I quickly hacked something together.

```
import * as ts from "typescript";
import * as Lint from "tslint";

export class Rule extends Lint.Rules.AbstractRule {
    public static FAILURE_STRING = "import from \"rxjs/Rx\" not allowed because it includes ALL operators";

    public apply(sourceFile: ts.SourceFile): Lint.RuleFailure[] {
        return this.applyWithWalker(new NoAllRxWalker(sourceFile, this.getOptions()));
    }
}

class NoAllRxWalker extends Lint.RuleWalker {
    public visitImportDeclaration(node: ts.ImportDeclaration) {
        if (/rxjs\/Rx/.test(node.getText())) {
            this.addFailure(this.createFailure(node.getStart(), node.getWidth(), Rule.FAILURE_STRING));
        }
        super.visitImportDeclaration(node);
    }
}
```

see https://palantir.github.io/tslint/develop/custom-rules/ for how to use the code above

it's my first attempt at a rule and only spent only a few minutes on it, so it's very specific to rxjs/Rx but you could imagine making this configurable

**Comment by nerumo** [comment]
@guojenman thanks for the example. but @mgechev was right, this project only contains angular specific rules. so rules that apply for all kind of ts projects should be added to tslint. and some days ago they merged this feature on tslint: https://github.com/palantir/tslint/pull/1549

**Comment by guojenman** [comment]
I also agree, which is why the example is a custom rule for tslint and not an addition to codelyzer
