### ISSUE TITLE
"contextual-life-cycle" false positive on Directive

### ISSUE THREAD

**Issue by nicolashenry** [mgechev/codelyzer#410]
According to [this test file](https://github.com/angular/angular/blob/4.3.x/packages/compiler/test/directive_lifecycle_spec.ts), the "contextual-life-cycle" rule should not report errors on ngAfterContentInit/ngAfterContentChecked/ngAfterViewInit/ngAfterViewChecked being used on directive. However, the [documentation ](https://angular.io/guide/lifecycle-hooks) seems to be wrong about this.

**Comment by wKoza** [comment]
Hi @nicolashenry,
It's true. There is a problem in the documentation. An issue is open [here](https://github.com/angular/angular/issues/10221).
