### ISSUE TITLE
Issue in `check-pipe`

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#412]
By @rolandjitsu

> I'm still seeing some problems with the `check-pipe` rule for:
> ```html
> <p *ngIf="(items | async)?.length as length" class="mat-caption">
> ```
> 
> ```html
> <span *ngIf="product.propagationTolerance" class="label">&plusmn; {{ product.propagationTolerance | number }}</span>
> ```
> 
> For the latter, removing `&plusmn;` seems to fix it.

**Comment by wKoza** [comment]
@mgechev , do you have any idea for manage html entities (we have a problem with the position) ?

**Comment by mgechev** [comment]
@wKoza, the compiler converts them to unicode chars?

**Comment by wKoza** [comment]
yes, @mgechev

**Comment by mgechev** [comment]
Not sure if there's a way to handle this, except the one I shown above, used by the language service. However, this way, I'm afraid we're getting coupled even further to lower, unstable APIs :-/.

**Comment by wKoza** [comment]
BTW, this issue (with html entity) happens  even with check-semicolon :(

**Comment by mgechev** [comment]
https://github.com/mgechev/codelyzer/issues/460
