### ISSUE TITLE
Member access error in templates for extended classes

### ISSUE THREAD

**Issue by sefo** [mgechev/codelyzer#413]
#### Bug report

- __TSLint version__: 5.7.0
- __Codelizer version__: 3.2.0
- __TypeScript version__: 2.5.2
- __Running TSLint via__: VSCode

#### TypeScript code being linted

```ts
export class MenuNavLargeComponent extends MenuNavComponent {
  constructor() {
    super();
  }
}
```
```ts
export abstract class MenuNavComponent {
  menu: string[];
}
```
```html
<div *ngFor="let m of menu"></div>
```

#### Actual behavior

Error: The property "menu" that you're trying to access does not exist in the class declaration.

#### Expected behavior
No error.

In the template if I replace menu by this['menu'] the error goes away but it doesn't seem like a clean solution.

**Comment by wKoza** [comment]
duplicate #191

**Comment by StefH** [comment]
Now both issues are closed? Please re-open one !

**Comment by CSchulz** [comment]
This won't be fixed https://github.com/mgechev/codelyzer/issues/191#issuecomment-307685909

You can use the AoT build of Angular.

**Comment by wKoza** [comment]
@StefH , 'no-access-missing-member` is are out of date since the Language service Angular make this job. You can remove this rule now.
