### ISSUE TITLE
"angular-whitespace" rule false-positive (when using string with pipe, ngx-translate)

### ISSUE THREAD

**Issue by dominique-mueller** [mgechev/codelyzer#415]
When using the "angular-whitespace" rule together with the translation pipes provided by ngx-translate, an error gets thrown although there actually is none.

The following code:

``` html
<p>
  {{ 'PERSONAL-DATA.FIRSTNAME.LABEL' | translate }}
</p>
```

Results in the following error:
``` bash
ERROR: XX:XX   angular-whitespace   The pipe operator should be surrounded by one space on each side, i.e. " | ".
```

**Comment by dominique-mueller** [comment]
Interestingly enough, this only seems to happen when using **content projection / transclusion**. In our case, for instance:

``` html
<my-button>
  {{ 'MY-BUTTON.LABEL' | translate }}
</my-button>
```

Everything works find when used within divs (also when using ngIf) or when using this for attribute binding.

**Comment by mgechev** [comment]
Thanks for reporting this! We'll take a look at the issue.

**Comment by wKoza** [comment]
@dominique-mueller ,

Can you test this : 

```html
<p>{{ 'PERSONAL-DATA.FIRSTNAME.LABEL' | translate }}</p>
`

?

**Comment by dominique-mueller** [comment]
Hmpf. Weirdly enough, I can no longer reproduce this issue, seems it has disappeared over the weekend. Perhaps a caching issue or something broken on my machine.

Thanks though for the quick replies :)

**Comment by Ritzlgrmft** [comment]
I have the same problem, and it doesn't disappear by itself.

My code is par example:

```html
<button>
  {{ "button.label" | translate }}
</button>
```

This is complained by codelyzer.
However, if I add a `span`, codelyzer is satisfied: 

```html
<button>
  <span>{{ "button.label" | translate }}</span>
</button>
```

It would be great, if you could fix it in an upcoming release, so that it will work also without the `span`

**Comment by wKoza** [comment]
We have fixed it on the master branch. A new release will soon be available.
cc/ @mgechev
