### ISSUE TITLE
Issue in check-pipe with interpolation

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#416]
By @BorntraegerMarc,

> @mgechev the issue seems not to be resolved for me:
> ```
> D:\projects\komed-health-web>ng lint
> ERROR: src/app/chat/chat.component.html[22, 43]: The pipe operator should be surrounded by > one space on each side, i.e. " | ".
> 
> D:\projects\komed-health-web>ng --version
> @angular/cli: 1.4.2
> ```
> 
> this is the HTML code:
> ```
> <paper-item>
>    {{ 'chat.switchToDe' | translate }}
> </paper-item>
> ```

> from package.json:
> ```
> "codelyzer": "3.2.0",
> ```

**Comment by wKoza** [comment]
After investigation, our system of unit tests doesn't detect any problems. 
But, indeed, there is a false positive in my IDE (WebStorm).

It's not a regression over the last release (v3.1.2).

**Comment by BorntraegerMarc** [comment]
@wKoza what OS are you using? I could only reproduce it with widows until now

**Comment by wKoza** [comment]
OSX, @BorntraegerMarc .

**Comment by wKoza** [comment]
Ok, there is a difference between angular compiler 4.3.6 and 4.4.3 that impacts codelyzer ... This is why our travis crashs

**Comment by mgechev** [comment]
@wKoza maybe we can run conditionally the parser using `semver-dsl` like we do for other API differences?

**Comment by wKoza** [comment]
Yes, we can do that !
