### ISSUE TITLE
no-access-missing-member reports false positive

### ISSUE THREAD

**Issue by Martin-Wegner** [mgechev/codelyzer#417]
I tried to use https://github.com/kekeh/ngx-mydatepicker with this code:

```
<form>
  <div class="input-group">
      <input #dp="ngx-mydatepicker" class="form-control" name="mydate" [(ngModel)]="model" ngx-mydatepicker [options]="myOptions">
      <span class="input-group-btn">
          <button type="button" class="btn btn-default" (click)="dp.clearDate()">
              <i class="glyphicon glyphicon-remove"></i>
          </button>
          <button type="button" class="btn btn-default" (click)="dp.toggleCalendar()">
              <i class="glyphicon glyphicon-calendar"></i>
          </button>
      </span>
  </div>
</form>
```

The `no-access-missing-member` rule complains about:

> ERROR: ....component.html[5, 65]: The method "dp" that you're trying to access does not exist in the class declaration.
> ERROR: ....component.html[8, 65]: The method "dp" that you're trying to access does not exist in the class declaration.

**Comment by mgechev** [comment]
Please, use the search to find similar issues.

**Comment by Martin-Wegner** [comment]
https://github.com/mgechev/codelyzer/issues/264 ?
