### ISSUE TITLE
no-access-missing-member Material Menu support

### ISSUE THREAD

**Issue by buu700** [mgechev/codelyzer#419]
When using `#menu='matMenu'` in an HTML template instead of `#menu='mdMenu'` (the latter of which is deprecated as of the latest Material beta release), I get the error `The property "menu" that you're trying to access does not exist in the class declaration.`. It looks like [this](https://github.com/mgechev/codelyzer/blob/bc412c5cee4e43fa5736990dad24ce1b4ab3da4b/src/angular/config.ts#L70) is probably the cause.

**Comment by mgechev** [comment]
Please, take a look at the existing issues.
