### ISSUE TITLE
Feature request : Force a type to be imported and extended

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [mgechev/codelyzer#426]
Any way to force a particular type to be imported. 

E.g. I want any developer creating any component should import the BaseComponent class as some basic functionality is already implemented in it. I don't want people to forget including that class altogether.
Similarly, a way to force inclusion of BasePipe and BaseDirective. 

This will endure the basic functionalities will always be there.

Also, a eay of exclusion too might be required to exclude certain component, directive or pipes.

**Comment by lazarljubenovic** [comment]
How would you know which ones should be extended? I don't see a benefit of extending _all_ component in a project.

**Comment by rajjaiswalsaumya** [comment]
That can be specified part of codelizer conf

**Comment by mgechev** [comment]
This looks like an issue outside the scope of codelyzer. Thanks for sharing your ideas @rajjaiswalsaumya!
