### ISSUE TITLE
Feature request: disallow modifying input properties

### ISSUE THREAD

**Issue by franekp** [mgechev/codelyzer#428]
Disallow assigning values to input properties of a component, as if they were readonly.
for example:
```typescript
@Component(...)
class ChildComponent {@Input myInput: number}

@Component(
    template: `<child-component></child-component>`,
    ...
)
class ParentComponent {
    @ViewChild(ChildComponent) childComponent;
    someMethod() {
        this.childComponent.myInput = 42
    }
}
```

**Comment by mgechev** [comment]
Sounds like a good idea.

**Comment by rafaelss95** [comment]
Another example:

```ts
@Component(...)
class AComponent implements OnInit {
  @Input() myInput: number;

  ngOnInit() {
    this.myInput = 1;
  }
}
```

**Comment by NagRock** [comment]
Whats the purpose for this? What is bad with setting input value?

**Comment by lazarljubenovic** [comment]
Developers expect them to be in sync. Furthermore, they can be overwritten when the parent component sets the inputs to a child. 

By the way, Vue has a built-in run-time-dev warning for this.

**Comment by mgechev** [comment]
@rafaelss95 it won't be safe to make inputs `readonly` (reasons that @franekp mentioned) but for outputs, this seems to work well.

>So, the question is: What would be the most correct way to do this?

What you suggested sounds good. You can store the inputs in a `Set` to have a check with `O(1)`.

**Comment by rafaelss95** [comment]
@franekp @mgechev I'm not sure this breaks AOT compilation. Maybe in past... idk, but I always make my `@Input`s `readonly` and it doesn't break AOT.

**Comment by mgechev** [comment]
@rafaelss95 since assignment to different values of already initialized `readonly`properties is not allowed, my guess is that it's not a good idea to be used for inputs.

**Comment by franekp** [comment]
@rafaelss95 @mgechev I was wrong, I checked and this does not break AOT compilation. Sorry for unnecessary confusion. Also, `readonly` is only a compile-time thing: https://blog.mariusschulz.com/2016/10/31/typescript-2-0-read-only-properties#readonly-vs-immutability

Therefore I think that enforcing inputs being `readonly` is the most clean way to do it.

**Comment by mgechev** [comment]
Yes, static analysis is ahead of time check as well. If inputs are mutable (and they are), they should not be readonly.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
