### ISSUE TITLE
Enforce wrapping all validators in an array when using FormBuilder

### ISSUE THREAD

**Issue by lazarljubenovic** [mgechev/codelyzer#429]
It often happens to me that I accidentally register a validator as async validator because I fail to wrap them into an array. Basically, I have code like this for a long time:

```
email: [null, Validators.required],
```

A few days later, I realize I need to add another validator, so I do the following:

```
email: [null, Validators.required, Validators.email],
```

And :boom:, this is a _run-time_ error :scream: because this syntax expects `[value, syncV, asyncV]`. What I actually wanted was:

```
email: [null, [Validators.required, Validators.email]],
```

I'm currently trying to establish a style to always wrap a validator in an array, even if it's only one. I'm trying to write this from the start:

```
email: [null, [Validators.required]],
```

Thought it would be nice addition here. ✨

**Comment by mgechev** [comment]
@lazarljubenovic we should decide if we want to introduce this as style in the style guide.

You can open an issue [here](https://github.com/angular/angular/issues) and we can start the keep the discussion there.

To me this looks like an error which should be handled by the TypeScript compiler.

**Comment by wKoza** [comment]
Hi @lazarljubenovic ,

For me , if you want more typing, you should use the constructor of `FormControl` like this : 

```typescript

this.personForm = new FormGroup({
      lastName: new FormControl('',Validators.required,Validators.minLength(3)),  <-- error
 ...
     });
```
With Codelyzer, it seems to be complicated.

**Comment by mgechev** [comment]
Lets close the issue for now.

**Comment by lazarljubenovic** [comment]
Thanks for the response, guys. @wKoza's suggestion works obviously, but it's too verbose when there are many forms. I'll see to open an issue at Angular repo or check out why there are not stronger types when using FormBuilder.

**Comment by mgechev** [comment]
@lazarljubenovic sounds like a good idea. The `any` types in the `FormBuilder` can be changed, however, keep in mind that this will be considered a breaking change, so probably it won't land in the next major release.
