### ISSUE TITLE
RxJS operators should not patch the prototype of Observable

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#430]
It's an [opened issue](https://github.com/angular/material2/issues/2622) by Rob that may be implemented in Codelyzer. 

What do you think about that ?

**Comment by mgechev** [comment]
@wKoza some time back I implemented [this](https://palantir.github.io/tslint/rules/no-import-side-effect/) tslint rule which makes sure we don't use imports with side-effects.

**Comment by wKoza** [comment]
humm... excellent !  This rule deserves to be discovered more ...
