### ISSUE TITLE
use-life-cycle-interface is not working properly for extended classes

### ISSUE THREAD

**Issue by kykint** [mgechev/codelyzer#431]
If we have next code:

```
class SomeComponent implements OnInit {
    ngOnInit(){
        /*some logic*/
    }
}

class ExtendedSomeComponent extends SomeComponent {
    ngOnInit(){
        super.ngOnInit();
        /*some logic*/
    }
}
```

We receive error, that ExtendedSomeComponent not implements OnInit , but it is not true. Is it possible to fix it?

**Comment by mgechev** [comment]
@kykint codelyzer doesn't support inheritance chain since it does not perform type checking. I'd recommend you to disable the rule for this file or implement the interface explicitly for the child class as well.
