### ISSUE TITLE
Error using in latest angular cli

### ISSUE THREAD

**Issue by vivekimsit** [mgechev/codelyzer#432]
I have following versions:

```
@angular/cli: 1.4.7
node: 6.11.2
os: darwin x64
@angular/animations: 4.4.2
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.2
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.4.7
@angular/compiler-cli: 4.4.2
typescript: 2.5.2
```

It seems like I am doing something wrong. I will update soon

**Comment by mgechev** [comment]
This doesn't seem an issue related to codelyzer. As Angular CLI says, you cannot use `new` command inside of Angular CLI project.

**Comment by vivekimsit** [comment]
@mgechev ok, that was a stupid thing from me. Can you please guide me to doc for setting it up for existing angular-cli project?

**Comment by mgechev** [comment]
You can take a look at the [Angular CLI repository](https://github.com/angular/angular-cli).
