### ISSUE TITLE
Feature request: force access modifier on @Input and @Output decorators

### ISSUE THREAD

**Issue by lukiffer** [mgechev/codelyzer#434]
`public` is implied by using `@Input()` and `@Output()` and since TypeScript doesn't support the `internal` modifier, I can't think of a use case for an access modifier other than `public`. I know it's not super critical as the modifier is virtual and doesn't affect the JS artifact, but semantically it would be nice to check for this.

**Comment by mgechev** [comment]
Hey @lukiffer thanks for giving codelyzer a try and thanks for the suggestion!

TypeScript supports `/* @internal */` annotation with a comment. Extending the syntax of TypeScript includes extension of the compiler that the language provides as well which is out of the scope of the tool.
