### ISSUE TITLE
Feature request: disallow returning object/array literals from getters in components

### ISSUE THREAD

**Issue by franekp** [mgechev/codelyzer#436]
When writing a component, it is very natural to write a getter that conditionally returns an object literal and use that getter inside a template. Such code confuses change detection because the getter returns a new object each time instead of reusing existing one.

Example:
```typescript
@Component({
    template: '<my-item-list items="items"></my-item-list>',
})
export class MyComponent {
    isCollapsed = false
    get items() {
        return this.isCollapsed ? [] : [{name: 'foo'}, {name: 'bar'}],
    }
}

@Component({
    template: '<ul><li *ngFor="let item of items"> {{ item.name }} </li></ul>'
})
export class MyItemList {
    @Input items: {name: string}[]

    ngOnChanges() {
        console.log('This message behaves as if it was inside an infinite loop.')
    }
}
```

**Comment by mgechev** [comment]
That's a good point! I think the proposal addresses only one of the problems and a generic solution might not be suitable for a linting rule without type checking (similar to the codelyzer rules).

Lets keep the issue open for now.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
