### ISSUE TITLE
Built-in directive config not compatible with material2 beta.12

### ISSUE THREAD

**Issue by csvn** [mgechev/codelyzer#437]
All `md-/Md` prefixes has been removed in favor of `mat-/Mat` prefix. To those who upgrades, the codelyzer rule `no-access-missing-members` now throws errors on valid code.

```
<button [matMenuTriggerFor]="menu">menu</button>
<mat-menu #menu="matMenu">
</mat-menu>
```
> "The property "menu" that you're trying to access does not exist in the class declaration.

The cause for this is that the configuration only exports `mdMenu`, not `matMenu`. Is it possible to have multiple exports (e.g. `exportAs: 'mdMenu, matMenu'`)? There are also several directives that are not configured correctly for the `mat-` prefix.
https://github.com/mgechev/codelyzer/blob/master/src/angular/config.ts#L69-L74

I'd be happy to make a pull request, but I'm not sure what to do for backwards compatibility to support both options. Maybe it's best to just split `md` & `mat` into their own like below?

```
// material2 deprecated `md` prefixes
{ selector: 'md-button-toggle-group', exportAs: 'mdButtonToggleGroup' },
{ selector: 'md-select', exportAs: 'mdSelect' },
{ selector: 'md-menu', exportAs: 'mdMenu' },
{ selector: '[md-menu-item]', exportAs: 'mdMenuItem' },
{ selector: '[md-menu-trigger-for], [mdMenuTriggerFor]', exportAs: 'mdMenuTrigger' },
{ selector: '[md-tooltip], [mdTooltip]', exportAs: 'mdTooltip' },

// material2 official `mat` prefixes
{ selector: 'mat-button-toggle-group', exportAs: 'matButtonToggleGroup' },
{ selector: 'mat-select', exportAs: 'matSelect' },
{ selector: 'mat-menu', exportAs: 'matMenu' },
{ selector: '[mat-menu-item]', exportAs: 'matMenuItem' },
{ selector: '[mat-menu-trigger-for], [matMenuTriggerFor]', exportAs: 'matMenuTrigger' },
{ selector: '[mat-tooltip], [matTooltip]', exportAs: 'matTooltip' },
```

In #395 I was told that `no-access-missing-members` would be removed, but I have seen no evidence of this yet in the v4 beta branch. Right now it's pretty messy, where I have to copy all the settings and adjust them. Any info about this would be appreciated.

**Comment by mgechev** [comment]
@csvn your suggestion sounds good. Would you open a PR with the update?

**Comment by csvn** [comment]
@mgechev Sure, I'm on it!
