### ISSUE TITLE
decorator-not-allowed produces false positives after an error is found

### ISSUE THREAD

**Issue by reduckted** [mgechev/codelyzer#441]
Once the `decorator-not-allowed` generates an error, it seems to generate more errors for decorators.

**Dependencies:**

|Package|Version|
|----------|---------|
|codelyzer|3.2.2|
|tslint|5.8.0|
|typescript| 2.5.3|
|angular/compiler|4.4.6|
|angular/core|4.4.6|

This code produces the expected errors (in `BadService`):
```typescript
import { Component, Injectable, Input } from '@angular/core';

@Component({})
export class GoodComponent {
    @Input() public foo: string;
}

@Injectable()
export class BadService {
    @Input() public foo: string;
}
```

```
* In the class "BadService" which have the "@Injectable" decorator, the "@Input" decorator is not allowed. Please, drop it. (decorator-not-allowed)' at: '10,5'
```

But, if you swap the order that the `GoodComponent` and `BadService` classes are defined in, two errors are produced (in `BadService` and `GoodComponent`, but they have the same error message):

```typescript
import { Component, Injectable, Input } from '@angular/core';

@Injectable()
export class BadService {
    @Input() public foo: string;
}

@Component({})
export class GoodComponent {
    @Input() public foo: string;
}
```

```
* 'In the class "BadService" which have the "@Injectable" decorator, the "@Input" decorator is not allowed. Please, drop it. (decorator-not-allowed)' at: '5,5'
* 'In the class "BadService" which have the "@Injectable" decorator, the "@Input" decorator is not allowed. Please, drop it. (decorator-not-allowed)' at: '10,5'
```

It looks like the rule is not resetting its state when it starts walking through a new class, so when it sees the `@Input` decorator in `GoodComponent`, it still thinks it's in an `@Injectable` class instead of a `@Component`.

**Comment by mgechev** [comment]
@reduckted thanks for reporting this issue!
