### ISSUE TITLE
i18n check-text edge cases

### ISSUE THREAD

**Issue by Manduro** [mgechev/codelyzer#442]
Some cases where the i18n rule with `check-text` errors, but shouldn't (imo):

```html
<mat-checkbox i18n="@@terms">
  I agree to the
  <a href="#">terms of service</a>
</mat-checkbox>
```

```html
<ng-container i18n="@@minlength">
  Use at least {{ minLength }} characters
</ng-container>
```

**Comment by mgechev** [comment]
Thanks for reporting this! Added it to the next release.

**Comment by mgechev** [comment]
@Manduro the rule with the `check-text` option will not fail if:

>Each element containing text node should have an i18n attribute

In such case, the first is invalid, right?

**Comment by mgechev** [comment]
@Manduro would you take a look at the referenced PR and tell me if you think that's the behavior you think the rule should have?

In the end, the content of the element with i18n will be replaced by the compiler so the interpolation will be lost, right?

If that's the case, I'd suggest to introduce another config option to this rule which warns when an interpolation is used inside of an element with i18n attribute.

**Comment by wKoza** [comment]
I'm not an i18n Expert, but the Angular documentation says that we can use interpolation with i18n attribute : see https://angular.io/guide/i18n#translate-singular-and-plural

**Comment by Manduro** [comment]
Yes we can use interpolation if I'm correct, but be sure to double check it!

I'm not sure if the first case I submitted is valid. Maybe it was just my wishful thinking. I'd probably need to split that into two elements with two i18n attributes.

**Comment by wKoza** [comment]
For me, it's not valid if we take a look at this : https://github.com/angular/angular/issues/18302

**Comment by mgechev** [comment]
Sounds good. Looks like the PR I opened fixes the second, incorrect, behavior. Let me know if you think we can add anything else.
