### ISSUE TITLE
Nested i18n linting

### ISSUE THREAD

**Issue by intellix** [mgechev/codelyzer#443]
A couple of us within our team accidentally nest i18n properties which will cause xi18n extraction to fail: 
```
<div i18n>
  <span i18n>First name</span>
</div>
```

The error thrown during xi18n is:
```
An error occured during the i18n extraction:
Error: Could not mark an element as translatable inside a translatable section
```

Not sure if this should fail Angular compilation or if there should be a linting rule to help identify these before they get merged. Thoughts?

**Comment by mgechev** [comment]
@intellix at first, to me it looks like it's the responsibility of xi18n to throw an error.
