### ISSUE TITLE
How to use with Angular 1 (angular.js)

### ISSUE THREAD

**Issue by mderazon** [mgechev/codelyzer#444]
When migrating angular.js app to Angular one of the [steps](https://angular.io/guide/upgrade#preparation) is to make sure your code is following the [john papa styleguide](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md). We can use [Angular.js ESLint plugin](https://github.com/Gillespie59/eslint-plugin-angular) for that and import those set of rules.

But another step in the migration process is to switch to using Typescript.  At that point, we need to start using TSlint but there's no TSlint rules for Angular 1 projects as far as I know. 

Any recommendation on how to solve this issue ?

**Comment by mgechev** [comment]
Codelyzer does not support AngularJS and introducing such feature is not part of the roadmap.
