### ISSUE TITLE
Codelyzer hanging for "styles" attribute in Angular component

### ISSUE THREAD

**Issue by bthharper** [mgechev/codelyzer#446]
I am developing an application using @angular/cli 1.4.9 and @angular 4.4.x , but have encountered an issue running `ng lint` on the code recently.  I've diagnosed this using ` tslint -c tslint.json .\src\some.component.ts` which never returns.  

I have traced this down to the following code snipet:

```typescript
@Component({
  selector: 'div[some-component]',
template: `<ng-content></ng-content>`,
  styles: [
  `:host {
    display:        flex;
    flex:           1 100%;
    margin:         20px;"
  }`
  ],
  changeDetection: ChangeDetectionStrategy.OnPush
})
```

Specifically the _styles_ options, if I remove this the above command succeeds.

I have played with different options in the tslint.json file, but find that many of them cause this not a specific one.

Is there anyway I can get diagnostic logging out to assist in this?

**Comment by bthharper** [comment]
Okay, my mistake and I've worked out what was wrong with my code ... but it would be good if this was reported rather than causing the tool to hang.

I'd accidentally put a quote (") after the *20px;*.

```
`:host {
    display:        flex;
    flex:           1 100%;
    margin:         20px;"
  }`
```

The typescript / angular compilers don't report this, but tslint fails.

**Comment by mgechev** [comment]
We can update the CSS parser that we use. Let's keep that open for now.

**Comment by HideDev** [comment]
Hi, any news?

**Comment by mgechev** [comment]
@HideDev I'll fix this as part of the next minor release.

**Comment by HideDev** [comment]
@mgechev thanks
