### ISSUE TITLE
Allow angular5

### ISSUE THREAD

**Issue by maosmurf** [mgechev/codelyzer#447]
Hi,

angular 5 is almost out (currently at RC7)
Codelyzers peerDependencies still state `<5.0.0` though.
Any reasons not to bump it?
We were working with a fork of yours, so far everything is stable.
https://github.com/kurier/codelyzer/commit/3c18cff13e5d8af258425d93a4d6f15e526bb995

Thank you!

**Comment by mgechev** [comment]
https://github.com/mgechev/codelyzer/pull/439
