### ISSUE TITLE
no-on-prefix-output-name is an unknown rule

### ISSUE THREAD

**Issue by Martin-Wegner** [mgechev/codelyzer#450]
Using the new rule `"no-on-prefix-output-name": true` does not work with codelyzer 4.0.0:

```
Could not find implementations for the following rules specified in the configuration:
    no-on-prefix-output-name
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```

**Comment by dhardtke** [comment]
Yep, same issue. Even the downloaded zip file from "Releases" does not contain a `noOnPrefixOutputName.ts` inside the src dir :(

**Comment by mgechev** [comment]
Will take a look at the problem today and issue a minor release.

**Comment by mgechev** [comment]
Sorry, mistake in the release logs. The rule name is `no-output-on-prefix-name`.

**Comment by Martin-Wegner** [comment]
@mgechev `test/noOutputOnPrefixNameRule.spec.ts`, `docs/src/worker.ts` and `src/noOutputOnPrefixNameRule.ts` still contain the wrong name `no-on-prefix-output-name` :(

**Comment by mgechev** [comment]
Hey Martin, would you open a PR with a fix?

**Comment by Martin-Wegner** [comment]
https://github.com/mgechev/codelyzer/pull/451

**Comment by Martin-Wegner** [comment]
@mgechev https://github.com/mgechev/codelyzer/pull/451
