### ISSUE TITLE
"angular-whitespace" rule false-positive (when using string with pipe, ngx-translate)

### ISSUE THREAD

**Issue by Ritzlgrmft** [mgechev/codelyzer#452]
My code is par example:

```html
<button>
  {{ "button.label" | translate }}
</button>
```

This is complained by codelyzer: `The pipe operator should be surrounded by one space on each side, i.e. " | ".`
However, if I add a `span`, codelyzer is satisfied: 

```html
<button>
  <span>{{ "button.label" | translate }}</span>
</button>
```

The same problem was already reported in #415. It was fixed in release 3.2.2, but in 4.0.1, it happens again.

**Comment by FabienDehopre** [comment]
I have this issue even when using version 3.2.2

**Comment by FabienDehopre** [comment]
BTW, the error happens randomly with 3.2.2. 
I made a change (removed an empty line) and the error did not happen.

**Comment by FabienDehopre** [comment]
Any news about this issue?
It still happens on the latest release (4.0.2)

**Comment by mgechev** [comment]
Here are the changes from [4.0.2](https://github.com/mgechev/codelyzer/blob/master/CHANGELOG.md#402).

**Comment by FabienDehopre** [comment]
OK. I read the changelog for the 4.0.2. 
My question was when would this issue (related to the check-pipe) be solved?

**Comment by jeneg** [comment]
Got the same issue on 4.0.2. @mgechev Is it going to be fixed?

**Comment by mgechev** [comment]
Let's drop the `check-pipe` as @wKoza suggested https://github.com/mgechev/codelyzer/issues/460.

**Comment by slimlime** [comment]
I had an issue with angular-whitespace or one of the fixers that seemed to identify angular moustache templates in my typescript files (no templates) and 

```ts
import {
  FormControl,
  FormGroup,
  FormBuilder,
  Validators,
  FormArray
} from "@angular/forms";

```
became 
```ts
imp; }}t{{ { {  }}{  }} {  }} {  }}
  }}ormArray,
  FormBuilder,
  FormGroup,
  Validators;
} from; '@angular/forms';
```

I had ridiculously run the tslint --fix autofix while working out how to use tslint and ended up replacing even more `}}` 🤣.

I'm still trying to track things down.
