### ISSUE TITLE
Pipe usage shows invalid whitespace error

### ISSUE THREAD

**Issue by Tragetaschen** [mgechev/codelyzer#455]
Version: 4.0.1

I have reduced my template to the dead simple
```html
{{value1 | async}}
{{value2 | async}}

```
and still `check-pipe` shows a white space error on the second line:
```
...[2, 7]: The pipe operator should be surrounded by one space on each side, i.e. " | ".
```

When I reduce it to just one line, the error goes away.
The file has Windows line endings:
![image](https://user-images.githubusercontent.com/1947968/32602417-509c0320-c546-11e7-9b92-29845b1043da.png)

**Comment by mgechev** [comment]
https://github.com/mgechev/codelyzer/issues/460
