### ISSUE TITLE
Drop check-pipe rule ?

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#460]
there are many issues open concerning the check-pipe rule. IMO, this problems are unsolvable without introduce other risks.
@mgechev , what do you think about drop once and for all this rule ?

**Comment by mgechev** [comment]
I believe the Angular team is working on making the compiler with a friendlier API, especially for template references. We can remove it from the `README.md` file. If we drop it completely, this will be a breaking change so we'll have to release version 5 as well.

**Comment by wKoza** [comment]
hmm, friendlier API ? good news ! indeed, it would be a breaking change. it may not be the right moment, yes. But, meanwhile, some people are waiting for an answer to these problems. I think we need to provide a answer to these people. 

BTW, We have remove this option from the `README.md`but It's inconsistent with the [tslint doc](http://codelyzer.com/rules/) where we talk about it. It can be confusing.

**Comment by mgechev** [comment]
We can drop if from master, generate the docs and push it to GitHub Page. We should remember to re-enable it if we push minor/patch versions.

**Comment by jaufgang** [comment]
Perhaps instead of removing it from the docs, you could document that it has been removed.  That way, developers trying to use the `check-pipe` who are looking at the docs won't be scratching their heads wondering where it is and need to search around to find this issue in order to figure out what happened to it.

**Comment by slimlime** [comment]
@jaufgang I think I just had an issue when I thoughtlessly copied a config file and somehow managed to replace parts of my `ts` code with `}}{}{}}{}}}{}` *scratches head*

I still managed to accidentally copy this from some version of docs(?) with check-pipe and ended up breaking my code
```ts
"angular-whitespace": [
      true,
      "check-interpolation",
      "check-pipe",
      "check-semicolon"
    ],
```

**Comment by slimlime** [comment]
## Clearer example
```ts
@Component({
  selector   : 'hero-list',
  templateUrl: 'hero-list.html'
})
export class HeroListComponent {
```
became

```ts
@Component({
  selector   : 'hero-list',
  templateUrl: 'hero-list.h{{ l',
})
 }}port class HeroListComponent {
```

regex?
