### ISSUE TITLE
[Feature Request] disallow using deprecated angular features

### ISSUE THREAD

**Issue by stocksr** [mgechev/codelyzer#461]
I would love the linter to complain when I use anything listed on this page
https://angular.io/api?status=deprecated

adding a warning for this lot would be useful as well: https://angular.io/api?status=experimental

Any implementation of this would have to be tied into the version of angular installed in the project, but perhaps this could be done by accessing the comment defined on item. e.g: https://github.com/angular/angular/blob/master/packages/http/src/http.ts#L101

**Comment by wKoza** [comment]
Hi @stocksr ,

Tslint offers the rule `deprecated`  currently. 

```javascript
 "deprecation": {
      "severity": "warn"
    },
```

We can extend this rule to handle the @experimental tag.

Thanks

**Comment by stocksr** [comment]
Many thanks - I guess I was looking in the wrong place.
