### ISSUE TITLE
no-input-rename rule: include exception for inputs used by directives

### ISSUE THREAD

**Issue by darkbasic** [mgechev/codelyzer#462]
I have several components which show a chat, user or message item.
Each one of them has a chat, user or message input.
I made a directive (which could be used on all of them) which needs to access the chat, user or message inputs. Since the directive has to be generic it creates another input called `item`.
So here is how I use my directive:

```
<chat-item [chat]="chat" myDirective="something" [item]="chat"></chat-item>

<message-item [message]="message" myDirective="something" [item]="message"></message-item>

<user-item [user]="user" myDirective="something" [item]="user"></user-item>
```

[chat, message, user] and item are redundant, so I prefer to simply omit the first and just use item:
```
<chat-item myDirective="something" [item]="chat"></chat-item>

<message-item myDirective="something" [item]="message"></message-item>

<user-item myDirective="something" [item]="user"></user-item>
```

Inside the [chat, message, user]-item components I prefer to refer to the item as chat, message or user, to make the code more readable. That's why I use:
```
@Input('item')
  chat;

@Input('item')
  message

@Input('item')
  user
```

In my opinion this is a use case where renaming is useful and an exception should be made.

**Comment by mgechev** [comment]
You can disable this rule for the directive itself. Take a look at https://palantir.github.io/tslint/usage/rule-flags/.

**Comment by darkbasic** [comment]
Thanks, I'm using `// tslint:disable-next-line:no-input-rename`
