### ISSUE TITLE
Feature Request: Check for unused returned RxJS Subscription objects

### ISSUE THREAD

**Issue by cormacrelf** [mgechev/codelyzer#467]
IMO, the following is the best way to unsubscribe from Rx subscriptions you create in your components. It uses the very simple chained IDisposable-esque interface of a Subscription for exactly its intended purpose.

```typescript
destroy = new Subscription();
 ...
this.destroy.add(someObservable$.subscribe(() => {
    // ...
}));
...
ngOnDestroy() {
    this.destroy.unsubscribe();
}
```

Unlike other methods (think `destroy = new Subject(); takeUntil(destroy$).subscribe(...)`), it's not hard to statically check if the subscription will eventually be unsubscribed. It would be awesome if Codelyzer could check for the anti-pattern:

```typescript
someObservable$.subscribe(() => { ... });
// or
const subscription = someObservable$.subscribe(() => { ... });
// where there is a warning: unused variable subscription
```

This would likely catch more bugs than all other codelyzer rules combined. I don't think you would need to check for used-but-not-unsubscribed, this is good enough. I don't know if it's possible or not, though. Can anyone comment on feasibility?

**Comment by mgechev** [comment]
@cormacrelf TypeScript 1.6 will warn you if you are not reading a private variable, which handles the second case. The first one should be easy to catch by codelyzer, although without type checking it'll be more of a guess rather than a proof.

**Comment by cormacrelf** [comment]
Do you get type checking in Tslint? It may be more broadly applicable to implement there instead, come to think of it.

**Comment by mgechev** [comment]
Yes, you can use the type checker in tslint rules but this has a price:
- Slower linting
- VSCode doesn't support type checking in their tslint extension

**Comment by cormacrelf** [comment]
Ok. I’d want this in any Rx project, so I’ll file on tslint and maybe have a go. Thanks for the help!
