### ISSUE TITLE
False positive use-pipe-transform-interface with inheritence

### ISSUE THREAD

**Issue by trenneman** [mgechev/codelyzer#468]
The following code gives me an unfairly error `The MyPipe class has the Pipe decorator, so it should implement the PipeTransform interface`:

```
@Injectable()
export class AbstractPipe implements PipeTransform {
  transform(value: any, ...args: any[]): any {
    return this.toView();
  }

  abstract toView(): string;
}

@Pipe({
  name: 'myPipe'
})
export class MyPipe extends AbstractPipe {
  toView(): string {
    return 'foo';
  }
}
```

`MyPipe` does indeed not implement `PipeTransform`, but its parent `AbstractPipe` does.

**Comment by wKoza** [comment]
Hi @trenneman ,

Codelyzer aims to provide linting for style errors which can be found by providing a "shallow analysis". Your example requires a deep analysis with Type Checker. This mecanism is very expensive and it is not supported by VSCode.

@mgechev , you confirm ?

**Comment by mgechev** [comment]
Yes, correct.

**Comment by trenneman** [comment]
Too bad. Thanks for the clarification.
