### ISSUE TITLE
Show Lint errors when running the ng lint command

### ISSUE THREAD

**Issue by kjdevocht** [mgechev/codelyzer#47]
Is the ng lint command supposed to tell me what the lint errors actually are?  Right now when I run it, it just says "Lint errors found in the listed files"  and does not tell me what the lint errors are

**Comment by cindoum** [comment]
Same here...

**Comment by mgechev** [comment]
Error reporter is not part of the project. We'll even try to keep it independent from the underlying platform. I guess this is an issue that should be reported to tslint instead.
