### ISSUE TITLE
"Could not find implementations for..." error when using extends: [codelyzer] approach

### ISSUE THREAD

**Issue by rtm** [mgechev/codelyzer#475]
I am using

    "extends": [codelyzer]

since I have a slightly non-standard repo structure where codelyzer has been hoisted to a higher level of a monorepo. Problem is, I consistently get the error

    Could not find implementations for the following rules specified in the configuration:
        banana-in-box

when my `tslint.json` file looks like this:

    {
      "extends": [ "codelyzer" ],
      "rules": {
        "banana-in-box": true
      }
    }

The same error occurs for each and every rule specified as `true`. This happens even when I create a brand-new repository, just add the bare minimum dependencies, the `tslint.json` file above, and a simple test TS file.

Am I missing something basic, or is there some problem with the `"extends": [codelyzer]` approach?

There is a repo reproducing this at https://github.com/rtm/codelyzer-extends-problem.

**Comment by mgechev** [comment]
Here's how you can configure tslint properly:

```
{
  "rulesDirectory": [ "node_modules/codelyzer" ],
  "rules": {
    "banana-in-box": true
  }
}
```

**Comment by mgechev** [comment]
Btw, you can try the [`tslint-angular`](https://github.com/mgechev/tslint-angular) preset for using a configuration similar to the one you posted.

**Comment by crush83** [comment]
I've tried both of the following with no luck:
```
"rulesDirectory": [
    "node_modules/codelyzer",
    "tslint-consistent-codestyle"
]
```
and
```
"rulesDirectory": [
    "codelyzer",
    "tslint-consistent-codestyle"
  ]
```

I am running `ng lint` from the root of my angular-cli project directory.

The path to `codelyzer` from my `tslint.json` is `node_modules/codelyzer`...

I have also installed `tslint-consistent-codestyle` and it runs without issue.

I am using `"codelyzer": "~4.4.4",` with `"@angular/cli": "~6.2.1",` and "tslint": "~5.11.0",

I'm unsure what else to try to get this working...
