### ISSUE TITLE
[Feature request] Warn user when Input/output does not exist in component and type checking

### ISSUE THREAD

**Issue by Tukks** [mgechev/codelyzer#476]
Hi!

I have this component :

```
 @Component({
  selector: 'example-component',
  templateUrl: 'example-component.component.html',
  styleUrls: ['example-component.component.scss']
})
export class ExampleComponent {

  @Input() label: string;
 @Output() event: string;
}
```
If I wrote this in another template like this : 
```
<example-component (label)="1" (noExistingInput)="'label'" [event]="exampleMethod()">
<example-component>
```
I have no warning on the noExistingInput, and no warning on label input waiting for a string and receiving a number.
Can you provide this?

**Comment by mgechev** [comment]
Hey @Tukks this is a compile-time error which makes the feature outside the scope of codelyzer. To get this behavior use the Angular language service.

**Comment by Tukks** [comment]
Ok, sorry I opened a issue at angular/angular#21204

**Comment by intellix** [comment]
hey @mgechev it seems that the Inputs are AOT compilation errors but Outputs are not: https://github.com/angular/angular/issues/17483#issuecomment-358658842

Shall I open another issue perhaps?

**Comment by mgechev** [comment]
This will require "deep analysis", or type checking, so we will hit these issues https://github.com/mgechev/codelyzer/issues/191. Let's leave this to the compiler, whenever it gets ready.
