### ISSUE TITLE
Configuration presets

### ISSUE THREAD

**Issue by HideDev** [mgechev/codelyzer#477]
@mgechev there are plans to add a config with presets for angular projects like presets for tslint:  tslint:latest, tslint-react, etc. ?

**Comment by mgechev** [comment]
Haven't considered introducing such. [This](https://github.com/angular/angular-cli/blob/ac09d40eacf5d33873260daebfd84752a94527ed/tests/e2e/assets/1.0.0-proj/tslint.json) looks like a valid option which can be published.

**Comment by HideDev** [comment]
@mgechev thanks
