### ISSUE TITLE
More than one prefix for directive/component/pipe

### ISSUE THREAD

**Issue by huyph** [mgechev/codelyzer#48]
I think at the moment there is only one prefix allowed. Should we have more than one for a project?

The example styleguide seems to say yes
https://angular.io/docs/ts/latest/guide/style-guide.html#!#style-02-07

**Comment by mgechev** [comment]
Yes, this is a limitation. We can allow multiple prefixes as part of the configuration:   `"directive-selector-prefix": [true, "sg", "another-prefix", "yet-another", "fourth"]`.

@filipesilva, @Brocco do you think this is going to fit well with the cli?

// cc @preslavsh

**Comment by filipesilva** [comment]
I think multiple prefixes are a good idea. The CLI already allows for multiple individual apps to be present in a project (angular2-material makes use of this) so it's not hard to see that these might need different prefixes.

It would also help giving the user flexibility in the recommendation here https://github.com/angular/angular-cli/pull/740#issuecomment-218821516.

**Comment by Brocco** [comment]
The CLI currently supports a single prefix, but there have been discussions surrounding feature-based prefixes. I'm not sure if/when this will be supported by the CLI, but I don't see a reason that the CLI should restrict the analysis of a project. If I have a default prefix of `foo` and want to change it manually after the fact I think this tool should support it even if the CLI does not.

**Comment by filipesilva** [comment]
Well we support overriding the prefix so it stands to reason that prefixes shouldn't be limited via linting as well.

**Comment by mgechev** [comment]
Sounds good. So we'll add context independent prefix checking. It'll be cool to make it context dependent one day.

**Comment by huyph** [comment]
what are the difficulties in making the checking context dependent?

**Comment by mgechev** [comment]
Implemented by @preslavsh here https://github.com/mgechev/codelyzer/pull/71.
