### ISSUE TITLE
no-output-on-prefix incorrectly throws error if output property name starts with "one"

### ISSUE THREAD

**Issue by compeek** [mgechev/codelyzer#480]
I enabled the new `no-output-on-prefix` rule and started getting an error for an output property named `oneTimeScheduleDetailItemChange`. It seems the rule is only looking at the first two letters. It should really check the first three and see if the first two are "on" and the third is a capital letter.

I'm using codelyzer 4.0.2 with Angular 5.1.3.

**Comment by mgechev** [comment]
Good catch. Will add a fix in the next release.

**Comment by tatsujb** [comment]
I'm currently getting this but with "on"

**Comment by lazarljubenovic** [comment]
@tatsujb I'm not sure I understand you correctly but if you're getting an error with an output named something like "onClick", then that's the point of the rule: it should be just "click".

**Comment by tatsujb** [comment]
ok that's dumb. why can't it be "on" when that would allow you to match Angular's naming convention?

**Comment by lazarljubenovic** [comment]
It doesn't: https://angular.io/guide/styleguide#dont-prefix-output-properties

> Do name events without the prefix on.

**Comment by lazarljubenovic** [comment]
If you want to use the `on` prefix for some reason, simply turn off this lint rule. This one is specifically for forbidding the `on` prefix, as the name implies: _no output "on" prefix_.

**Comment by tatsujb** [comment]
Oh. my bad. so they bridge the "name-gap" html-side : 
`<toh-hero (savedTheDay)="onSavedTheDay($event)"></toh-hero>`

yeah that makes more sense, sorry.
