### ISSUE TITLE
Missing Style 01-01

### ISSUE THREAD

**Issue by roychoo** [mgechev/codelyzer#489]
Hi,

i was going through the angular styleguide and it recommend that we 
`Do define one thing, such as a service or component, per file.`

should we add `max-classes-per-file` rule under the https://github.com/mgechev/codelyzer#recommended-configuration ?

**Comment by wKoza** [comment]
Your remark is  interesting. Currently, we have a recommended configuration for our rules. `max-classes-per-file` is a tslint rule from `palentir`. @mgechev proposes a new project https://github.com/mgechev/tslint-angular. It's the good place for this rule.

**Comment by roychoo** [comment]
i agree, thanks for the suggestion, created a PR for this. https://github.com/mgechev/tslint-angular/pull/2

**Comment by wKoza** [comment]
No, tslint-angular should replace the ts-lint of Angular CLI .
