### ISSUE TITLE
Allow disabling of rules in templates and styles

### ISSUE THREAD

**Issue by alan-agius4** [mgechev/codelyzer#491]
At the moment if I add a rule example `trackBy-function` which validates html content there is no way to disable a rule for a specific file or line such as https://palantir.github.io/tslint/usage/rule-flags/

It would be nice to have this feature, in order to disable a rule where one doesn't want to emit a lint error.

**Comment by mgechev** [comment]
This could be caused by the rule naming. Did you try using both `/* tslint disable:trackBy-function */` and the lower case alternative?

**Comment by alan-agius4** [comment]
I can try again, but when I checked tslint was only looking for these in TS
files and not HTML files, causes it uses TypeScript to find comments and it
cannot read comments in Html files.

But surly I can try the lower case later and give you an update.

**Comment by mgechev** [comment]
@alan-agius4 yes, you should add this marker in the TypeScript file referencing your HTML template.

**Comment by alan-agius4** [comment]
That works fine thanks :) I'll happily do a PR. Maybe you can indicate in
which readme it should go?

**Comment by mgechev** [comment]
In the root of the project should be fine. Thanks!

**Comment by rgant** [comment]
It would be great if we could actually disable this rule for specific lines in the template file. I have a situation where some of my ngForOfs are just looping over strings and don't need template-use-track-by-function.

**Comment by antch** [comment]
> It would be great if we could actually disable this rule for specific lines in the template file. I have a situation where some of my ngForOfs are just looping over strings and don't need template-use-track-by-function.

Absolutely. I'm finding that I have to disable the rule altogether as around half of the usages in the codebase use strings/numbers, and if we have to disable the rule for an entire template there's really no point in trying to enforce it.
