### ISSUE TITLE
"extends": ["codelyzer"] is broken

### ISSUE THREAD

**Issue by scott-ho** [mgechev/codelyzer#505]
The docs stated in https://github.com/mgechev/codelyzer/tree/4.1.0#custom-installation is some how invalid now.

the published package(download from npm) does not have index.js as https://github.com/mgechev/codelyzer/blob/4.1.0/index.js, therefore, extends feature is broken

**Comment by mgechev** [comment]
@scott-ho thanks for pointing this out! Will fix it as part of the next release.

**Comment by mgechev** [comment]
This should fix the issue https://github.com/mgechev/codelyzer/pull/511/files
