### ISSUE TITLE
Using a deprecated API

### ISSUE THREAD

**Issue by NiKlimenko** [mgechev/codelyzer#507]
- codelyzer 4.1.0
- Angular 5.2.3
- TypeScript 2.7.1

Get the following warnings:
**WARNING: 47:41  deprecation  get is deprecated: from v4.0.0 use `Type<T> or InjectionToken<T>`
WARNING: 57:41  deprecation  get is deprecated: from v4.0.0 use `Type<T> or InjectionToken<T>`
WARNING: 73:41  deprecation  get is deprecated: from v4.0.0 use `Type<T> or InjectionToken<T>`
WARNING: 93:43  deprecation  get is deprecated: from v4.0.0 use `Type<T> or InjectionToken<T>`**

**Comment by wKoza** [comment]
When have your this error ?
What's your lint configuration (Codelyzer rules) ?

**Comment by NiKlimenko** [comment]
@wKoza during the run the angular-cli linting: `ng lint`.
tslint.json:
{
  "extends": ["tslint-angular", "tslint-no-unused-expression-chai"],
  "rules": {
    "directive-selector": [true, "attribute", "app", "camelCase"],
    "component-selector": [true, ["attribute", "element"], "app", ["kebab-case", "camelCase"]],
    "angular-whitespace": [true, "check-semicolon"]
  }
}

**Comment by NiKlimenko** [comment]
Just realized that it looks like my code causes these warnings, if so then feel free to close issue.
