### ISSUE TITLE
[Feature Request] Limiting template condition complexity

### ISSUE THREAD

**Issue by intellix** [mgechev/codelyzer#508]
We've got a payment process with conditions to reveal different steps of said process to push the user through it. An example of an *ngIf condition for revealing the Card entry step to the user: 

```html
<div *ngIf="step === 'amount' || (step === 'card' && transaction.action !== 'iframe-sent' && transaction.action !== 'html-provided' && transaction.action !== 'redirect-to-url')">
  Enter your card details
</div>
```

This amount of condition complexity is dangerous because it's breakage can only be detected via E2E or Manual QA. During refactor another developer can completely break payments.

I think one way Codelyzer can help here is allowing us to limit the complexity of an `*ngIf` condition allowed in the view. The above example would throw that it's too complex and the condition needs to be moved into the Component class, of which can be unit tested:

```ts
get canShowCardStep() {
  return this.step === 'amount' || (this.step === 'card' && this.transaction.action !== 'iframe-sent' && this.transaction.action !== 'html-provided' && this.transaction.action !== 'redirect-to-url;
}
```

```html
<div *ngIf="canShowCardStep">
  Enter your card details
</div>
```

**Comment by mgechev** [comment]
Love this feature request. Probably we can apply some version of cyclomatic complexity estimation.

**Comment by wKoza** [comment]
> Love this feature request

 I'm not surprised

**Comment by mgechev** [comment]
Here's a simple estimation of cyclomatic complexity implemented in go https://github.com/fzipp/gocyclo/blob/master/gocyclo.go. It should be easy to port it to the Angular expression/template ASTs.

**Comment by wKoza** [comment]
If we want to test boolean expression complexity, this implementation seems to be fine: https://github.com/maddingo/checkstyle/blob/master/src/checkstyle/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java

Its test: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java
