### ISSUE TITLE
Message for 'use-host-property-decorator' includes invalid link to Angular style docs

### ISSUE THREAD

**Issue by roddy** [mgechev/codelyzer#510]
The "use-host-property-decorator", as documented [here](http://codelyzer.com/rules/use-host-property-decorator/), displays the following warning message when triggered via TSLint:

> Use @HostBindings and @HostListeners instead of the host property (https://angular.io/styleguide#style-06-03)

The documentation is also wrong:
> Use @HostProperty decorator rather than the host property of @Component and @Directive metadata.
> 
> See more at https://angular.io/styleguide#style-06-03.

The URL is wrong and leads to an error/404 page. The correct URL is https://angular.io/guide/styleguide#style-06-03

Observed on:
* Angular 5.2.2
* Codelyzer 4.1.0
* TSLint 5.9.1

Code to reproduce / trigger this warning:

```
@Component({
  selector: 'app-test',
  template: `<p>Hello!</p>`,
  styles: [`p{display:block;}`],
  host: {
    "class": "example",
  }
})
export class TestComponent {
  constructor() {}
}
```

**Comment by mgechev** [comment]
Thanks for sharing this! I'll talk to the docs team.

**Comment by mgechev** [comment]
https://github.com/angular/angular/issues/22078 will resolve it.
