### ISSUE TITLE
`use-view-encapsulation` only accepts a boolean

### ISSUE THREAD

**Issue by alan-agius4** [mgechev/codelyzer#517]
Using `encapsulation` other than `ViewEncapsulation.None` can be problematic in case you are building an atomic component library similar to `Material` As in some cases you'd want to allow the consumers to override it without using `/deep/`

Thus in my case I want to enforce the use of `ViewEncapsulation.None`

I'd see the usage like 
```json
{
"use-view-encapsulation":  [
  true,
 "\\.None$",
]
}
```

**Comment by mgechev** [comment]
Codelyzer enforces view encapsulation. Allowing `None` is possible if you disable the rule. Let's keep this outside codelyzer for now.
