### ISSUE TITLE
Export error in json or xml

### ISSUE THREAD

**Issue by olivierscheffler** [mgechev/codelyzer#518]
Hi !

For statistic purpose, I would like to have an export in json or xml of the lint error for making graph and being able to track down evolution.
Do you know if there's any solution already working or if codelyzer can do that ?

Thank you for your help !

**Comment by mgechev** [comment]
Hey @olivierscheffler you should be able to do this with a custom tslint reporter. See https://palantir.github.io/tslint/formatters/json/.
