### ISSUE TITLE
Why is the pipe-naming rule deprecated?

### ISSUE THREAD

**Issue by yannickglt** [mgechev/codelyzer#519]
Hey!
Sorry to create an issue to ask such a question but I could not find any answer on the repo or in the doc.
I saw that the `pipe-naming` rule was deprecated in the Readme. Could you tell me what's the reason and if it was replaced with another rule?
Thanks

**Comment by mgechev** [comment]
You can name your pipes only camel case if you try to use snake-case then your application will not compile. This is a compile-time error, not a linting one. The alternative is to use AoT.

**Comment by yannickglt** [comment]
Thanks for your quick answer!

Good to learn that there's a compile error now. 

I mainly wanted to know if the practices about prefixing pipes have changed. If it is not a good practice anymore then I guess the rule is not useful anymore.

**Comment by mgechev** [comment]
It's still considered a good practice. Prefixing will not be caught by the compiler thought.

**Comment by yannickglt** [comment]
Great. Thank you!

**Comment by emilio-martinez** [comment]
@mgechev is there a replacement for checking that the Pipe names are prefixed accordingly?

```
"pipe-naming": [true, "camelCase", "app"]
                                     ^
```

**Comment by georgms** [comment]
Sorry for resurrecting this but I can still do:

```typescript
@Pipe({ name: 'underscore_name' })
export class UnderscoreNamePipe implements PipeTransform {}
```

But according to the Angular style guide [pipe name strings should use *lowerCamelCase*](https://angular.io/guide/styleguide#pipe-names), ie. `@Pipe({ name: 'underscoreName' })`.

How can I enforce *lowerCamelCase* for pipe names?

**Comment by mgechev** [comment]
I'd recommend opening an issue in [angular-eslint](https://github.com/angular-eslint/angular-eslint). Codelyzer is now deprecated.
