### ISSUE TITLE
Angular 5.X peer dependencies

### ISSUE THREAD

**Issue by AdamKernig** [mgechev/codelyzer#520]
Standard NG CLI 5.x project,

Npm install gives me:
codelyzer@2.1.1 requires a peer of tslint@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@2.1.1 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@2.1.1 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.

Currently on  "codelyzer": "^4.1.0",

Can anyone please advise?

**Comment by dsmclaughlin** [comment]
I'm also seeing this issue.

**Comment by mgechev** [comment]
Thanks! I will make a new release today.

**Comment by mgechev** [comment]
@AdamKernig your log says `codelyzer@2.1.1`. The peer dependencies of the current release look fine:

```
"peerDependencies": {
  "@angular/compiler": "^2.3.1 || >=4.0.0-beta <6.0.0",
  "@angular/core": "^2.3.1 || >=4.0.0-beta <6.0.0",
  "@angular/platform-browser-dynamic": "^2.3.1 || >=4.0.0-beta <6.0.0",
  "@angular/platform-browser": "^2.3.1 || >=4.0.0-beta <6.0.0",
  "@angular/common": "^2.3.1 || >=4.0.0-beta <6.0.0",
  "tslint": "^5.0.0"
}
```

Verify that codelyzer is not installed as a transitive dependency.

**Comment by AdamKernig** [comment]
You have closed the ticket without problem resolution can you ezplain what
a teansiticie is?

**Comment by wKoza** [comment]
Your codelyzer's version should be 2.1.1, not 4.1.0. Maybe do you have a npm package that depends on Codelyzer 2.1.1. Check your npm package.

**Comment by pasame-el-codigo** [comment]
@AdamKernig did you have a solution??
