### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sreeramachandramurthy** [mgechev/codelyzer#521]
Getting the below error while trying to run `tslint --project tslint.json`
The linting fails and no issues are being reported for any typescript file.

`
D:\android>tslint --project tslint.json
C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\runner.js:118
            throw error;
            ^

TypeError: Cannot read property '0' of undefined
    at Rule.SelectorRule [as constructor] (D:\android\node_modules\codelyzer\selectorNameB
ase.js:23:24)
    at new Rule (D:\android\node_modules\codelyzer\directiveSelectorRule.js:18:47)
    at Object.loadRules (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\ruleLoader.js:47:36)
    at Linter.getEnabledRules (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\linter.js:168:44)
    at Linter.lint (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\linter.js:81:33)
    at Runner.processFiles (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\runner.js:161:20)
    at Runner.run (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\runner.js:110:18)
    at Object.<anonymous> (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\tslint-cli.js:139:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
`

- tslint Version: 4.5.1
- typescript Version: 2.6.2
- codelyzer Version: 4.1.0

Steps to Reproduce:

1. Open terminal
2. cd D:\android
3. tslint --project tslint.json

**Comment by sreeramachandramurthy** [comment]
More Info

tslint.json

`
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
    "class-name": true,
    "comment-format": [
      true,
      "check-space"
    ],
    "curly": true,
    "eofline": true,
    "forin": true,
    "indent": [
      true,
      "spaces"
    ],
    "label-position": true,
    "max-line-length": [
      true,
      140
    ],
    "member-access": false,
    "member-ordering": [
      true,
      "static-before-instance",
      "variables-before-functions"
    ],
    "no-arg": true,
    "no-bitwise": true,
    "no-console": [
      true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-construct": true,
    "no-debugger": true,
    "no-duplicate-variable": true,
    "no-empty": false,
    "no-eval": true,
    "no-inferrable-types": true,
    "no-shadowed-variable": true,
    "no-string-literal": false,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unused-expression": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "object-literal-sort-keys": false,
    "one-line": [
      true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-whitespace"
    ],
    "quotemark": [
      true,
      "single"
    ],
    "radix": true,
    "semicolon": [
      "always"
    ],
    "triple-equals": [
      true,
      "allow-null-check"
    ],
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      }
    ],
    "variable-name": false,
    "whitespace": [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator",
      "check-type"
    ],
    "directive-selector": [true, "attribute", "app", "camelCase"],
    "component-selector": [true, "element", "app", "kebab-case"],
    "use-input-property-decorator": true,
    "use-output-property-decorator": true,
    "use-host-property-decorator": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "use-life-cycle-interface": true,
    "use-pipe-transform-interface": true,
    "component-class-suffix": true,
    "directive-class-suffix": true,
    "no-access-missing-member": true,
    "templates-use-public": true,
    "invoke-injectable": true
  }
}
`

package.json
`
{
  "name": "android",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "5.2.5",
    "@angular/cdk": "^5.2.1",
    "@angular/common": "5.2.5",
    "@angular/compiler": "5.2.5",
    "@angular/core": "5.2.5",
    "@angular/forms": "5.2.5",
    "@angular/http": "5.2.5",
    "@angular/material": "^5.2.1",
    "@angular/platform-browser": "5.2.5",
    "@angular/platform-browser-dynamic": "5.2.5",
    "@angular/router": "5.2.5",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.0",
    "@angular/compiler-cli": "5.2.5",
    "@types/jasmine": "2.8.6",
    "@types/node": "9.4.6",
    "codelyzer": "4.1.0",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "0.6.0",
    "protractor": "5.3.0",
    "ts-node": "4.1.0",
    "tslint": "5.9.1",
    "typescript": "2.6"
  }
}
`

**Comment by wKoza** [comment]
Hi,
You should use this command:
```
tslint --project tsconfig.json -c tslint.json
```

**Comment by sreeramachandramurthy** [comment]
Not working!
Tried again on a fresh project starting from scratch

Steps to Reproduce
1. Open terminal
2. `ng new trial`
`
Installed packages for tooling via npm.
`
`
Project 'trial' successfully created.
`
3. `cd trial`
4. `tslint --project tsconfig.json -c tslint.json`
`
C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\runner.js:118
            throw error;
            ^
TypeError: Cannot read property '0' of undefined
    at Rule.SelectorRule [as constructor] (D:\trial\node_modules\codelyzer\selectorNameBa
se.js:23:24)
    at new Rule (D:\trial\node_modules\codelyzer\directiveSelectorRule.js:18:47)
    at Object.loadRules (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\ruleLoader.js:47:36)
    at Linter.getEnabledRules (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\linter.js:168:44)
    at Linter.lint (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\linter.js:81:33)
    at Runner.processFiles (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\runner.js:161:20)
    at Runner.run (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\runner.js:110:18)
    at Object.<anonymous> (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\tslint\lib\tslint-cli.js:139:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
`

package.json
`
{
  "name": "trial",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.8",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
`
