### ISSUE TITLE
changelog to be updated for 4.2.1

### ISSUE THREAD

**Issue by akkumar** [mgechev/codelyzer#527]
npm shows codelyzer to be 4.2.1 but changelog does not reflect the changes since 4.1.0 and nor does the "releases" under github . 

It would be useful to get the changelog be updated to get a sense of what has changed since 4.1.0 .  Thanks in advance.

**Comment by wKoza** [comment]
/cc @mgechev 

we should also think about modifying the readme (with the new rules)

**Comment by mgechev** [comment]
There was an emergency and I had to push a new release yesterday. Will add details in the change log over the weekend.

**Comment by mgechev** [comment]
https://github.com/mgechev/codelyzer/blob/master/CHANGELOG.md
