### ISSUE TITLE
Check that component doesn't have @Outputs that conflict with standards events

### ISSUE THREAD

**Issue by sokolovstas** [mgechev/codelyzer#535]
For now if we have `@Output click:EventEmitter` in component and bind like this `(click)="test()"` handler was called for standard click event. Maybe codelyzer need to check that we use standard event name in `@Output`?

I have found this so far `'wheel'
'touchmove'
'paste'
'focusin'
'focus'
'blur'
'keydown'
'mousedown'
'mousemove'
'mouseover'
'mouseout'
'mouseenter'
'mouseleave'
'scroll'
'click'
'dblclick'
'change'
'error'
'load'
'keyup'
'keydown'`

**Comment by ngiebel** [comment]
See the rule [no-output-named-after-standard-event](http://codelyzer.com/rules/no-output-named-after-standard-event/)

**Comment by sokolovstas** [comment]
Thanks!

**Comment by sokolovstas** [comment]
Short question: is there are rule to check that event in templates exist in component `@Output`?

```
@Component({
  selector: 'sg-hero-cmp',
  template: '<h1>Hello <span [ERROR]->(myEvent)="myEv()"></span></h1>',
  ]
})
class HeroComponent {
  private hero: Hero;
	myEv() {
    }
}
```

I have found that this check is disabled on angular compiler, and used only when template is included in .ts file. I have try to restore it, but compiler couldn't find standard events like `(click)`
