### ISSUE TITLE
[Feature Request] max-inline-template-lines and min-template-lines

### ISSUE THREAD

**Issue by listepo-alterpost** [mgechev/codelyzer#536]
- min-template-lines - the minimum number of lines that is allowed in `templateUrl` file, otherwise recommend using `template` string;
- max-inline-template-lines - the maximum number of lines that is allowed in `template` string, otherwise recommend using `templateUrl` file;

**Comment by mgechev** [comment]
It's a good issue for newcomers.

**Comment by mgechev** [comment]
https://github.com/mgechev/codelyzer/commit/174ed46f11dddd2837559163d6475e00cef8be84

**Comment by rafaelss95** [comment]
@mgechev I just noticed that `min-lines templates/styles` weren't handled on that PR. Does it makes sense to implement this?

**Comment by mgechev** [comment]
Please do
