### ISSUE TITLE
Custom prefix error being confused for kebab-case error

### ISSUE THREAD

**Issue by mpetkov** [mgechev/codelyzer#54]
Latest update of this library is confusing the following 2 rules:
- Custom Prefix for Components (Style 02-07)
- Components Selector Naming (Style 05-02)

So if you have a selector **app**, the error you get is the the kebab-case (05-02) error instead of the custom prefix error.  Could it be updated so that kebab-case is proper checking where app would not fail?  That way if a user would want to turn off the custom prefix rule but keep the kebab case rule, they could.

**Comment by mgechev** [comment]
This PR is related to the issue https://github.com/mgechev/codelyzer/pull/50.

**Comment by mgechev** [comment]
Lets track the selectors validation progress here https://github.com/mgechev/codelyzer/issues/15.
