### ISSUE TITLE
Component Selector Suffix

### ISSUE THREAD

**Issue by sam-s4s** [mgechev/codelyzer#544]
There is a rule "component-class-suffix", and in that you can specify a custom list of allowed suffixes (by default "Component" only). This is great, as I'm also using the suffix "Page" for a sub-type of components.

The problem is that I can't find any matching functionality for the selector. There is a rule "component-selector", but it does not seem to give me the option to specify a custom list of allowed suffixes (by default "Component only), just as the "component-class-suffix" rule does.

This would be a great feature to have, as currently I have to disable the "component-selector" rule completely, which makes me sad :P

**Comment by wKoza** [comment]
Why do you need to disable the `component-selector` rule ? This rule enforces a prefix. You can use all suffixes that you want.

**Comment by sam-s4s** [comment]
Yes, it enforces a prefix, buy only in the case of there being no "component" suffix.

I don't want a prefix.

But I do want to be able to provide an alternate list of suffixes (not just "component").

I hope that makes sense :)

**Comment by wKoza** [comment]
You have this error because you have defined `app` as prefix:

```
"component-selector": [true, "element", "app", "kebab-case"]`
```

**Comment by sam-s4s** [comment]
Wait... you're saying that it expects me to put the prefix "app" in front of every component in my entire app? And that's Angular CLI's default setting? That is terrible lol

**Comment by lazarljubenovic** [comment]
@sam-s4s It's far from terrible. It ensures two things, apart from consistency:

- namespacing your components meaning less chances for a clash with another library;
- a dash in the selector, even when your component is a single word.

**Comment by sam-s4s** [comment]
Yeah, I guess it's a good idea from that perspective... But it seems a little unrealistic for real-world large-scale usage...

ie. our app has over 160 components already, some with selectors over 40 characters (adding more verbosity would be annoying).

Back when we started development, that pattern didn't really exist.

Anyway, I can just disable that rule now I know what's going on.

Thanks!
