### ISSUE TITLE
Rule `contextual-life-cycle` too aggressively scoped

### ISSUE THREAD

**Issue by ngiebel** [mgechev/codelyzer#545]
When turning on the rule `contextual-life-cycle`, if an `@Injectable` is defined before a component/directive using lifecycle hooks the rule incorrectly flags a violation. Sample below as an adaptation of the main codelyzer demo, but it seems the demo does not have the rule activated.

```TypeScript
@Injectable()
class Sample {
  public constructor() { }
}

@Component({
  selector: 'sg-hero-cmp',
  template: `
    <h1>Hello <span>{{ hero.name }}</span></h1>
  `,
  providers: [Sample]
})
class HeroComponent implements OnInit {
  public hero: Hero;

  public constructor(private sample: Sample) { }

  ngOnInit() {
    console.log('Initialized');
  }
}
```

**Comment by mgechev** [comment]
Thanks for reporting this issue! It should be fixed in the next released.
