### ISSUE TITLE
[Feature Request] Enforce single line @Input decorator

### ISSUE THREAD

**Issue by haubbixa** [mgechev/codelyzer#549]
I'd like to have a rule to enforce the recommendation of 'Consider placing @Input() or @Output() on the same line as the property it decorates.' described in Style 05-12.  As far as I can tell use-input-property-decorator only enforces the usage of @Input not the styling

**Comment by mgechev** [comment]
Yes, correct. This is a good suggestion. Will add it to the roadmap.

**Comment by rafaelss95** [comment]
What should happen for the following case?

```
@Input()
get text(): string {
  return 'hey'
}
set text(value: string) {
  this._text = value;
}
private _value: string;
```

**Comment by mgechev** [comment]
@rafaelss95 it's a good corner case that you caught! My suggestion would be to ignore the rule in case the input is applied to a setter.

**Comment by rafaelss95** [comment]
@mgechev I'd like to implement this (I've already started). I think we can use more generic approach, to enforce single line for `Output`, `ContentChild`, `ViewChild`... and so on. What do you think?
