### ISSUE TITLE
import-destructuring-spacing with alias imports

### ISSUE THREAD

**Issue by cexbrayat** [mgechev/codelyzer#55]
I was giving a try to the new `import-destructuring-spacing` rule, and it breaks in our codebase on imports that use an alias:

    import * as moment from 'moment';

produces `You need to leave whitespaces inside of the import statement's curly braces`.

It would be better if that was ignored (but perhaps I'm missing something).

**Comment by mgechev** [comment]
It is fixed in 0.0.23.

**Comment by spzSource** [comment]
Hi
Still have this issue on 0.0.28
