### ISSUE TITLE
Importing SCSS/CSS into multiple components

### ISSUE THREAD

**Issue by intellix** [mgechev/codelyzer#553]
I'm performing a refactor of HTML, SCSS and removing stuff that's unused. Typically with a CLI application you have a structure like:
```
/account
  account.module.ts
  account.component.ts
  account.component.html
  account.component.scss

  /activity
    activity.component.ts
    activity.component.html
    activity.component.scss

  /sessions
    sessions.component.ts
    sessions.component.html
    sessions.component.scss
```

I'm looking inside account SCSS and notice quite a few styles referencing HTML that doesn't exist within it's HTML counterpart and remove them. 

Realised that activity and sessions broke because they were importing **account.component.scss** (likely due to someone not understanding ViewEncapsulation and getting frustrated about sharing).

I think importing other component SCSS is dangerous due to the reason we have ViewEncapsulation, that you break other components without realising it.

**Comment by mgechev** [comment]
Yes, the rule which detects dead CSS is experimental. The two main limitations it has you already listed - it doesn't consider `ViewEncapsulation` and shared styles.

I'll close this issue because we've already marked it as not production ready in the readme.

**Comment by mgechev** [comment]
Sorry, misread the issue. Would you share more details on the functionality you're looking for?

**Comment by intellix** [comment]
That other components can't re-use the SCSS of another component

```ts
@Component({
  selector: 'xc-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.scss'],
})
export class AccountComponent { ... }

@Component({
  selector: 'xc-activity',
  templateUrl: './activity.component.html',
  styleUrls: ['../account.component.scss'],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
})
export class ActivityComponent { ... }
```

**Comment by wKoza** [comment]
@intellix , can you confirm the supposition of @mgechev ?

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
