### ISSUE TITLE
add new rule to enforce the use of providedIn flag

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#558]
This is recognized as best practice for providers with Angular 6 (we can now perform tree shaking and remove services that aren't used by your app

**Comment by rafaelss95** [comment]
Related to #135. Btw, any news on integrate material2#validateDecoratorsRule here?

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by mohammedzamakhan** [comment]
You can assign it to me

**Comment by mgechev** [comment]
GitHub does not allow this but since you're taking it I'll drop `votes needed`.

**Comment by rafaelss95** [comment]
@mgechev @wKoza 
Currently we have the following rules to (dis)allow decorator properties values:

| List of rules |
|:-:|
| `no-host-metadata-property`                                 |
| `no-inputs-metadata-property`                              |
| `no-outputs-metadata-property`                            |
| `no-queries-metadata-property`                            |
| `no-pipe-impure`                                                      |
| `prefer-on-push-component-change-detection`  |
| `use-component-selector`                                       |
| `use-component-view-encapsulation`                    |

... and this list is growing...

What's your opinion about implement something like [**`material2#validateDecoratorsRule`**](https://github.com/angular/material2/blob/master/tools/tslint-rules/validateDecoratorsRule.ts) (it was already mentioned in this and other issues like https://github.com/mgechev/codelyzer/issues/135)?

A default config would be:

```JSON
{
  "rules": {
    "validate-decorators": [
      true, {
        "Component": {
          "changeDetection": "\\.OnPush$",
          "!encapsulation": "\\.None$",
          "!host": ".*",
          "!inputs": ".*",
          "!outputs": ".*",
          "!queries": ".*",
          "selector": ".*"
        },
        "Directive": {
          "selector": ".*"
        },
        "Pipe": {
          "!pure": ".*"
        }
      }
    ]
  }
}
```

... and of course we could allow users to customize it according to their project standards, and why not also their decorators.

**Comment by mgechev** [comment]
Sounds good. I can talk to @jelbourn to converge both rules.

**Comment by jscharett** [comment]
Does this rule allow for a non-singleton services?  I haven't seen an example where provideIn is used for a component, only root/Modules.
