### ISSUE TITLE
directive-selector-name rule gives error for "[validateEmail][ngControl],[validateEmail][ngModel],[validateEmail][ngFormControl]" syntax

### ISSUE THREAD

**Issue by rushi216** [mgechev/codelyzer#56]
I have custom email validator like below

```
@Directive({`
    selector: '[validateEmail][ngControl],[validateEmail][ngModel],[validateEmail][ngFormControl]',
    providers: [
        provide(NG_VALIDATORS, {
            useClass: EmailValidatorDirective, multi: true             
        })
    ]
})
```

but it gives 

> The selector of the directive "EmailValidatorDirective" should be named camelCase (https://goo.gl/rdGf2b)

even it is in camel case

**Comment by mgechev** [comment]
This is a known issue, already reported here https://github.com/mgechev/codelyzer/issues/15.
