### ISSUE TITLE
Prevent to implement OnChanges and DoCheck on the same class

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#560]
According to [DoCheck#description](https://angular.io/api/core/DoCheck#description):

> Note that a directive typically should not use both DoCheck and OnChanges to respond to changes on the same input, as ngOnChanges will continue to be called when the default change detector detects changes.

I thought it was a good idea to add a rule to prevent this.

**Comment by wKoza** [comment]
It makes sense. :+1:

**Comment by rafaelss95** [comment]
@wKoza Do you have any name in mind for this rule?

**Comment by mgechev** [comment]
`no-conflicting-life-cycle-hooks`?

**Comment by rafaelss95** [comment]
I like this name. I'm implementing it right now. Do you think this rule needs to be made in a generic way to provide flexibility or only for `DoCheck` and `OnChanges` hooks?

**Comment by kylekatarnls** [comment]
My 2 cents, an important part of this quote is "on the same input"

Using OnChanges and DoCheck to respond to independent changes is a relevant usage.
