### ISSUE TITLE
Disallow accessing "decorated" properties before its initialization

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#562]
- `@Input`;
- `@ContentChild / @ContentChildren`;
- `@ViewChild / @ViewChildren`;

Ex.:

```
@Component...
@Input() x: string;
@ViewChild('var') var;

constructor() {
  console.log(this.x); // undefined
}

ngOnInit() {
  console.log(this.var); // undefined
}
```

**Comment by wKoza** [comment]
It's an interesting feature @rafaelss95 !

**Comment by rafaelss95** [comment]
Do you have any idea in mind to this rule?

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
