### ISSUE TITLE
[Feature request] - Generic rule to enforce prefixes/suffixes

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#567]
Currently we have rules to enforce `component` and `directive` suffixes, but Angular style guide have more rules for the other suffixes:

- [`Service` for injectables](https://angular.io/guide/styleguide#service-names);
- [`Module` for modules](https://angular.io/guide/styleguide#angular-ngmodule-names);
- [`Pipe` for pipes](https://angular.io/guide/styleguide#pipe-names);
- [`RoutingModule` for routing modules](https://angular.io/guide/styleguide#angular-ngmodule-names); (not sure how to detect this isn't a "common" module);

So I thought it's a good idea either to create a rule for everyone (IMHO not the best solution) or to create a generic rule in order to cover all cases.

<hr>

A configuration schema would be:

```JSON
{
  "type": "object",
  "properties": {
    "prefix": {
      "type": "string"
    },    
    "suffix": {
      "type": "string"
    }
  }
}
```
<hr>

A standard config based on Angular style guide could be:
`"naming-convention": [true]`

A sample of custom configuration could be:

```JSON
"naming-convention": [
  true,
  { "type": "Component", "prefix": "MyPrefixLibName", "suffix": "Component" },
  { "type": "Directive", "prefix": "MyPrefixLibName", "suffix": "Directive" },
  { "type": "Injectable", "prefix": "MyPrefixLibName", "suffix": "Service" },
  { "type": "Module", "prefix": "MyPrefixLibName", "suffix": "Module" },
  { "type": "Pipe", "prefix": "MyPrefixLibName", "suffix": "Pipe" },
  { "type": "RoutingModule", "MyPrefixLibName": "Any", "suffix": "RoutingModule" }
]
```

... or

```JSON
"naming-convention": [
  true,
  "Component": {
    "prefix": "MyPrefixLibName", "suffix": "Component"
  },
  "Directive": {
    "prefix": "MyPrefixLibName", "suffix": "Directive"
  },
  "Injectable": {
    "prefix": "MyPrefixLibName", "suffix": "Service"
  },
  "Module": {
    "prefix": "MyPrefixLibName", "suffix": "Module"
  },
  "Pipe": {
    "prefix": "MyPrefixLibName", "suffix": "Pipe"
  },
  "RoutingModule": {
    "prefix": "MyPrefixLibName", "suffix": "RoutingModule"
  }
]
```

<hr>

**Questions**:

* Would it be weird if we have an generic prefix to avoid always type `MyPrefixLibName` for every member (note that this could be useful if people want to enforce `Interface`s or simple `Class`es to have a prefix)? Something like:
  * `"class": { prefix: "MyPrefixLibName" }`
* Could prefix option accept an `array`?
* Could suffix option accept an `array`?
* If no suffix is specified it must use the defaults (according to Style guide) or no suffix at all?

<hr>

This is based on https://github.com/ajafff/tslint-consistent-codestyle/blob/master/docs/naming-convention.md#examples

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
