### ISSUE TITLE
[max-inline-declarations] - Add option for animations

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#568]
Although not mentioned in the Angular style guide (maybe because it's a really new thing), I think it makes sense to warn in `max-inline-declarations` rule if the `animations` declaration is _too_ large as well as `template` and `styles`.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
