### ISSUE TITLE
Upgrade TypeScript dependency to 2.7.2

### ISSUE THREAD

**Issue by mertdeg2** [mgechev/codelyzer#583]
https://github.com/mgechev/codelyzer/blob/4.3.0/package.json#L69

We couldn't use codelyzer because its pinning TS 2.4

**Comment by mgechev** [comment]
I'll take a look at this today.

**Comment by mertdeg2** [comment]
Sounds good. Thanks Minko! Let me know if i can help.

**Comment by mgechev** [comment]
@mertdeg2 would you try the branch `minko/dev-typescript`. It should work properly with the latest TypeScript.

**Comment by mgechev** [comment]
@mertdeg2 I added the return type to `noTemplateCallExpressionRule`. Let me know if the build still fails.

**Comment by mertdeg2** [comment]
Nope, this works. Thanks! :)
