### ISSUE TITLE
[Feature request] - use output for EventEmitter

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#591]
It'd be great to check if an `EventEmitter` is decorated with `@Output`.

If you simply forgot to decorate it (something like `fakeOutput = new EventEmitter<void>();`) it'll fail silently and you may waste some time to find this mistake.

An use case:

```
@Component({
  selector: 'app-root',
  template: '<app-child (fakeOutput)="fakeOutput()"></app-child>'
})
export class ParentComponent  {
  fakeOutput() {
    console.log('fakeOutput');
  }
}

@Component({
  selector: 'app-child',
  template: `
    <button type="button" (click)="fakeOutput.emit()">
      Fake output
    </button>
  `
})

export class ChildComponent  {
  fakeOutput = new EventEmitter<void>();
}
```

[DEMO](https://stackblitz.com/edit/angular-gitter-kcgkhd)

<hr>

Not sure if here is the best place, because for `@Input`'s, `@angular`, throws an error (not really friendly, but works) stating something like "the property XXX isn't recognized as an `Input`".

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
