### ISSUE TITLE
About use-pipe-decorator

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#592]
The rule `usePipeDecorator` seems to be unnecessary now, because once you try to put any class without any valid decorators (`Component`, `Directive` or even `Pipe` decorator) in `@NgModule`'s declarations it throws an error:

> Unexpected value 'XXXPipe' declared by the module 'XXXModule'. Please add a @Pipe/@Directive/@\Component annotation.

**Comment by mgechev** [comment]
Let's keep it for now until Ivy gets released.

**Comment by mgechev** [comment]
@rafaelss95 love your suggestion btw, I definitely agree. I closed the issue because of the plans for the locality of the compiler.

**Comment by rafaelss95** [comment]
@mgechev I just missed this discussion... now that `Ivy` is closer, what's your opinion for this rule?

**Comment by mgechev** [comment]
Would you see how `ngtsc` handles this? If it still throws, let us deprecate.
