### ISSUE TITLE
About prefixes rules

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#594]
In theory, `prefix` is a word, letter, or number placed before another, however I noticed that there's a test case in `noOutputOnPrefix`:

https://github.com/mgechev/codelyzer/blob/651be15e7a5e0ce047b1ab0be5a90b51a3adb4aa/test/noOutputOnPrefixRule.spec.ts#L35-L47

... where it implies that we can't name a variable `on`. Is it really the expected behavior? For me, it's a little strange because there's nothing after `on` word.

Anyway, I'm asking because actually `noInputPrefix` works a little bit different. In which rule should go a fix?

**Comment by mgechev** [comment]
To me, it sounds fine to disallow `on` as the name of an output. Let's reopen this if anyone disagrees.
