### ISSUE TITLE
[Feature request] - check unused properties in class declaration

### ISSUE THREAD

**Issue by Teamop** [mgechev/codelyzer#596]
Right now, there's an edge case that doesn't covered by tslint, codelyzer and language service.
The demo is easy, just use http://codelyzer.com/, then just add `a: string;` in the component, like this:
![image](https://user-images.githubusercontent.com/8519685/39522554-2b056d80-4e45-11e8-8166-d91f6715bfba.png)
Here, no error, no warning.

For TSLint, [only complains about unused private properties](https://github.com/palantir/tslint/issues/3317), but for angular template usage, the properties must be public for AOT.

There was a similar but opposite rule `no-access-missing-member` which has been removed for language service, so I'm not sure whether I should submit this issue here or in the language service.

**Comment by mgechev** [comment]
@Teamop the feature request is to detect properties which are not later read?

**Comment by Teamop** [comment]
@mgechev yes, just declare but don't use.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by rafaelss95** [comment]
@mgechev Do you have any idea on how to start the implementation for this rule?

**Comment by mgechev** [comment]
Not sure if it's possible to solve this in the general case.

The property can be accessed from outside of the component.

**Comment by wKoza** [comment]
yes, and we have had lot of problem with inheritance...

**Comment by buu700** [comment]
My request (#810) was pretty much the same as this, with the addition that it should flag methods that aren't referenced in the template, not just class variables.

Also, an additional consideration comes to mind: in the case of both variables and methods, I think we should overlook anything specified by an implemented interface by default. e.g. no need to complain that `ngOnInit` is never called, because we can see that it's required by `OnInit`.

**Comment by buu700** [comment]
> The property can be accessed from outside of the component.

I don't know whether you'd consider this an acceptable solution, but this was my suggestion in the other ticket:

> There are certainly some edge cases where a public member might be needed without having been referenced in the template, but I think these would be the vast minority of cases, and so would be fine for most projects to just comment with one-off lint exceptions.
