### ISSUE TITLE
Request - Component restrictions

### ISSUE THREAD

**Issue by dev054** [mgechev/codelyzer#598]
Could we have a rule to disallow the following situations?

```ts
@Component({
  interpolation: ['((', '))'], // Should report to not override the default interpolation
  moduleId: module.id // Should report to not use `moduleId` anymore
})
....
```

Another situation is when you have by mistaken this code:

```ts
@Component({
  template: `<div>I'm failing</div>`, // wrong
  selector: 'app-something',
  stlyeUrls: ['./path/to/file'],
  inputs: [...],
  outputs: [...],
  encapsulation: ViewEncapsulation.None,
  templateUrl: './path/to/file'
})
....
```

It should report a failure because you have both attributes: `template` and `templateUrl` in the same definition and Angular will only recognize the last attribute, in this case, `templateUrl`. The same happens for `styles` and `styleUrls`.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
