### ISSUE TITLE
Request - Enforce pipe names

### ISSUE THREAD

**Issue by dev054** [mgechev/codelyzer#599]
There's one rule to enforce component selectors, could we have one for `pipe` names?

```ts
@Pipe({
  name: '' // should report
  name: null // should report
})

**Comment by mgechev** [comment]
`name: null` should be a compile-time error. The name is not nullable, no?

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by dev054** [comment]
Unfortunately not, it compiles [here](https://stackblitz.com/edit/angular-gitter-ttdpfz). The maximum we can get now is a warning from the deprecated `pipe-naming` rule if the value is **undefined** (not null or empty):

> [tslint] The name of the Pipe decorator of class Test should be named camelCase with prefix fo,mg,sg, however its value is "undefined". (pipe-naming)

Interestingly, Angular throws an compile-time error for `@Directive`:

> Error: Directive Test has no selector, please add it!

... when your `selector` is equal to `null`, `undefined` or `empty`.

**Comment by mgechev** [comment]
@dev054 `name` is [not nullable](https://github.com/angular/angular/blob/master/packages/core/src/metadata/directives.ts#L793). With stricter type checking this should not be a semantically valid program.

**Comment by dev054** [comment]
Hmm, yes. While I agree that enable `strict` makes it more easier to find errors, not all projects use it. Also, it doesn't prevent `''`.

**Comment by lazarljubenovic** [comment]
I think prevent anything that leads to `name.trim() == ''` should be handled by Angular. I don't think it's linter's responsibility to ensure that you can use the pipe you've created. It's a direct Angular problem.
