### ISSUE TITLE
useLifeCycleInterfaceRule failing with a Symbol.iterator

### ISSUE THREAD

**Issue by Foxandxss** [mgechev/codelyzer#60]
Having this class:

```
export class Heroes implements Iterable<Hero> {
  ...

  [Symbol.iterator]() {
    return this.currentHeroes.values();
  }

  ...
}
```

I get this error:

`TypeError: Cannot read property 'substr' of undefined` at `useLifeCycleInterfaceRule.js:58:44`

Is not the interface itself, is the Symbol.iterator.

**Comment by preslavsh** [comment]
#65  Fixes it.
