### ISSUE TITLE
Request - Http only in services

### ISSUE THREAD

**Issue by dev054** [mgechev/codelyzer#601]
According to https://angular.io/guide/styleguide#style-08-01, we should "Do refactor logic for making data operations and interacting with data to a service.". Is it possible to prevent http directly calls in other places that `@Injectable` ones?

**Comment by mgechev** [comment]
That's a pretty good suggestion.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
