### ISSUE TITLE
Whitespace rules in angular templates

### ISSUE THREAD

**Issue by jaufgang** [mgechev/codelyzer#619]
the [TSLint `Whitespace` rule](https://palantir.github.io/tslint/rules/whitespace/) can check for whitespace around operators, for example 

```ts

if(foo===bar){return}  // TSLint missing whitespace error
const x=a?b:c;   //multiple TSLint missing whitespace errors

if(foo === bar){return} //no TSLint error
const x = a ? b : c; //no TSLint error

```
However, the codelyzer `angular-whitespace` rule does not catch this

```html
<button *ngIf="foo===bar"
	[disabled]="checkCount()===0">
</button>  <!-- no TSLint error-->
```

Is there a way to catch this?  Could the `angular-whitespace` rule be configured to piggyback off the `whitespace` rule, and enforce the same config options for code in angular templates as  are used for the `whitespace` rule if it is configured?

**Comment by rafaelss95** [comment]
Some people, such as Material2 team, doesn't like whitespaces between the interpolations), so it could be another improvement: add some configuration like `never`, so that would validate it to have no spaces.

**Comment by jaufgang** [comment]
Another example of where whitespace rule could be enforced: 
```html
<div [ngClass]="{foo:item.isFoo}"> <!-- should have space after colon -->
```

**Comment by rafaelss95** [comment]
Thinking more about it... do we really want to messing with formatting rules in a linter? Well, while I can imagine how this rule could be useful in many cases, I really think it's more appropriated to left this kind of rule to a formatter, like `Prettier`*, for example.

IMHO, this project shouldn't mess with spaces and formatting in general. Formatting rules are always a pain and it also never satisfies every people.

\* [Sadly, Prettier still doesn't format HTML](https://github.com/prettier/prettier/issues/1882).

**Comment by rafaelss95** [comment]
Update: Now you can use Prettier to format HTML :)

@mgechev Let's remove the `votes needed` label here?

**Comment by mgechev** [comment]
@rafaelss95 you're a project collaborator. I believe you should have write access as well. Let me know if that's not the case so I can fix it.

**Comment by rafaelss95** [comment]
@mgechev Ah, yes I have :)
