### ISSUE TITLE
Angular2 style guide links wrong

### ISSUE THREAD

**Issue by cementito** [mgechev/codelyzer#62]
The links do not resolve to the proper guide section anchor:

Example:

        [11, 1]: Implement lifecycle hook interfaces (https://goo.gl/uhVsrr)

links to
[https://angular.io/docs/ts/latest/guide/style-guide.html#!#style-09-01](https://angular.io/docs/ts/latest/guide/style-guide.html#!#style-09-01)

should link to
[https://angular.io/docs/ts/latest/guide/style-guide.html#!#09-01]
(https://angular.io/docs/ts/latest/guide/style-guide.html#!#09-01)

**Comment by mgechev** [comment]
@cementito thanks for the issue! I'll fix it in a sec.

**Comment by mgechev** [comment]
Fixed in 0.0.24.
