### ISSUE TITLE
component-selector stopped working in Angular v6

### ISSUE THREAD

**Issue by dev054** [mgechev/codelyzer#620]
I have the config:

`"component-selector": [true, "element", "sg", "kebab-case"],`

and this component:

```
@Component({
  selector: 'sg-cmp' 
})
class AppCmp {}
```

Now I'm getting a warning

> [tslint] The selector of the component "AppCmp" should have prefix "app" (https://angular.io/styleguide#style-02-07) (component-selector)

It used to working before upgrade.

**ng -v:**
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.0
Node: 9.10.1
OS: linux x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by wKoza** [comment]
When you say "before upgrade", what are you talking about ? Angular CLI, Codelyzer or the both ?

**Comment by dev054** [comment]
Hard to say, but I've upgraded everything.

Before all `@angular` related stuff was in 5.2.10 and `Codelyzer` 4.2.1. After upgrading I'm getting these warnings.

**Comment by wKoza** [comment]
Are you sure about your `tslint.json` , maybe have you more than one  `component-selector` entry in your file. 
Can you push one repro in Github ?

**Comment by wKoza** [comment]
Without further informations, I close this issue for the moment.

**Comment by SebasG22** [comment]
@wKoza The issue should be open, the problem persist.
Typescript File
![image](https://user-images.githubusercontent.com/17608169/40817531-77f6f2d2-6518-11e8-9c8b-e4006ea35aab.png)
Tslint config
![image](https://user-images.githubusercontent.com/17608169/40817550-9e96dd62-6518-11e8-86a2-df1b2d9c98e1.png)

**Comment by wKoza** [comment]
I think you confound the type (`element` or `attribute`) and the list of prefixes. You have an error because you have set prefixes `app` and `page`. You should therefore change your selector name with `app-login-main` or `page-login-main`.

**Comment by SebasG22** [comment]
@wKoza You are right, but still not working.
![captura de pantalla 2018-06-01 a la s 9 57 42 a m](https://user-images.githubusercontent.com/17608169/40847548-53fbfb92-6582-11e8-879a-d766f5d1e625.png)

**Comment by rafaelss95** [comment]
Are you sure guys that your config are not being overwritten in `<your-project>/src/tslint.json`? It's a new file that came in `angular-cli` v6 and maybe you didn't notice that.

**Comment by rafaelss95** [comment]
Are you sure that your config are not being overwritten in `<your-project>/src/tslint.json`? It's a new file that came in `angular-cli` v6 and maybe you didn't notice that.

**Comment by SebasG22** [comment]
@rafaelss95 thanks you, I realized that the src/tslint.json (Angular Generated) overwritten my global ( tslint.json )custom rules.

**Comment by Linkker** [comment]
insert line 
@Component({
  // tslint:disable-next-line:component-selector
  selector: 'vtc-temp',
