### ISSUE TITLE
[no-template-this]

### ISSUE THREAD

**Issue by dev054** [mgechev/codelyzer#622]
A rule to disallow `this` in template:

```ts
@Component({
  selector: 'sg-cmp',
  template: `
    {{ this.myVar }}
  `
})
class SgCmp {
  myVar = 5;
}
```

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by rafaelss95** [comment]
I like this proposal. I can see one case where `this` in template is "useful": when you want to access dynamic properties: `{{ this[dynamicProp] }}`, so I think it could be configurable:

```JSON
{
  "rules": {
    "template-no-this": true, // disallow any usage of `this`
    "template-no-this": [true, "allow-dynamic-properties"] // or something like this, to allow dynamic usage
  }
}
```
