### ISSUE TITLE
A rule to enforce the use of property binding

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#624]
Samples:

```ts
@Component({
  selector: 'my-app',
  template: `
    <img src="{{url}}"> <!-- prefer <img [src]="url"> -->
    <label for="{{dynamicAttr}}"></label> <!-- prefer <label [attr.for]="dynamicAttr"></label> -->
    <div class="{{myClass}} class1 class2"></div> <!-- prefer <div class="class1 class2" [ngClass]="myClass"></div> -->
  `
})
export class AppComponent {}
```

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by rafaelss95** [comment]
@mgechev @wKoza I'm implementing this rule (actually 95% complete) and some questions came to my mind, can we discuss this?

**1 -** Is it good/safe to have a fix for this rule?
**2 -** Considering the following case:

```HTML
<source src="{{basePath}}{{endpoint}}" type="video/mp4">
```

  2.1 - Should we report failures if there are multiple interpolations? Maybe it should be configurable?
  2.2 - If the answer above was yes: How the fix would be done for this? Or for this specific cases the fix wouldn't be applied? 

**3 -** As I'm bad with names, I want some suggestions from you... so far I'm calling it `template-prefer-property-binding`.

**Comment by rafaelss95** [comment]
I'm extending `BasicTemplateAstVisitor` and using `visitElementProperty` to try to distinguish `cannonical-form` from `property-binding`, but it seems that it's not possible. Thoughts @mgechev?

**Comment by wKoza** [comment]
@rafaelss95 , I like your original idea and your last proposal seems to move in this bad direction. The enemy is the interpolation. After , maybe can we give the choice between property binding and canonical form but I'm not really convinced  of the gain.
For the first question, attempting a fix seems dangerous.
And for the name, `template-prefer-property-binding` seems good.

**Comment by rafaelss95** [comment]
Hey @wKoza after having created this issue (almost an year ago), I noticed that Angular does not indicate one of the forms, so I guess we shouldn't also. That's the reason why I've proposed to leave it configurable so that users can choose the best option according to the standard of their projects.

I think the best definition for this rule is: Let's standarize one form in the project, no matter what. :)

**Comment by wKoza** [comment]
hmm.. Your rule checks the binding on which attribut ? only HTML attribut  or all properties ?

**Comment by rafaelss95** [comment]
Only element properties for now..

**Comment by wKoza** [comment]
okay. So, the name is ambiguous. Maybe template-harmonize-html-attribute-binding. And let's the choice to the user in this case.

**Comment by mohammedzamakhan** [comment]
@mgechev since @rafaelss95 is working on this, can you remove the votes needed tag from this issue?

**Comment by rafaelss95** [comment]
@mohammedzamakhan I've removed the _label_.
