### ISSUE TITLE
Turn on strict TS compilation mode

### ISSUE THREAD

**Issue by rkirov** [mgechev/codelyzer#629]
We started syncing this repo for google internal usage. Technically we have exceptions for code that doesn't have `'strict': true`, but it is generally best to use that flag to be consistent with the rest of google TS users.

**Comment by rafaelss95** [comment]
I was about to open an issue to suggest the same thing.

@ mgechev can I work on it?

**Comment by mgechev** [comment]
@rafaelss95 sure!

**Comment by mgechev** [comment]
@rafaelss95 how's this task going?

**Comment by rafaelss95** [comment]
@mgechev Sry for the delay, I'm a little busy this week, but I hope I can send a PR tomorrow. :rocket:
