### ISSUE TITLE
support of Typescript 2.0

### ISSUE THREAD

**Issue by Delagen** [mgechev/codelyzer#63]
Error: Unsupported TypeScript version: 2.0.0-dev.20160703

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/codelyzer/commit/82121b770ac03b2df361f5b9705cc8bcda2d9412.

**Comment by mgechev** [comment]
@Delagen actually tslint doesn't support TypeScript 2.0 yet so codelyzer cannot support it neither.

**Comment by Delagen** [comment]
@mgechev you are kidding me? tslint works with typescript@2.0
palantir/tslint#1355

**Comment by mgechev** [comment]
It is still in `dev`, which means that it won't be installed by default with `npm i tslint`. 

Would you verify that the rules work with `tslint@3.12.0-dev.2`?

**Comment by Delagen** [comment]
@mgechev already 3.13.0 published to npm

**Comment by Delagen** [comment]
Almost week has passed. And it must not install with npm I tslint as it in peerDependencies, but semver range >=1.7.3 does not prevent it to be 2.0
