### ISSUE TITLE
[template-conditional-complexity] - Report failures for other directives besides ngIf

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#630]
Currently this rule only computes conditionals wrapped by `*ngIf`, it'd be great if we could have failures for `[class]` and `[ngClass]` bindings as well, e.g.:

**Config:**
```JSON
{
  "rules": {
    "template-conditional-complexity": [
      true,
      2
    ]
  }
}
```

```html
<div [class.px-4]="a === b && c === d && d === e && e === 3"> <!-- expected failure here -->
  Content
</div>
```

**Comment by rafaelss95** [comment]
@mgechev is it a bug? I thought it was an enhancement. That's why I separate this and #627.

**Comment by mgechev** [comment]
@rafaelss95 you're correct. Will close it as a feature request.
