### ISSUE TITLE
Feature request: template-prefer-safe-navigation-operator

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#632]
A rule to enforce the following:

```html
<div *ngIf="obj?.a?.b?.c">
  content
</div>
```

... instead of this:

```html
<div *ngIf="obj && obj.a && obj.a.b && obj.a.b.c">
  content
</div>
```

**Comment by lazarljubenovic** [comment]
Is compiled code exactly like this with `?.`? Or does it do an actual `!= null` check?

**Comment by rafaelss95** [comment]
According to [docs](https://angular.io/guide/template-syntax#the-safe-navigation-operator----and-null-property-paths):

> The Angular safe navigation operator (?.) is a fluent and convenient way to guard against null and undefined values in property paths.
