### ISSUE TITLE
use-life-cycle-interface support for inheritance

### ISSUE THREAD

**Issue by david-driscoll** [mgechev/codelyzer#64]
If I have the following, would it be possible for the rule `use-life-cycle-interface` to not throw a lint error?

``` typescript
class Parent implements OnInit {
    public ngOnInit() {
    }
}

class Child extends Parent {
    public ngOnInit() {
        super.ngOnInit();
    }
}
```

**Comment by preslavsh** [comment]
I will play with it next week. If you can do it make a PR

**Comment by preslavsh** [comment]
I don't see a good way that can be done know.

**Comment by meriturva** [comment]
Hi @preslavsh any news here? so thanks!

**Comment by DethAriel** [comment]
Not 100% related, but I'm wondering whether other rules can take inheritance into account, too? Like the `The property "xyz" that you're trying to access does not exist in the class declaration`, although it exists in parent class. This is kinda annoying and the reason why I have to keep this rules disabled.

**Comment by mgechev** [comment]
Will be fixed once we merge [this](https://github.com/mgechev/codelyzer/commit/d0d71387ab322f7bbb612c79bc673fe9dbf4880f).

**Comment by pgrm** [comment]
upgrading from `3.0.0-beta.4` to `3.0.0` we seem to be getting this issue again. Is it the same or it just looks very similar? - this also happened with https://github.com/mgechev/codelyzer/issues/191#issuecomment-296660455

**Comment by mgechev** [comment]
Yes, ngast support is pushed for 4.0.0. Because of the breaking changes introduced by tslint@5 I had to push a new major release.

**Comment by paulshelestovich** [comment]
Still happening, same error with inheritance

**Comment by Zoomink** [comment]
This is still an issue using `4.4.4`. @mgechev any suggestions?

**Comment by antch** [comment]
This issue should be re-opened.
