### ISSUE TITLE
Feature request: template-prefer-as-syntax

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#647]
Instead of:

```html
<div *ngFor="let a of arr; let index = index; let odd = odd">
  {{ a }}
</div>
```

This:

```html
<div *ngFor="let a of arr; index as index; odd as odd">
  {{ a }}
</div>
```

The same applies for `ngIf`.

**Comment by lazarljubenovic** [comment]
Is there an official rationale to prefer the second one? Otherwise we should make it configurable. Developer should choose which one they prefer and the linter should make sure it's consistent.

**Comment by rafaelss95** [comment]
> Is there an official rationale to prefer the second one?

AFAIK, no... and yes, I totally agree, it could be configurable.
