### ISSUE TITLE
Feature request: template-prefer-sugar-ngFor

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#649]
Instead of:

```html
<ng-template ngFor let-person [ngForOf]="persons" let-i="index">
  {{ person.name }}
</ng-template>
```

Prefer:

```html
<ng-container *ngFor="let person of persons; index as i">
  {{ person.name }}
</ng-container>
```

**Comment by lazarljubenovic** [comment]
Last time I checked, although these two have the same effect, they produc different code. The first one recognizes if there is a single element inside it, while the second one always uses the upoptimized version.

(Just observing, not saying this is a bad rule - I'd love to see it as well.)
