### ISSUE TITLE
Feature request: A rule to enforce literal string in *ngSwitchCase

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#652]
Example:

```ts
@Component({
  selector: 'app-root',
  template: `
    <div>
      <div *ngSwitchCase="hey"> // Expected a failure here
        Hey!
      </div>
      <div *ngSwitchCase="'one'">
        One!
      </div>
    </div>
  `
})
export class AppComponent  {
  myVariable = 'hey';
}
```

**Comment by lazarljubenovic** [comment]
I don't think you'd want to do this globally. Isn't it a too common usecase to use an enum from the component, or a number?

**Comment by rafaelss95** [comment]
Good catch! When I created this issue I was just wondering about the above use case, forgot totally about what you described. Now I'm unsure about this would be a good rule.
