### ISSUE TITLE
About rule names

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#653]
Template rules are a little bit mixed, some start with `template`, others with `templates`, others with nothing.
I want to propose to normalize them with the prefix `template-`:

`banana-in-box` -> `template-banana-in-box`;
`i18n` -> `template-i18n`;
`templates-no-negated-async` -> `template-no-negated-async`
`trackBy-function` -> `template-use-trackBy-function` (not sure about the capitalized "B")
`angular-whitespace` -> `template-whitespace`

<hr>

Also, another suggestions for names would be:

All the `*-life-cycle-*` rules should be renamed to `*-lifecycle-*`, as mentioned in some issues/PRs;
`no-output-named-after-standard-event` should be renamed to `no-output-standard-event` or something like that since this rule cares precisely about exact output names.

**Comment by mgechev** [comment]
@rafaelss95 the proposal makes sense. We should coordinate the effort with Angular CLI. It might be a good idea to push the rules before their next major release.

**Comment by rafaelss95** [comment]
Hey @mgechev :), what about makes these changes before Angular 8?
