### ISSUE TITLE
A better way to disable rules in template

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#654]
Consider the following markup:

```ts
// tslint:disable:trackBy-function <--
@Component({
  template: `
    <div *ngFor="let a of arr"> // Supposing that I want to disable the rule only here
      {{ a }}
    </div>

    <div *ngFor="let a of arr1">
      {{ a }}
    </div>
  `
})
class AppComponent {
  arr = [1, 2, 3];
  arr1 = [1, 2, 3, 4];
}
```

I can't disable a specific rule for specific line/lines. Currently I've to disable all the template.

**Comment by lazarljubenovic** [comment]
Idea:

```
<!--
// tslint:disable
-->
<div>template</div>
<!--
// tslint:enable
-->
```

But indeed, it's ugly. I wonder if the disable/enable commets are configurable in tslint...

**Comment by mohammedzamakhan** [comment]
I think with more and more rules for template in this repo, we definitely will need a way to disable rules.
