### ISSUE TITLE
Feature request: directive and components selector support for module-name

### ISSUE THREAD

**Issue by SanderElias** [mgechev/codelyzer#656]
Both the component as well as the directive selector do this:
`The selector of the component "Sub1Component" should have prefix "app" (https://angular.io/styleguide#style-02-07) (component-selector)`

However, I would love to have support for enforcing de module name in there, if that is at all possible.
I mean, that something like this:

```typescript
@Component({
  selector: 'demo-sub1',
  template: `
    <h1>
      sub1 works!
    </h1>
  `,
  styles: []
})
```

should be valid when it is part of the `demo`  module.

**Comment by wKoza** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by SanderElias** [comment]
@wKoza perhaps a clue on how to vote might help the voting process? ;)

**Comment by mgechev** [comment]
Give yourself a 👍

**Comment by sgwatgit** [comment]
This convention is mentioned in the official [style guide](https://angular.io/guide/styleguide#style-02-07)

`Do use a custom prefix for a component selector. For example, the prefix toh represents from Tour of Heroes and the prefix admin represents an admin feature area.`

**Comment by mgechev** [comment]
In the style guide, we agreed on application level prefixes for directives & component. One of the core motivations for this practice is to make the directives & components developed by your team more apparent when reading the code. I can see why the module level may make sense as well.
