### ISSUE TITLE
Feature request: allow kebab-case class selectors for components and directives

### ISSUE THREAD

**Issue by webtrix** [mgechev/codelyzer#66]
I'm sorry if this is already available, but I can't find the right configuration in my `tslint.json` file to get this working.

For components and directives, when using a class selector, I think it would be better to keep to the Google CSS style guides in mind and not use `camelCase` but `kebab-case`, with or without a prefix.

**Comment by mgechev** [comment]
We do not support CSS selectors (except element selectors) yet. Most likely we'll switch to something like https://github.com/mdevils/node-css-selector-parser in more advanced version which is in progress.

**Comment by mgechev** [comment]
FYI here's an issue to keep an eye on https://github.com/mgechev/codelyzer/issues/15.
