### ISSUE TITLE
[Feature Request] Detect attribute & event conflicts with native HTML / DOM

### ISSUE THREAD

**Issue by dominique-mueller** [mgechev/codelyzer#661]
### Feature

Codelyzer could detect component attributes (inputs) and events (outputs) that have the exact name as native HTML / DOM attributes and events. By detecting those conflicts, Codelyzer can eliminate confusion by preventing (assumingly) unexpected behaviour from occuring.

### Example

The `title` attribute can be used to show a small tooltip when the user is hovering over the element this attribute is assigned to. But, when creating a component that exposes a `title` attribute as well - and the binding is being implemented statically (`title="..."` instead of `[title]="..."`) - the title attribute (while still working as expected) now also works as a tooltip.

Despite this behaviour making totally sense, it's probably not expected by developers and might lead to confusion.

*Related: https://github.com/angular/angular/issues/24376*

### Proposal

I could imagine two new rules, one for detecting attributes, one for detecting events. For instance:

``` json
{
  "no-native-attributes": true,
  "no-native-events": true
}
```

Allowing exceptions from this rule would be possible, but I'm not sure whether it makes sense. Another open questions is where to get the list of native HTML attributes and events.

**Comment by mgechev** [comment]
Thanks! Marking it as a `votes needed` and closing it. Once we implement it, I'll drop the `votes needed` label.

**Comment by rafaelss95** [comment]
@dominique-mueller About `input attributes`, do you have any source that we can find a complete list? For `output native`, we already a have one now :)

**Comment by wKoza** [comment]
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/language-service/src/html_info.ts

or https://www.w3schools.com/tags/ref_attributes.asp

**Comment by rafaelss95** [comment]
Looking at the above lists.. it seems it's kind of weird restricting people from naming their `inputs` as `disabled`,` value`, etc ...

**Comment by wKoza** [comment]
We should restrict to the "Global Attributes".

**Comment by rafaelss95** [comment]
> We should restrict to the "Global Attributes".

Hmm.. let's imagine a component that wraps the input behavior with some predefined styles, etc., like this:

```
@Component({
  selector: 'app-input',
  template: `
    <input [type]="type" [id]="id">
    <!-- more and more code -->
  `
})
export class InputComponent {
  @Input() id: string; // See below
  @Input type: string;
}
```

Since `id` is a 'global attribute', we should have a failure there, right? Btw... how should people name it?
