### ISSUE TITLE
no-input-rename rule should allow aliasing dashed properties

### ISSUE THREAD

**Issue by mertdeg2** [mgechev/codelyzer#663]
Specifically, something like this should be allowed:

`@Input('aria-label') ariaLabel: string;`

In above, we can't have a variable called aria-label. TS code wouldn't compile, and JS engine would complain invalid left hand side assignment.

**Comment by mgechev** [comment]
Regex to whitelist names makes sense.

**Comment by rafaelss95** [comment]
Whitelist only for `aria-*` family then? Btw, I found [this reference](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques).
