### ISSUE TITLE
Feature request: disallow import from parent directory

### ISSUE THREAD

**Issue by FDIM** [mgechev/codelyzer#664]
I am not sure how others do this, but at least in our project we are using baseUrl in tsconfig and almost all of our imports are relative to the root of the repo, e.g.: 
```
// should pass
import { SomeService } from 'common/services/some.service'; 
import { SomeService } from 'common/services';  // if you have index.ts
import { Foo } from './util/foo';

// should fail
import { SomeService } from '../../services/some.service';
import { SomeService } from '../services/some.service';
```

A rule to enforce this would be quite nice. How about `no-parent-dir-import`?

I am willing to investigate and make a PR if there is some interest.

**Comment by lazarljubenovic** [comment]
This looks like a tslint feature, not codelyzer. Nothing Angular-specific here, right?

**Comment by FDIM** [comment]
yep, nothing angular specific - but it might be easier / faster to include it here than in the tslint itself. I'll open the issue there and reference this one.

As for node_modules, it just goes down to order - it tries base directory first and then fallbacks to node_modules or any other folder dictated by compiler options paths property in tsconfig
