### ISSUE TITLE
Feature request: A rule to disallow the use of providers in NgModule

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#666]
Angular 6 brings a new **recommended** way to define injectable using `providedIn`.

Relates to #558.

**Comment by mohammedzamakhan** [comment]
Some third-party libraries force you to use providers
https://aws-amplify.github.io/docs/js/angular#importing-the-angular-module

**Comment by rafaelss95** [comment]
@mohammedzamakhan you're right. When I created this issue I was just thinking in the app's own providers :/

**Comment by mohammedzamakhan** [comment]
Yeah, the rule still makes sense, and I think most of the projects can have this rule enabled, and in such rare case, they will add tslint ignore for just this alone

**Comment by jeandat** [comment]
How do you write an HttpInterceptor with "providedIn"? Is it possible?
