### ISSUE TITLE
Export codelyzer to IDE autoformat rules

### ISSUE THREAD

**Issue by geoHeil** [mgechev/codelyzer#67]
Hi,

is it possible to export codelyzer's rules e.g. space around import statements to a IDE's auto-formatting e.g. intelliJ?

**Comment by mgechev** [comment]
I've been working on an auto-format functionality [here](https://github.com/mgechev/codelyzer/tree/refactoring). In the next a couple of weeks I won't be able to release it but I'll try to have something working by this fall.

**Comment by mgechev** [comment]
Since it is in the roadmap and in an experimental branch, lets close the issue for now.
