### ISSUE TITLE
Some PRs are missing in changelog (v4.4.0)

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#672]
**Features:**
#569, #595

**Bug fixes:**
#575, #582, #585, #590, #593, #597, #610, #611, #612, #614, #617 

**Others:**
#625

**Comment by rafaelss95** [comment]
@mgechev can you tell me how is the changelog being generated currently?

**Comment by mgechev** [comment]
@rafaelss95 the process is manual ATM. We can go with [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator).

**Comment by mgechev** [comment]
@rafaelss95 looks like I've missed these commits because they weren't part of the 4.4.0 milestone.
