### ISSUE TITLE
no-output-on-prefix rule

### ISSUE THREAD

**Issue by krichert** [mgechev/codelyzer#678]
Actual: no-output-on-prefix rule fails when 'on' is in the word (irrelevant where it is - on the begging, in the middle, on the end)
Expected: no-output-on-prefix rule fails 'on' is in the beginning of word (prefix)

**Comment by mgechev** [comment]
This is fixed by https://github.com/mgechev/codelyzer/commit/adc974af75193a78b1e9f6f4760319143965b6b1. I'll release the change in the next few days.

**Comment by mgechev** [comment]
Actually, it's already out in 4.4.2.
