### ISSUE TITLE
Fix compilation issues with TS 2.9

### ISSUE THREAD

**Issue by mertdeg2** [mgechev/codelyzer#679]
We had to locally change following rules to get them compiled under TS 2.9

noInputRenameRule.ts
preferOutputReadonlyRule.ts

These rules had something like this: `(property.parent as ts.PropertyAccessExpression)`.

Everything seems to compile when we changed above to `(property.parent as ts.ClassLikeDeclaration)`

**Comment by rafaelss95** [comment]
Codelyzer supports up to the latest version of TS supported by the Angular, which is so far I am writing this comment, 2.7.2.
