### ISSUE TITLE
component-selector-name: should it really warn for names without dashes?

### ISSUE THREAD

**Issue by chapati23** [mgechev/codelyzer#68]
I'm a fan of concise code and naming (not obscure acronyms , just short names). So I like to keep my component names short. For example:
```typescript
@Component({
  selector: 'transaction'
})
```

This throws a no-kebab-case warning. IMO a simple string without any capitalisation or special characters should _pass_ this rule and not fail.

@mgechev, bug or just different opinions?

**Comment by mgechev** [comment]
Yes, it should throw a warning. `transaction` is not a valid name for a custom Web Component.

**Comment by chapati23** [comment]
in case anyone else stumbles over this: http://www.w3.org/TR/custom-elements/#valid-custom-element-name

custom element spec requires a hypen to "force-avoid" naming conflicts with other custom elements.

**Comment by Igonato** [comment]
@mgechev how about an option that would allow names without a hyphen. Would be happy to make a PR if you are ok with it.

**Comment by mgechev** [comment]
Since selectors without a dash are not valid I don't think we should consider them.
