### ISSUE TITLE
TypeScript compilation error due to missing source-map types

### ISSUE THREAD

**Issue by szymonbultrowicz** [mgechev/codelyzer#685]
After creating a simple TypeScript project with an empty Codelyzer rule, TypeScript compilation failes due to:

```
node_modules/codelyzer/angular/metadata.d.ts:1:30 - error TS7016: Could not find a declaration file for module 'source-map'. '/home/travis/build/szymonbultrowicz/codelyzer-sourcemap-test/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm install @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
1 import { RawSourceMap } from 'source-map';
                               ~~~~~~~~~~~~
```

It looks like `source-map` in version 0.5.7 (which codelyzer uses) doesn't have it's own typings. Moreover, types from `@typings/source-map` are also deprecated and actually don't work because instead of having type definitions they just have a dependency to the latest `source-map`. In case when `codelyzer` already has that dependency, `@typings` dependency is placed in their own `node_modules` and thus TS still cannot find the definitions. 

Repository with code to reproduce this issue:
https://github.com/szymonbultrowicz/codelyzer-sourcemap-test

And a Travis build with the error:
https://travis-ci.org/szymonbultrowicz/codelyzer-sourcemap-test/jobs/398325520#L448

**Comment by mgechev** [comment]
Looks like this is no longer reproducible.
