### ISSUE TITLE
Bring back templates-use-public

### ISSUE THREAD

**Issue by pockata-kt** [mgechev/codelyzer#689]
I would want to suggest to bring back the **templates-use-public** rule. I understand that it was removed because it is something that the angular compiler should handle, but in Angular 6, templates are now static fields in their components, thus they have access to the private properties. ([source](https://www.rednxt.com/whats-new-in-angular-6/) under section _New Features > Private properties in templates_). This leaves nothing checking it. It would be very useful to have a linter rule that ensures the use of only public properties in the template. I hope you consider bringing it back!

**Comment by mgechev** [comment]
Hey @pockata-kt, the Angular compiler determines if private members should be accessible within the templates. If it generates code where they can be, then there's no point restricting this behavior.
