### ISSUE TITLE
Component selector prefix

### ISSUE THREAD

**Issue by natejgardner** [mgechev/codelyzer#69]
With the current configuration, this lints all of the components to match only one feature. The Angular2 styleguide encourages use of prefixes for some selectors that may be otherwise ambiguous. These prefixes are supposed to be centered around the specific feature the component is associated with. For example, toh-heroes or admin-users. The current configuration makes the desired prefix static, which doesn't make sense. Instead, it should simply check the presence of a prefix at all and remind the user to name it after the feature, perhaps checking the context making sure other components in the same directory with potentially colliding names across the app also use the same prefix.

**Comment by mgechev** [comment]
Duplication of https://github.com/mgechev/codelyzer/issues/48.
