### ISSUE TITLE
no-unused-css can't handle @media

### ISSUE THREAD

**Issue by apo34** [mgechev/codelyzer#690]
I've encountered an error regarding no-unused-css rule.
It seems as if the rule wouldn't be able to handle @media calls in the scss files.
![no-unused-css](https://user-images.githubusercontent.com/28670067/42690653-647325c4-86a5-11e8-9745-bd53f174c9ce.gif)

![image](https://user-images.githubusercontent.com/28670067/42690886-4f7cb4ea-86a6-11e8-8c98-6627459b46be.png)

Versions:

- angular: 6.0.3
- codelyzer: 4.4.2

Steps to reproduce: 

- Create new angular project,
- add codelyzer,
- add no-unused-css rule,
- change app.component.css to scss,
- add @media rule,
- make some change in app.component.ts to trigger tslint

Simple reproduction -> [stackblitz](https://stackblitz.com/edit/angular-gnu2fk?file=src%2Fapp%2Fapp.component.ts) (of course it wouldn't show ts-lint errors)

**Comment by mgechev** [comment]
The rule is experimental and the chances are that we'll remove it at some point, or completely rewrite it.

I'll close this issue for now and consider it when we decide how we'll proceed.
