### ISSUE TITLE
Out of date tslint rules

### ISSUE THREAD

**Issue by hugonoro** [mgechev/codelyzer#691]
I'm running an Angular 6 project with codelyzer 4.4.2 and tslint 5.10.0 and I'm getting the following message when running the ng lint:

Could not find implementations for the following rules specified in the configuration:
    no-access-missing-member
    templates-use-public
    invoke-injectable
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

Are these rules no longer in place? I can remove them locally or check if they were renamed in the tslint documentation but whenever I update codelyzer I reckon I would get them back, hence the request to check for a potential issue in the source :)

**Comment by mgechev** [comment]
These rules are no longer part or codelyzer. You can remove them from `tslint.json`.
