### ISSUE TITLE
Using fixers in external Angular templates. 

### ISSUE THREAD

**Issue by cwoolum** [mgechev/codelyzer#699]
I'm using Codelyzer as a base for ionic-team/v4-migration-tslint. We have some rules that work against HTML and they seem to work fine when the template is inlined but they mangle the TypeScript when a templateUrl is used. I've only seen one usage of templateUrl for finding unused CSS classes but there is no fixer for it. Have any of the rules ever had fixers working against an external template?

**Comment by mgechev** [comment]
There's a bug related to reporting in external templates. This seems like a regression caused by a dependency. You can look at this issue for details https://github.com/mgechev/codelyzer/issues/692.
