### ISSUE TITLE
Use Injectable() instead of Injectable

### ISSUE THREAD

**Issue by JohannesRudolph** [mgechev/codelyzer#70]
According to https://angular.io/docs/ts/latest/guide/dependency-injection.html

> 
> ALWAYS INCLUDE THE PARENTHESES
> Always write @Injectable(), not just @Injectable. Our application will fail mysteriously if we forget the parentheses.

It would be great if codelyzer could enforce this as a tslint rule (unless it's already enforced somehow?)

**Comment by mgechev** [comment]
Nice suggestion! I'll work on this issue during the weekend.

**Comment by JohannesRudolph** [comment]
Cool, thanks a lot for implementing this!
