### ISSUE TITLE
angular-whitespace autofix broke the html document

### ISSUE THREAD

**Issue by michaeljota** [mgechev/codelyzer#702]
The rule is to put spaces after and before the Angular interpolation (`{{}}`), but sometimes it removes and adds angular brakes on its own leaving something like this `{{ { firstNam }}}`. Notice there is even a missing char from the `firstName` variable.

**Comment by mgechev** [comment]
Thanks for sharing this problem! Are there any HTML entities in the template? Would you share a test case that we can use to debug the issue?

**Comment by michaeljota** [comment]
I had this issue with some regular variables, when two or more interpolations were close, and I have to say it seems to reproduce more by using the translation key and pipe used by ngx-translation

**Comment by mgechev** [comment]
Also, what's your operating system? I remember we had similar issues on Windows.

**Comment by michaeljota** [comment]
I'm sorry I didn't reply earlier. My OS is Windows 10. I was using the cli with powershell, calling it from a npm script.

**Comment by michaeljota** [comment]
@rafaelss95 I'm using latest of each, but Angular I'm using latest from 5.x. I don't sure if I can share the whole file, but it's just extending recommended, and for the rules of codelyzer the same, just copy pasted the recommended.

**Comment by mgechev** [comment]
@michaeljota I believe @JamesHenry was working on prettier support for Angular (inline?) templates.

**Comment by JamesHenry** [comment]
Not just yet, I originally had it in the same PR as when I added inline style formatting, but the HTML formatting (in general) in Prettier is still a WIP, once that lands it will be straightforward to add inline template formatting for Angular Components.

You can subscribe to the general issue here: https://github.com/prettier/prettier/pull/4753

**Comment by gaspardip** [comment]
Same thing here. Trying to setup prettier+codelyzer+stylelint. Not that easy so far.

tslint.json
`{
  "rulesDirectory": ["node_modules/codelyzer"],
  "extends": ["angular-tslint-rules", "tslint-consistent-codestyle", "tslint-config-prettier"],
  "rules": {
    "array-type": [true, "array"],
    "ban": [
        true,
        "eval",
        "alert",
        "$",
        {
          "name": ["*", "forEach"],
          "message": "Use a regular for loop instead. Please check .find/.findIndex/.filter/.map/.some/.every if you are performing one of these operations."
        }
    ],
    "no-implicit-dependencies": false,
    "no-inferrable-types": false,
    "no-var-keyword": true,
    "no-var-requires": true,
    "object-literal-sort-keys": [
      true,
      "match-declaration-order",
      "shorthand-first"
    ],
    "ordered-imports": true,
    "typedef": [
      true,
      "call-signature",
      "parameter",
      "member-variable-declaration"
    ]
  }
}
`

"codelyzer": "^4.4.4"
"tslint: "^5.11.0"
"tslint-config-prettier": "^1.15.0"
"tslint-consistent-codestyle": "^1.13.3"

Input
`
              <mat-option *ngFor="let av_programa of av_programas" [(value)]="av_programa.Id" class="sizeTitle">
                {{av_programa.Name}}
              </mat-option>
`

Output
`
              <mat-option *ngFor="let av_programa of av_programas" [(value)]="av_programa.Id" class="sizeTitle">
               {{ {av_programa.Nam }}}
              </mat-option>
`

**Comment by michaeljota** [comment]
Prettier just release 1.15 with support for Angular templates and fix spaces between the declaration and the interpolation.

**Comment by wKoza** [comment]
`angular-whitespace` is now deprecated. So, we can close this issue.

**Comment by jorgekleeen** [comment]
Is still in [the docs](http://codelyzer.com/rules/angular-whitespace/)
