### ISSUE TITLE
no-input-rename fails if input alias is prefixed with directive selector

### ISSUE THREAD

**Issue by marcincichocki** [mgechev/codelyzer#705]
Currently codelyzer doesn't allow to rename inputs of a directive other than its selector.

```typescript
@Directive({
  selector: '[appHighlight]',
})
export class HighlightDirective {
  // works with codelyzer 4.4
  @Input('appHighlight') visible = true;

  // still an error
  @Input('appHighlightColor') color = 'yellow';
}
```

```html
<h1 appHighlight appHighlightColor="red">Demo</h1>
```

In example above `HighlightDirective#color` have alias prefixed with directive's selector to prevent name collisions within the template(if component or other directive have same input prop). 

If this means anything, `@angular/material` uses this convention(for example: https://github.com/angular/material2/blob/6.4.6/src/lib/sort/sort.ts#L76)

Thank you for this amazing project!

**Comment by mgechev** [comment]
@marcincichocki thanks for reporting this! I can see that @rafaelss95 already took care of the issue ⚡️. I'll review & merge today.
