### ISSUE TITLE
Rule use-pipe-transform-interface shows violation when extending a class which implements PipeTransform

### ISSUE THREAD

**Issue by andreasgebauer** [mgechev/codelyzer#714]
When extending a class which already implements the PipeTransform interface a violation of that rule is shown on that class. This rule should analyze the class hierarchy and check if PipeTransform is already implemented higher up in the hierarchy.

**Comment by mgechev** [comment]
I'd recommend you to disable the rule for this specific class. codelyzer does not perform type checking at the moment, and we don't have plans for introducing it in the near future.
