### ISSUE TITLE
Request: Create a separate package containing removed rules

### ISSUE THREAD

**Issue by PRR24** [mgechev/codelyzer#715]
There is a lot of discussion here about removed rules like templates-use-public.
For me personally it means being stuck in version 3.2.1 as I heavily depend on this specific rule.
Saying that, I do respect a Minko's decision to keep the software modern and unbloated.

As a solution I would recommend to create a separate package, like "codelyzer-compat" (or similar), that contains rules that do not expect users to have their projects based on latest angular-cli/ngc.
This would allow the main package to be modern and focused while providing solution for non-standard environments.

**Comment by lazarljubenovic** [comment]
It would be better to just split the rules across packages. Have `@codelyzer/core` for common helper logic, and then have each rule as a `@codelyzer/rule-xxx`. And then have `@codelyzer/all` or `@codelyzer/common` for the ones that are "official" -- maybe even name it `@codelyzer/styleguide` or `@codelyzer/official`.

Then people could install whatever they want if they are not happy with what the official package provides.

**Comment by mgechev** [comment]
Let's keep this outside of the scope of codelyzer. Currently, in the CLI we provide automatic migration for breaking changes, which helps us workaround this.
