### ISSUE TITLE
Update peer Dependencies to support Angular v7 without warnings

### ISSUE THREAD

**Issue by DanielHabenicht** [mgechev/codelyzer#717]
Currently when installed with Angular 7 npm produces two warnings: 

```bash
npm WARN codelyzer@4.4.4 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.4.4 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
```

in order to have a clean installation the peer Dependencies of this project have to be updated. 

I did not encounter any problems when using the current version (4.4.4) with Angular 7

**Comment by mgechev** [comment]
Use `codelyzer@4.5.0`.

**Comment by DanielHabenicht** [comment]
I am sorry. I did not see the PR 7 days ago. Thought I had upgraded all my packages but it did not.

**Comment by mgechev** [comment]
No worries
