### ISSUE TITLE
trackBy-function not reporting failures involving multiple `*ngFor` directives

### ISSUE THREAD

**Issue by axelboc** [mgechev/codelyzer#718]
I have two `*ngFor` directives within the same template.

- If neither has a `trackBy` function, rule `trackBy-function` reports two failures. ✅ 
- If only the first one has a `trackBy` function and the second one doesn't, rule `trackBy-function` **doesn't report any failure**. ❌

**Comment by wKoza** [comment]
Thanks for your report. We're going to figure out the problem.
