### ISSUE TITLE
feature request: detect incorrrect usage of async/inject in specs

### ISSUE THREAD

**Issue by oocx** [mgechev/codelyzer#729]
We recently discovered the following subtile error in many of our specs:
```
it("sollte das Dashboard 3 Gruppen enthalten", async(() => {  
            inject([DashboardService], (sut: DashboardService) => {
                sut.getDashboard("dashbaord", companyNo).subscribe(() => expect(sut.dashboardConfiguration.groups.length).toBe(3));
            });
}));
```
As you could probably immediately see :), inject was used incorrectly here. Inject returns a function which is supposed to be called from async, but the dev here did not know that and used it in a way in which it got never called.

Our team is new to Angular, so someone did it wrong once and everybody else just copied that code for new specs, so we probably have this mistake all over our codebase.

The code should be:
```
it("sollte das Dashboard 3 Gruppen enthalten", async(inject([DashboardService], (sut: DashboardService) => {
                sut.getDashboard("dashbaord", companyNo).subscribe(() => expect(sut.dashboardConfiguration.groups.length).toBe(4));
})));
```

It would be nice if there was a codelyzer rule that detects an inject that is never called.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
