### ISSUE TITLE
Extends i18n  rule to check attributes

### ISSUE THREAD

**Issue by Karamuto** [mgechev/codelyzer#730]
As the i18n can also be used for attributes for example to translate a 'title' attribute you place a 'i18n-title' on the element, it would be great if one could define themselves a list of attributes to translate.

This could look like the proposel in #628: 

```
{
  "rules": {
    "i18n": [
      true,
      "check-id",
      "check-text",
      {
        "check-attributes": ["placeholder", "title"]
      }
    ]
  }
}
```

**Comment by wKoza** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
