### ISSUE TITLE
Feature Request: Disallow inline "style" attribute

### ISSUE THREAD

**Issue by gregjacobs** [mgechev/codelyzer#731]
Hey @mgechev. First off, great work on this project. We're finding it very useful to maintain code consistency and catch common errors.

A colleague of mine and I are tasked with providing direction for UI projects within our organization, and have noticed that a number of projects make use of inline `style` attributes in their HTML. We all know that this is a generally bad practice, so we were thinking of introducing a codelyzer rule for this.

I'm thinking that if we were to implement it, it should be split between two rules, something to the tune of `no-static-inline-style` and `no-dynamic-inline-style` to differentiate between something like `style="color: red;"` and the dynamic  `[style.color]="isSpecial ? 'red' : 'green'"` type of expressions. I think there are some use cases for the dynamic expressions (dynamic animations on elements and such), so it might be good to differentiate between the two.

Thoughts?

**Comment by gregjacobs** [comment]
Does anyone actually vote on closed issues?

**Comment by mgechev** [comment]
Here you can find the [issues sorted](https://github.com/mgechev/codelyzer/issues?utf8=%E2%9C%93&q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc+) by the number of votes they have.
