### ISSUE TITLE
Dependency on tslint

### ISSUE THREAD

**Issue by huerlisi** [mgechev/codelyzer#76]
This package assumes there is a dependency on tslint in the consuming application. I think this is what the npm `peerDependencies` can be used for.

Shouldn't we add a `peerDependency` on `tslint`?

**Comment by huerlisi** [comment]
Wow you're fast! That's an incredible nice experience, thanks a lot!

**Comment by arkon** [comment]
@mgechev Is there any reason why the peer dependency is specifically version 3.9.0?
