### ISSUE TITLE
`!.` in html prevents working for rules like `angular-whitespace`

### ISSUE THREAD

**Issue by Emeryao** [mgechev/codelyzer#767]
A tricky story

I have an angular project with `--strict` in `tsconfig.json` so it starts to complain about null property in html files like `<div>foo.bar</div>` when the object of `foo` is possibly null
so I change the html template to `<div>foo!.bar</div>` to suppress the error 

but with those codes the codelyzer rules like `angular-whitespace` starts not checking the html file 
it seems that the `!.` prevent the codelyzer/tslint from working on the very html file

and when I change the template to `<div>foo?.bar</div>` with [the safe navigation operator](https://angular.io/guide/template-syntax#the-safe-navigation-operator----and-null-property-paths) all things work well

---
Sorry for my poor English 😝

**Comment by rafaelss95** [comment]
`angular-whitespace` is deprecated. See #719.
