### ISSUE TITLE
Migration to ESlint

### ISSUE THREAD

**Issue by chaosmonster** [mgechev/codelyzer#769]
This is a long-term feature request.

As Palantir decided to drop TSLint and to move everything to ESLint [read here](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) codelyzer should start thinking about a migration path. 
This might to be done with the Angular-CLI team together as they are integrating codelyzer with every build [Angular-CLI issue](https://github.com/angular/angular-cli/issues/13732)

**Comment by wKoza** [comment]
Thks @chaosmonster ,

I close your issue and re-open #763 . 

Duplicate #763
