### ISSUE TITLE
Doesn't work with external templates

### ISSUE THREAD

**Issue by mohammedzamakhan** [mgechev/codelyzer#770]
I created new project using Angular CLI, and didn't see the template rules running in external templates, though they worked in internal template.

**Comment by mohammedzamakhan** [comment]
Either close this issue and reopen https://github.com/mgechev/codelyzer/issues/94 or keep this open

**Comment by wKoza** [comment]
Hi @mohammedzamakhan ,
Codelyzer has to work with external template. You can test that adding this rule 

` "banana-in-box": true` in your tslint file and 

```html
<input ([ngModel])="title" name="title">
```

in your app.component.html file.

What is your version of Angular CLI ?

**Comment by mohammedzamakhan** [comment]
I am using the latest 7.3.2, and yes I do that the rule `"banana-in-box": true` in my tslint

**Comment by wKoza** [comment]
Can you push me a repo ?

**Comment by mohammedzamakhan** [comment]
https://github.com/mohammedzamakhan/test-a11y

**Comment by wKoza** [comment]
curious, it's work for me.

```
ERROR: /users/william/webstormprojects/test-a11y/src/app/app.component.html[6, 22]: Invalid binding syntax. Use [(expr)] instead

Lint errors found in the listed files.
Linting "test-a11y-e2e"...
```

You launch `ng lint` ?

**Comment by mohammedzamakhan** [comment]
So it only shows error using `ng lint`, but does not show errors directly in the VSCode editor when using `tslint` VSCode Extension?

I want it to show errors directly in the editor, like it shows for internal templates

<img width="945" alt="screen shot 2019-02-21 at 2 51 58 pm" src="https://user-images.githubusercontent.com/2327532/53200940-6a15a900-35e8-11e9-9eed-55d5dea0dacb.png">

**Comment by mgechev** [comment]
@mohammedzamakhan yes, that's a known issue. Unfortunately at the moment we cannot do this because of limitations in the tslint plugin.

Let's close this issue because it's likely that we don't use tslint in the future and this is a tslint-specific problem.
