### ISSUE TITLE
contextual-decorator: fails for some cases

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#776]
~**Case 1:** (It doesn't report failures for pipes)~ **Fixed in #754**.

```
@Pipe({
  name: 'app-test'
})
export class TestPipe {
  @Input() someVar: string; // should report a failure, currently it does not.
}
```

**Case 2:** (it doesn't report failures if `ViewChild` decorator is applied to a setter accessor)
```
@Injectable({ // doesn't work for @Pipe also
  providedIn: 'root'
})
export class TestService {
  @ViewChild(Pane)  // should report a failure, currently it does not.
  set pane(v: Pane) {
    console.log('v', v);
  }
}
```

<hr>

Also, the `@Attribute` decorator is not handled at the moment. Is it intentional? @mgechev @wKoza

**Comment by wKoza** [comment]
@Attribute can only be used in a constructor. It's maybe the reason (which it's not a valid reason ;) ).
But, if we handle `@Attribute`, what about `@Host`, `@Self`, ... ?

So, I don't think it's intentional.

**Comment by wKoza** [comment]
@rafaelss95 , I've just seen that `@Attribute` is a bad practice [here](https://github.com/mgechev/codelyzer/blob/a9d74bef3a93818520127676612fc67531dde785/src/noAttributeParameterDecoratorRule.ts)

**Comment by rafaelss95** [comment]
> @rafaelss95 , I've just seen that `@Attribute` is a bad practice [here](https://github.com/mgechev/codelyzer/blob/a9d74bef3a93818520127676612fc67531dde785/src/noAttributeParameterDecoratorRule.ts)

@wKoza Yep, it's supposed to be, however the rules are independent, right?

**Comment by wKoza** [comment]
I think we should still keep some consistency but I don't have the whole history of this rule.

**Comment by superdyzio** [comment]
Today I noticed weird behavior for `@Pipe` and `@Injectable`.
Example:
```
@Pipe({
  name: 'tableRow',
})
export class TableRowPipe implements PipeTransform {
    @Input() x; // not an error
}
```
and
```
@Pipe()
export class TableRowPipe implements PipeTransform {
    @Input() x; // error
}
```

Similar behavior for `@Injectable()` and `@Injectable({...})`. Codelyzer `5.0.1` and tslint `5.16.0`.
