### ISSUE TITLE
Feature Request: `prefer-template-url` and `prefer-style-urls`

### ISSUE THREAD

**Issue by cafesanu** [mgechev/codelyzer#789]
Would love to have optional rules `prefer-template-url` and `prefer-style-urls` (or similar names), which will force you to create an html and a style file as opposed to have the html and css within the component.ts file

Thanks!

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by cafesanu** [comment]
@mgechev would love to create a pull request with these rules if you think they make sense. The angular style guide mentions this as a DO in here https://angular.io/guide/styleguide#style-05-04, so it would be nice to have theme at least optionally.

If you think it makes sense and my PR will make it, are there any guidelines to follow or recommendations?

**Comment by wKoza** [comment]
Currently, we have the rule `component-max-inline-declarations` which checks whether the number        of line is above 3. You can configure this rule with the number 0. You'll have an error like this:
` Exceeds the maximum allowed inline lines for template. Defined limit: 0 / total lines: 1 (https://angular.io/guide/styleguide#style-05-04)
`

**Comment by cafesanu** [comment]
Nice! that is what I needed! Thanks!
