### ISSUE TITLE
Pipe/Directive/Component naming conventions should be more consistent

### ISSUE THREAD

**Issue by DethAriel** [mgechev/codelyzer#79]
Here are the current naming-related options:

``` json
{
  "pipe-naming": [true, "camelCase", "sg"],
  "directive-selector-name": [true, "camelCase"],
  "component-selector-name": [true, "kebab-case"],
  "directive-selector-prefix": [true, "sg"],
  "component-selector-prefix": [true, "sg"],
  "component-class-suffix": true,
  "directive-class-suffix": true
}
```

Not only are they inconsistent (I mean `"pipe-*"` versus `"component-*"`), there's just too many of them. Maybe the below format would be more appropriate/easier:

``` json
{
  "[pipe|directive|component]-naming": [
    true,
    {
      "selector-prefix": "sg",
      "selector": "[camelCase|kebab-case]",
      // or, to make this somewhat future-proof
      // "selector": ["camelCase", "tolerate-kebab-case", "tolerate-PascalCase"]
      "suffix": true|false,
    }
  ]
}
```

**Comment by mgechev** [comment]
We have improvement in this direction. We will change the configuration a bit in near future, for sure, but for now I think the current configuration makes a lot of sense.

Closed by https://github.com/mgechev/codelyzer/commit/3373dffe7962f5e919161d60bc152f0d82dcb5d2.
