### ISSUE TITLE
[Feature request] - Rule to disallow the misuse of `PipeTransform`

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#796]
Consider the following snippet:

```
@Injectable() // imagine here any decorator other than a @Pipe
export class MyAwesomeService implements PipeTransform {
  transform(value: string, times: number) {
    return value.repeat(times);
  }
}
```

`MyAwesomeService` is not decorated with  `@Pipe()` and is implementing the `PipeTransform` interface.

This obviously makes no sense and currently we doesn't have a rule that handle this case.

<hr>

I was thinking to add it to the existing rule `contextual-lifecycle`, but this rule is, as its name implies, specifically to `lifecycle` cases (interfaces and methods).

Thoughts, @mgechev @wKoza?

**Comment by mgechev** [comment]
I see cases when people may want to implement the `PipeTransform` interface for a service. It means - I want to declare a service which has a `transform` method, this seems fine to me.

**Comment by rafaelss95** [comment]
> I see cases when people may want to implement the `PipeTransform` interface for a service.

Hmm, I'm not sure if people would do this in the real world, because as the name implies, it should be only used for `@Pipe`s. It would be really strange to see a _non_ `@Pipe` class implemeting it. Also, if people try to do this with the `use-pipe-decorator` rule enabled, failures will be reported to enforce the class to be decorated with `@Pipe()`.

> I want to declare a service which has a `transform` method...

Let's imagine the same situation for `lifecycle hooks`: I want to declare a service which has a `ngOnInit` method. Doesn't it sounds strange? The rule `contextual-lifecycle` doesn't allow me to do so, right? So, for me it's the same idea.

**Comment by mgechev** [comment]
I'd probably return code which has service implementing `PipeTransform` during code review because of personal preferences. It doesn't feel right; at the same time, I'm not sure it deserves an entire rule.

I don't think implementing the `ngOnInit` method is comparable with `transform,` mostly because of the `ng` prefix. Still, these are very vague arguments, and it's mostly a matter of personal preference.
