### ISSUE TITLE
[Question] Can I use 'codelyzer' with VS Code editor?

### ISSUE THREAD

**Issue by VladimirAmiorkov** [mgechev/codelyzer#80]
I just found out about codelyzer and did the `npm install --save-dev codelyzer`, hopped over to my {N} project, added an `tslint.json` in to root and pasted the recommended [configuration](https://github.com/mgechev/codelyzer#recommended-configuration) from the readme. After all that I checkted VS code, did a TypeScript transpile but no errors were found, I changed some declarations intentionally to cause and error but still nothing is highlighted or outputted as error.

So my question is is codelyzer supposed to work with VS Code editor?

**Comment by Doomape** [comment]
I am having the same issue, in VS code i thought it's some kind of a bad configuration on my side but when i use  "extends": "tslint:recommended" i get errors and warnings back so i am not sure what's the issue.

**Comment by mgechev** [comment]
Here's how your `settings.json` should look like https://gist.github.com/mgechev/3622937a235a80ce2742.
