### ISSUE TITLE
Rule template-accessibility-elements-content not found

### ISSUE THREAD

**Issue by cexbrayat** [mgechev/codelyzer#801]
Using `5.0.0-beta.2`, I've got the following error:

```
Could not find implementations for the following rules specified in the configuration:
    template-accessibility-elements-content
```

using the following `tslint.json`:

```json
"template-accessibility-alt-text": true,
// not found in 5.0.0-beta.2
"template-accessibility-elements-content": true,
"template-accessibility-label-for": true,
"template-accessibility-tabindex-no-positive": true,
"template-accessibility-valid-aria": true,
```

Note that the other rules are found, so I may be missing something, but I think the name is correct (see https://github.com/mgechev/codelyzer/blob/master/src/templateAccessibilityElementsContentRule.ts#L44).
The error was already present in `beta.0` and `beta.1`.

**Comment by wKoza** [comment]
Indeed, This rule is missing in the file https://github.com/mgechev/codelyzer/blob/master/src/index.ts
