### ISSUE TITLE
[docs] Update rule names after recent renaming 

### ISSUE THREAD

**Issue by kamilchlebek** [mgechev/codelyzer#807]
Currently docs contains only old names for recently renamed rules. 

ex. http://codelyzer.com/rules/use-input-property-decorator/ that was renamed to `no-inputs-metadata-property`

It would be good to reference new names inside the description or rename these entries totally.

**Comment by mgechev** [comment]
https://github.com/mgechev/codelyzer/commit/6d283e6fc5ff4a46fceb81d8885f4813a11cd929
