### ISSUE TITLE
[Feature Request] prefer-reactive-forms/no-ng-model rule

### ISSUE THREAD

**Issue by buu700** [mgechev/codelyzer#809]
Not sure which would be the better name, but I'm working on a project right now where the team has internally deprecated usage of `[ngModel]` in favor of `[formControl]`. A lint rule to automatically flag uses of `[ngModel]` would make this a lot easier to enforce going forward.

**Comment by rafaelss95** [comment]
Hmm.. not sure if I understood your feature request. Are you suggesting a rule to **flag** all `ngModel` usages? Or only the _mixed_ ones, e.g.: `<input [ngModel]="someValue" formControlName="someName">`?

**Comment by buu700** [comment]
Yeah, I was suggesting a rule to flag all uses (maybe with an optional parameter to find just mixed ones). Not that this should be recommended for everyone or included in the tslint-angular preset, but it would definitely be helpful for teams/projects that are trying to use reactive forms for most or all of their application.

**Comment by rafaelss95** [comment]
Although I use `Reactive Forms` in 90% of cases, I still can see some cases where `ngModel` is more suitable... as for example, a paginator component where you don't necessarily deal with `forms` and have a select element to control how many items should be on the page.

For the _mixed_ ones, I saw that there's an open PR https://github.com/angular/angular/pull/28996 that will remove deprecated support for `ngModel` on reactive form directives.

**Comment by buu700** [comment]
Yeah, I agree with that, and wouldn't try to advocate 100% reactive forms usage as a general best practice.

Where we're looking to use this is a project that's pretty big/complicated but basically just a bunch of forms and tables, and all the custom UI implementations exist in (or are being factored out to) a separate module that wouldn't have this rule applied.

**Comment by emilio-martinez** [comment]
There are cases where ngModel is helpful in that it can instantiate a `FormControl` without needing to be within a Form, i.e., leverage CVA streams. I also use ReactiveForms 90% of the time, but I wouldn't ban ngModel entirely for it.
