### ISSUE TITLE
Provide "recommended" and "latest" configurations 

### ISSUE THREAD

**Issue by DethAriel** [mgechev/codelyzer#81]
### Enhancement Request

`tslint` supports configuration extensions via `"extends"` json option. This is a very convenient way of reusing configurations and keeping up-to-date with latest linter advancements.

Given the roadmap for codelyzer, it's obvious that there will be linting rules added in the future. To allow developers take advantage of these, it would be convenient if `codelyzer` provided a set of preconfigured settings. There's already a "Recommended Configuration" section in the readme, so why not extract that to a ".json" file?

Given that `"extends"` option also supports "the name of an NPM module which has a "main" file that exports a config object", the `package.json` file could also be modified to export the, say, "recommended" configuration:
```json
  "main": "presets/ng2-recommended.json"
```
Or, even better, "recommended" and "latest" configurations could be their separate npm packages.

**Comment by mgechev** [comment]
This is tslint specific, probably with the guys there we can discuss something like that. The tslint extensibility is something which is great and can be even further improved. Lets close the issue here and move the discussion to the right place.

**Comment by kputh** [comment]
I'd argue that these presets are codelyzer-specific because they build on rules provided mostly by codelyzer.

**Comment by NiKlimenko** [comment]
@mgechev any updates about this suggestion?

**Comment by ohrrkan** [comment]
I join kputh. Those are codelyzer specific. The goal is to provide some preset like tslint configuration preset : https://palantir.github.io/tslint/usage/configuration/

like a 

```
  "extends": [
    "tslint:all",
    "codelyzer:all"
  ],

```
or a

```
  "extends": [
    "tslint:all",
    "codelyzer:recommended"
  ],
```
