### ISSUE TITLE
[Feature Request] no-unused-public-component-members rule

### ISSUE THREAD

**Issue by buu700** [mgechev/codelyzer#810]
A rule to flag every instance of a public component class variable or method that isn't referenced by the associated template would be extremely useful.

There are certainly some edge cases where a public member might be needed without having been referenced in the template, but I think these would be the vast minority of cases, and so would be fine for most projects to just comment with one-off lint exceptions.

**Comment by rafaelss95** [comment]
@buu700 It seems that it was already suggested in #596. Can you check if that issue is the same as yours?

**Comment by buu700** [comment]
Ah whoops, thanks! That sounds pretty much the same, but I'll add my additional suggestion in a comment there.
