### ISSUE TITLE
template-accessibility-label-for does not recognise nested custom control components.

### ISSUE THREAD

**Issue by Merott** [mgechev/codelyzer#811]
**Describe the bug**

I have a custom checkbox form control, with the selector `x-checkbox`, nested inside a `label`. Despite configuring `controlComponents` for `template-accessibility-label-for`, I still get this:

> A form label must be associated with a control

This feels like I must be doing something wrong because it's a really basic use case...

**Context and configuration**

Rule configuration:

```json
"template-accessibility-label-for": [
  true,
  {
    "controlComponents": ["x-checkbox"]
  }
]
```

Simplified Template code:

```html
<label>
  <x-checkbox></x-checkbox>
  Check me
</label>
```

**Environment**

 - Version: 5.0.0
 - OS: macOS 10.14.4
 - Node.js version: 11.12.0
 - Yarn version: 1.15.2
 - Angular version: 7.2.11
 - tslint version: 5.14.0

**Comment by rafaelss95** [comment]
Thanks for reporting this bug. I'll submit a PR later to fix this along with #808.
