### ISSUE TITLE
Disable "template-use-track-by-function" globally

### ISSUE THREAD

**Issue by vmurillo** [mgechev/codelyzer#817]
Hello,

My tslint.json is:

`{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "extends": ["angular-tslint-rules"],
  "rules": {
    "template-use-track-by-function": false
  }
}
`

However when I run `./node_modules/.bin/tslint src/**/*.ts`

I still get 
 src/app/components/select/select.component.html:3:10 - Missing trackBy function in ngFor directive

Is it possible to deactivate this rule for all templates?

**Comment by rafaelss95** [comment]
It should work. Check if you don't have this rule enabled in any other `tslint.json` (Angular projects usually have at least 2).

**Comment by vmurillo** [comment]
My bad, it is working. Thanks a lot
