### ISSUE TITLE
[Feature Request] no-implicit-barrel-imports

### ISSUE THREAD

**Issue by dedward3** [mgechev/codelyzer#822]
**Disclaimer** I'm admittedly weak in my knowledge of how typescript actually goes about building things and specifically how the Angular build system works. So if I get some terminology wrong or I've assumed something incorrectly. Please forgive me, I'm doing my best to convey this issue that I've run into quite a few times.

Also I want to say this upfront. I've built a lint rule for this problem for personal use. I'm posting here to see if there is any interest in contributing this back to the community or if it has been brought up before. I've looked around and didn't find much.

## The Problem
Implicit barrel imports in Angular libraries cause some really weird build errors.

The main problem is that they are VERY hard to track down because this issue is masked by other errors like "Maximum call stack size exceeded". 

## What is an "Implicit Barrel Import"
Say you have a directory "my-service-module", which contains files for a bunch of services. 

In a normal typescript environment, you can export all of these services through an index.ts file in the directory. Then when you import it somewhere else you can say

`import { MyService } from '../../my-service-module'` 

And everything runs just fine. However in an Angular library that import will cause your build to fail. In order to fix this error you have to import your service like such

`import { MyService} from '../../my-service-module/index'`

## Things to note
- I have not spent the time to confirm that this is always an issue in Angular libraries. So this could be setup specific, I'm not sure. I do know that I've found a fair amount of issues on StackOverflow where implicit barrel imports were the culprit. I also know that anytime I use an implicit barrel import in my projects, I encounter build errors.
- I have seen this issue across multiple versions of Angular.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
