### ISSUE TITLE
Rule to forbid using ::ng-deep at the top level

### ISSUE THREAD

**Issue by maxime1992** [mgechev/codelyzer#823]
When a component uses in its style(s) `:ng-deep` at the top level, this will basically act as a global style. This is really dangerous and it'd be nice to have a rule to enforce *not* doing that.

I've made a small stackblitz demo here: https://stackblitz.com/edit/ng-deep-leak

`AppComponent`
  |__ `Sub1Component`
  |__ `Sub2Component`

In this example, every component has within its template a `div` with a `class="hello"`.

**Only** the `Sub2Component` has the following style:

```css
::ng-deep {
  .hello {
    color: red;
  }
}
```

All of the components (even the top level one) are affected: 

![image](https://user-images.githubusercontent.com/4950209/58183866-f72fd300-7ca7-11e9-800d-a5af4999e8bc.png)

If we could have 2 levels of severity, that'd be brilliant:
- Non strict, just requires you to have a selector before the `::ng-deep`
- Strict (default?), requires you to always need a `:host` selector before using `::ng-deep`, so that the "leak" is only happening downward, not both up and down.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
