### ISSUE TITLE
[Question] Does "codelyzer" work with NativeScript

### ISSUE THREAD

**Issue by VladimirAmiorkov** [mgechev/codelyzer#84]
I have been trying to run the "codelyzer" with an [NativeScript](http://docs.nativescript.org/angular/tutorial/ng-chapter-0) project but I do not know if it is actually possible. NativeScript does support Angular 2 RC6 and what I am trying is:

- add codelyzer with `npm install --save-dev codelyzer`
- add an `tslint.json` file in the root of the app where the `package.json` with the following contents:
```
{
    "tslint.rulesDirectory": "./node_modules/codelyzer",
    "rulesDirectory": [
        "node_modules/codelyzer"
    ],
    "rules": {
        "directive-selector-name": [
            true,
            "camelCase"
        ],
        "component-selector-name": [
            true,
            "kebab-case"
        ],
        "directive-selector-type": [
            true,
            "attribute"
        ],
        "component-selector-type": [
            true,
            "element"
        ],
        "directive-selector-prefix": [
            true,
            "sg"
        ],
        "component-selector-prefix": [
            true,
            "sg"
        ],
        "use-input-property-decorator": true,
        "use-output-property-decorator": true,
        "use-host-property-decorator": true,
        "no-attribute-parameter-decorator": true,
        "no-input-rename": true,
        "no-output-rename": true,
        "no-forward-ref": true,
        "use-life-cycle-interface": true,
        "use-pipe-transform-interface": true,
        "pipe-naming": [
            true,
            "camelCase",
            "sg"
        ],
        "component-class-suffix": true,
        "directive-class-suffix": true,
        "import-destructuring-spacing": true
    }
}
```
- finnaly go to VS Code and run a task that builds all .ts files to .js files with the help of an a tsconfig.json file:
```
{
    "version": "1.8.10",
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": false,
        "watch": false,
        "noLib": false,
        "preserveConstEnums": true,
        "emitDecoratorMetadata": true,
        "suppressImplicitAnyIndexErrors": true,
        "noImplicitUseStrict": true,
        "experimentalDecorators": true
    },
    "filesGlob": [
        "./**/*.ts"
    ],
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

After all that the output is still empty, and I know there should be an error because I have added the `ngOnInit()` without setting the `implements OnInit` on the class. Am I missing something or is NativeScript not supported for codelyzer?

**Comment by mgechev** [comment]
Yes, it supports NativeScript. At this point codelyzer is a set of rules for tslint so it is supported by all text editors and IDEs with tslint plugin (that is one of the reason we decided to build on top of tslint instead of developing yet another linter):

![](http://i.giphy.com/l3vQZXleufd3Qqwnu.gif)

All you need for VSCode is to set `tslint.rulesDirectory` in your `settings.json`:

```json
{
    "tslint.rulesDirectory": "./node_modules/codelyzer"
}
```

From the setup that you shared seems like you've added this property to `tslint.json` instead.

We're already analyzing Angular templates by processing the AST returned by the `TemplateParser`. This feature should be available for any Angular-based projects with inline templates (at first) because it is platform agnostic.

**Comment by VladimirAmiorkov** [comment]
Thank you for the detailed explanation it helped a lot and not its runs like a charm.
