### ISSUE TITLE
no-unused-variable from tslint is not sufficient to angular 2 project

### ISSUE THREAD

**Issue by netstart** [mgechev/codelyzer#86]
no-unused-variable from tslint is not sufficient to angular 2 project. We need verify teamplate html

"no-unused-variable": true,

Look researched variable for exemple. 
If use this variable only in tamplate we receive a Message:
    Failed to lint: login/modulos/components/areabox/area-box-list.component.ts [38, 20]: Unused property: 'researched'.

![image](https://cloud.githubusercontent.com/assets/200232/18515258/185aff24-7a6b-11e6-856f-1029d1b9ec73.png)

**Comment by mgechev** [comment]
It makes sense to create a rule `ng-no-unused-variable`. With what we have in the `templates` branch I think we're not far from one.

**Comment by mgechev** [comment]
@netstart I was thinking that might be a good idea to keep this rule for the next version when we support external templates. Currently it will be only misleading for the users if we mark a variable as unused.

**Comment by mgechev** [comment]
Better to wait for the official Angular language service.

**Comment by dzonatan** [comment]
Before implementing it take a look at https://github.com/angular/angular/issues/11422 about accessing private properties when using AoT.

Also some key notes from http://stackoverflow.com/a/39000046/2320455:
> With ngc and static template compilation, you'll get errors if you try accessing private members of the component from template.

> In Dart the template can't reference private variables of the component class, because Dart in contrast to TypeScript effectively prevents access of private members from outside.

I'd think about creating the converse rule: to verify that all properties usages in template are with public access.

**Comment by mgechev** [comment]
Thanks for the comment! We have such [rule already](https://github.com/mgechev/codelyzer/blob/master/src/templatesUsePublicRule.ts).

**Comment by michaeljota** [comment]
The `no-unused-vars` rule will be deprecated in tslint 4. See [#1481](https://github.com/palantir/tslint/issues/1481).

**Comment by mgechev** [comment]
This is even greater motivation to include such rule in codelyzer. Now we support external templates so we can make it happen. I'm afraid that the release will become too big so I'd suggest to move this feature as part of the next one.

**Comment by michaeljota** [comment]
Still, the no-unused-vars will rise only for private members, and as @dzonatan said, all template binded properties should be public. (There is a rule for that already)

**Comment by amivit** [comment]
Any suggestions to get VS Code to work with Angular component fields showing up as unused like WebStorm can?
