### ISSUE TITLE
@Input @Outpur - marked as "public"

### ISSUE THREAD

**Issue by meriturva** [mgechev/codelyzer#87]
Hi to all
with new AoT compiler released in RC 5 i guess we have to mark all input/output as "public".
am i right?

so i think a new rule has to be introduced.

**Comment by mgechev** [comment]
We may introduce even more generic rule - mark as public all properties/method used in the templates. Should be straightforward with the updates in the `templates` branch.

**Comment by meriturva** [comment]
@mgechev Correct!

**Comment by mgechev** [comment]
@meriturva once https://github.com/mgechev/codelyzer/pull/90 gets merged we'll have this rule up and running!

**Comment by meriturva** [comment]
@mgechev Perfect....i will test it surely!
So thanks!
