### ISSUE TITLE
Using template rules with pug

### ISSUE THREAD

**Issue by undsoft** [mgechev/codelyzer#880]
Hey,

I'm trying to use template rules, such as 'template-use-track-by-function' on my project.
The problem is that I'm using pug in my templates.

I'm using https://github.com/danguilherme/ng-cli-pug-loader.

Is there any way for me to make template rules work with pug?
I'm willing do extend the rules if that's necessary, but would need some direction to do that.

Thanks.

**Comment by mgechev** [comment]
Hey @undsoft, you can check the [advanced config](https://github.com/mgechev/codelyzer#advanced-configuration) section in the readme. The functionality exists in codelyzer, but hasn't been exhaustively tested yet.

Let me know how it goes.

**Comment by undsoft** [comment]
It seems to be working okay more or less.
Here's my .codelyzer.js config:
```js
const pug = require('pug');

module.exports = {
  /**
   * Transforming pug templates for codelyzer.
   */
  transformTemplate(code, url) {
    const result = {code: code, url: url};

    if (url && /\.pug$/.test(url)) {
      const transformed = pug.render(code);
      result.source = code;
      result.code = transformed;
    }
    return result;
  },
};
```

Unfortunately I wasn't able to find anything that would generate proper sourcemaps, which means that numbers in tslint logs are off, but that's something I can live with.
