### ISSUE TITLE
fix(interfaces): mark only the method which corresponds to non-implemented interface

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#89]
Currently the text editors mark the entire class and it can get quite noisy. It'll be better to mark only the method which requires implementation of an interface, for instance:

```ts
@Component({
  // ...
})
export class ZippyComponent {
  ngOnInit() {
    // ...
  }
}
```

Should mark only the substring:

```ts
  ngOnInit() {
    // ...
  }
```

This requires changes for:

- `useLifeCycleInterfaceRule`.
- `usePipeTransformInterfaceRule`

And their test files.

**Comment by preslavsh** [comment]
#92  Updates that
