### ISSUE TITLE
template literal indent

### ISSUE THREAD

**Issue by serkon** [mgechev/codelyzer#909]
I need to set template literal indentation: space or tab and how much will be. 

I need 2 space inside template like this,
```typescript
@Component({
  template: `
    <button *ngIf="closable" type="button" class="close" aria-label="Close" (click)="onClose()">
      <span aria-hidden="true">&times;</span>
    </button>
    <ng-content></ng-content>
  `,
})
```

but Webstorm IDE changes space count to 4 automatically and not give an error

```typescript
@Component({
  template: `
      <button *ngIf="closable" type="button" class="close" aria-label="Close" (click)="onClose()">
          <span aria-hidden="true">&times;</span>
      </button>
      <ng-content></ng-content>
  `,
})
```

Like this configuration rule maybe help to developers at tslint.json:
`"literal-indent": [true,"spaces", 2]`

**Comment by mgechev** [comment]
The focus of codelyzer is not code-formatting but rather linting. Let's keep this outside of the scope of the project.
