### ISSUE TITLE
[Feature Request] disallow-pipe

### ISSUE THREAD

**Issue by marcelcremer** [mgechev/codelyzer#928]
Hey everyone,

I just encountered a frequent issue after adding a complex feature, that I pushed some leftover debug information to our QS system. Of course, the review will find it, but that means opening another issue, removing the debug and create a new merge request.

That's why I came up with the idea, that it would be awesome to have "disallow-pipe"-Rule, like

```
...
"disallow-pipe": ["json", "json-beautified"],
...
```

The linter could throw a warning, that those pipes are forbidden every time, that someone left something like 

```
{{ view | json }}
```

in the code.

Maybe other people have the same problem and this could be any use?

Cheers
Marcel

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
