### ISSUE TITLE
[Feature Request] Check that Services are provided

### ISSUE THREAD

**Issue by JWO719** [mgechev/codelyzer#931]
I think it would be valuable to have a linting rule to catch services that aren't provided in any module. Right now one just get a runtime error in this situation, looking like this:

```
Uncaught NullInjectorError: StaticInjectorError(LM)[Oc -> wc]: 
```

Especially in an aot compiled app this is not really helpful. Having a linting rule to prevent this scenario could help people from deploying a broken application.

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
