### ISSUE TITLE
Documentation for prefer-inline-decorator rule is outdated

### ISSUE THREAD

**Issue by y-moroz** [mgechev/codelyzer#939]
The syntax of options for the prefer-inline-decorator rule was changed in the https://github.com/mgechev/codelyzer/pull/794, and now docs show wrong information. Now the only way to understand how it works is to look at the source code - https://github.com/rafaelss95/codelyzer/blob/master/src/preferInlineDecoratorRule.ts#L91. Also, the documentation states that this rule has a fixer, while the hasFix option was deleted in the scope of the above PR. 

**Environment**

 - Version 5.2.0
 - OS: Ubuntu
 - Node.js version 13.2.0
 - Package manager (yarn/npm) version 6.13.1
 - Angular version 8.2.3
 - tslint version 5.11.0

**Comment by mgechev** [comment]
Thanks for pointing this out! [This](https://github.com/mgechev/codelyzer/commit/3348a1edffad2a272bc32034cc6ad78e73645428) commit should have fixed the problem.
