### ISSUE TITLE
Support for external templates

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#94]

**Comment by mgechev** [comment]
Implemented by https://github.com/mgechev/codelyzer/commit/67d5a07a56163f05e1e3d49e446fa6b0fde15ea2.

**Comment by mohammedzamakhan** [comment]
@mgechev I do not see it to work in a new angular cli project on external templates! Am I missing something?

**Comment by mohammedzamakhan** [comment]
Can we reopen this?
