### ISSUE TITLE
Documentation - Pull the install instructions to a new file and improve.

### ISSUE THREAD

**Issue by MalcolmAnderson** [mgechev/codelyzer#941]
**Documentation - Pull the install instructions to a new file and improve.**

I'm in a situation where I want to run static code analysis on my existing set of angular projects.  
I believe that I can get there with a couple of hours of experimentation with the sample project and 3 - 7 read through's of the current instructions.   (The documentation appears to cover 3 or 4 different starting point scenarios, that may or may not have assumptions built into one set of instructions that are explained in another section.

What I'm looking for are the instructions that look something like this.

Install and build codelyzer
-instructions to clone and build codelyzer

Run static code analysis
- "from the src directory" or "from the project level directory (where tslint.json exists)"
-- execute the following from the command line

Find and open the code analysis

What I want to start with is finding out is something along the lines of:
- how many methods per class
- how many lines of code per class
- how many lines of code per method
- how many lines of code per file (if file contains more than one class)
- cyclomatic complexity (he number of linearly independent paths through a method)
- catalog of duplicate lines of code, and the number of copies per line

**Comment by wKoza** [comment]
Hi @MalcolmAnderson ,

Codelyzer is a tool which verifies that your code respects the Angular's best practices. It is not designed to be used as a "Sonar like". 
There are other tools in order to check that.

**Comment by MalcolmAnderson** [comment]
Thank you @wKoza, do you have any suggestions of which other tools to start with?  Any time I search for "Angular static code analysis" I see a lot of enterprise-level ads and links to Codelyzer.   

It's for little things.  For instance, I've found the same 12 line section of code duplicated 21 times in our codebase (in 7 files, exactly 3 times in each file.)  For all I know, there's a valid reason for this duplication, but it's unlikely.

Our code base is 1000s of lines of code.  I'd like to get a clue as to what other types of duplication or other smells are out there.

Any suggestions for how to get a jump start on analyzing this codebase?

**Comment by wKoza** [comment]
For your needs,  [SonarQube](https://www.sonarqube.org/downloads/)  seems to be the best choice. It's a highly comprehensive tool.  There is a community edition. 
I know there are some tools like [jscpd](https://github.com/kucherenko/jscpd) but I've never tested it.

**Comment by MalcolmAnderson** [comment]
Awesome, thanks, looks like what I require.
