### ISSUE TITLE
angular-whitespace: check-pipe false positives

### ISSUE THREAD

**Issue by FDIM** [mgechev/codelyzer#947]
**Describe the bug**

There are some false positives in check-pipe option in angular whitespace rule

**To Reproduce**

```html
<ng-container *ngFor="let item of (items | keyvalue: keyValueSort)">
  <my-item [item]="item"></my-item>
</ng-container>
```
```
ERROR: path/to/xyz.component:1:40 - The pipe operator should be surrounded by one space on each side, i.e. " | ".

```

Same error also error occurs with following template:
```html
<button>{{ day.value | date: 'd' }}</button>
```

**Expected behavior**

I'd think that whitespace inside ngFor above and inside the button tag is correct

**Environment**

 - Version 5.1.0
 - Angular version: 8.2.4
 - tslint version: 5.20.0

**Comment by hoeni** [comment]
same here. Lots of false positives for this

**Comment by rafaelss95** [comment]
`angular-whitespace` is deprecated. See #719.
