### ISSUE TITLE
ad this rule in tslint.json -> https://ponyfoo.com/articles/template-literals-strictly-better-strings

### ISSUE THREAD

**Issue by stefanaerts** [mgechev/codelyzer#95]
@mgechev 
Hi,
I think its a good idea to add this(see article) rule to my tslint.json file.
Do you agreed this is a good rule mgechev?
If so, how do i put the eslint rule "quotes": ["error", "backtick"]
in my tslint.json config file generated with angular-cli?

![image](https://cloud.githubusercontent.com/assets/3684599/18743757/c94727a4-80ba-11e6-8bc4-557204f112f1.png)

Thx,
Kind Rg,
Stefan.

**Comment by mgechev** [comment]
Thanks for the suggestion! This is more like a rule which should be considered for tslint, I believe. With a few small exceptions, we are trying to keep this repository focused on Angular.
