### ISSUE TITLE
No changelog for version 5.2.1

### ISSUE THREAD

**Issue by nseni** [mgechev/codelyzer#958]
https://www.npmjs.com/package/codelyzer?activeTab=versions
The latest available version is 5.2.1.

But this version is not mentioned in Releases, Changelog or Commits
https://github.com/mgechev/codelyzer/releases
https://github.com/mgechev/codelyzer/blob/master/CHANGELOG.md
https://github.com/mgechev/codelyzer/commits/master

and in the package.json I see that the latest version is 5.2.0
https://github.com/mgechev/codelyzer/blob/master/package.json#L3

**Comment by mgechev** [comment]
Thanks for pointing this out. Here it is https://github.com/mgechev/codelyzer/blob/master/CHANGELOG.md#521-2020-03-03.
