### ISSUE TITLE
tslint 6 compatibility

### ISSUE THREAD

**Issue by snebjorn** [mgechev/codelyzer#959]
**Describe the bug**

I was wondering if the tslint version could be bumped to 6, it's currently 5

I keep getting peer dependency warnings :(

**Comment by KBeDevel** [comment]
I think this could be ignored due to ESLint migration :/

**Comment by snebjorn** [comment]
The ESLint migration is possibly months/years away.

I'd be willing to make a PR

**Comment by snebjorn** [comment]
From changelog for easy reference

> :fire: BREAKING CHANGES :fire:
> - [api] Changed default formatter to stylish (https://github.com/palantir/tslint/issues/4872)
> - [enhancement] Removed formatting and whitespace rules from `tslint:recommended` configuration (https://github.com/palantir/tslint/issues/4871)
> - [enhancement] Removed pedantic rules from `tslint:recommended` configuration (https://github.com/palantir/tslint/issues/4312)
> - [enhancement] `vso` formatter now reports severity of rule failures (https://github.com/palantir/tslint/issues/4286)
> - [enhancement] [`typedef`](https://palantir.github.io/tslint/rules/typedef/) rule `arrow-call-signature` option is more consistent in reporting errors on lambdas and will flag more violations that were missed in the previous rule implementation (https://github.com/palantir/tslint/issues/4533)
> - [bugfix] [`ordered-imports`](https://palantir.github.io/tslint/rules/ordered-imports/) is now consistent with TypeScript's Organise Imports ordering (https://github.com/palantir/tslint/issues/4064)
> - [bugfix] [`member-ordering`](https://palantir.github.io/tslint/rules/member-ordering/) now checks property accessors (getters and setters) (https://github.com/palantir/tslint/issues/3984)

**Comment by PowerKiKi** [comment]
This should be fixed by https://github.com/mgechev/codelyzer/pull/961

**Comment by alan-agius4** [comment]
Version 5.2.2 has been released which contains the above fix.
