### ISSUE TITLE
host property decorator = true?

### ISSUE THREAD

**Issue by stefanaerts** [mgechev/codelyzer#96]
![image](https://cloud.githubusercontent.com/assets/3684599/18743869/65753a44-80bb-11e6-98e0-86800b782504.png)

![image](https://cloud.githubusercontent.com/assets/3684599/18743887/7660b09a-80bb-11e6-99e9-be0b3b38024d.png)

@mgechev 
What is the recommended way?
the style guide or the codelyzer,it should be in sync?

**Comment by mgechev** [comment]
The rule does exactly what the style guide says but the rule name may sound misleading to you. It means: use host property decorator which is:

    @HostListener('click')
    foo() {}

**Comment by stefanaerts** [comment]
Ok thx
