### ISSUE TITLE
Support for Angular 8.x.x

### ISSUE THREAD

**Issue by umdstu** [mgechev/codelyzer#960]
**Describe the bug**

codelyzer@5.1.x requires angular/core@7.2.x

When you're on angular >= 8.0.x, ng update is unhappy updating without being foroced.
"Package "codelyzer" has an incompatible peer dependency to "@angular/core" (requires "^2.3.1 || >= 4.0.0-beta < 5.0.0" (extended), would install "9.0.5").
"Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires "^2.3.1 || >= 4.0.0-beta < 5.0.0" (extended), would install "9.0.5").

**To Reproduce**

install an angular@7.x application to angular@8.x

**Expected behavior**

The upgrade should work silently and without fail.

**Code**

N/A

**Environment**

 - Version 3.2.2
 - OS: Windows 10
 - Node.js version 10.16.3
 - Package manager (npm) version 6.9.0
 - Angular version 8.2.14
 - tslint version 5.11.0

**Additional context**

N/A

**Comment by rafaelss95** [comment]
I guess the `peerDependencies` are adjusted now.

https://github.com/mgechev/codelyzer/blob/4d597cd1497e9d1ff036a2362e7812961d63fc75/package.json#L94-L98
