### ISSUE TITLE
Support Angular 10

### ISSUE THREAD

**Issue by crfrolik** [mgechev/codelyzer#967]
```
warning " > codelyzer@5.2.2" has incorrect peer dependency "@angular/compiler@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0".
warning " > codelyzer@5.2.2" has incorrect peer dependency "@angular/core@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0".
```

**Comment by denis-starchenko** [comment]
++ The same problem

**Comment by emiliovmq** [comment]
The same here

**Comment by pickfire** [comment]
Well, the same problem happen to a lot of angular libraries every time there is an update.

**Comment by markgoho** [comment]
Have you guys checked out the `6.0.0` release? https://www.npmjs.com/package/codelyzer

**Comment by pickfire** [comment]
No, it was just up 2 days ago.

**Comment by markgoho** [comment]
@crfrolik can you confirm?

**Comment by hamfastgamgee** [comment]
It looks like there is a direct dependency in 6.0.0 to v9 @angular/core and @angular/compiler.  I'm guessing it's not quite ready yet?

**Comment by mgechev** [comment]
It's ready. The dependency is intentional to make sure codelyzer uses View Engine's parsing machinery.

**Comment by crfrolik** [comment]
Running `npm list` with Angular 10 and codelyzer 6 shows this in the console:

```
npm ERR! missing: @angular/core@9.0.0, required by codelyzer@6.0.0
```

I'm not sure if this is actually a problem, though.

**Comment by mgechev** [comment]
Codelyzer should have a direct dependency on v9 because of some internal APIs it uses. I'm surprised it errors out. Does your `ng lint` command work?

**Comment by crfrolik** [comment]
Yes, `ng lint` does work work, so maybe this isn't really a problem.

**Comment by ccarmesin** [comment]
> Running `npm list` with Angular 10 and codelyzer 6 shows this in the console:
> 
> ```
> npm ERR! missing: @angular/core@9.0.0, required by codelyzer@6.0.0
> ```
> 
> I'm not sure if this is actually a problem, though.

Hey @crfrolik I have the exact same Problem. Do you remember your solution for it? Thanks Cami :)

**Comment by crfrolik** [comment]
Are you using codelyzer 6.0.2? That is the latest version, and it should work with that.

**Comment by ccarmesin** [comment]
> Are you using codelyzer 6.0.2? That is the latest version, and it should work with that.

Yes, I tried also codelyzer 6.0.2 but the error is still there
```
npm ERR! missing: @angular/core@9.0.0, required by codelyzer@6.0.2
npm ERR! missing: @angular/compiler@9.0.0, required by codelyzer@6.0.2
```

**Comment by mohitrth26** [comment]
Hi @ccarmesin , I have the exact same Problem

Have you got the solution for this error?
