### ISSUE TITLE
[Feature Request] Rule: Inputs, Outputs and lifecycle methods on top

### ISSUE THREAD

**Issue by karmasakshi** [mgechev/codelyzer#975]
Presently in TSLint, one can set
```
"member-ordering": [
  true,
  {
    "alphabetize": true,
    "order": "fields-first"
  }
]
```
This enforces the code to be as following:
```
class DashboardPageComponent implements OnDestroy, OnInit {

  public aVar: string = '';
  @Input() public bVar: string = '';
  public cVar: string = '';
  @Input() public dVar: string = '';

  private xVar: string = '';

  public constructor() { }

  public aFun(): void { }

  public nFun(): void { }
  
  public ngOnDestroy(): void { }

  public ngOnInit(): void { }

  private xFun(): void { }

}
```
Proposing a new rule which puts members alphabetized in the following order:
1. Inputs
2. Outputs
3. Public fields
4. Private fields
5. Lifecycle hooks, preferably in the order they are called
6. Public methods
7. Private methods

Thus, the file would look like this:
```
class DashboardPageComponent implements OnDestroy, OnInit {

  @Input() public bVar: string = '';
  @Input() public dVar: string = '';
  
  public aVar: string = '';
  public cVar: string = '';

  private xVar: string = '';

  public constructor() { }

  public ngOnInit(): void { }

  public ngOnDestroy(): void { }

  public aFun(): void { }

  public nFun(): void { }

  private xFun(): void { }

}
```
Reason:

1. Having Inputs and Outputs at the top help quickly understand the usage of a component
2. Having lifecycle methods above user methods help quickly understand the behaviour of a component

**Comment by mgechev** [comment]
Hey @karmasakshi feel free to open this feature request in [angular-eslint](https://github.com/angular-eslint/angular-eslint). Since tslint's maintenance was discontinued we'll be moving to ESLint.
