### ISSUE TITLE
component-class-suffix does not work.

### ISSUE THREAD

**Issue by ranouf** [mgechev/codelyzer#977]
Hi,

I added this rule to tslint.json for my Angular project:

    "rules": {
        "component-class-suffix": [ true, "Component", "Container" ],
    }
or

    "rules": {
        "component-class-suffix": false,
    }

But, I continue to have this warning:

> ERROR: 14:14   component-class-suffix           The name of the class SelectOrganizationsContainer should end with the suffix Component (https://angular.io/styleguide#style-02-03)

Do I need to do something else to make this custom rule works?

Thanks

**Comment by rafaelss95** [comment]
Hello @ranouf, I just tested it locally and I was unable to reproduce it. Do you mind in share your full `tslint.json` or even creating a repo to demonstrate this issue? Thanks.

**Comment by ranouf** [comment]
Hi,

kind of long to create a new repo, the project is pretty big, if we can't find a solution, I will do it.

here us the tslint.json file:

> {
>   "rules": {
>     "prefer-for-of": false,
>     "component-class-suffix": false,
>     "align": {
>       "options": [
>         "parameters",
>         "statements"
>       ]
>     },
>     "array-type": false,
>     "arrow-return-shorthand": true,
>     "curly": true,
>     "deprecation": {
>       "severity": "warning"
>     },
>     "contextual-lifecycle": true,
>     "directive-class-suffix": true,
>     "directive-selector": [
>       true,
>       "attribute",
>       "app",
>       "camelCase"
>     ],
>     "component-selector": [
>       true,
>       "element",
>       "app",
>       "kebab-case"
>     ],
>     "eofline": true,
>     "import-blacklist": [
>       true,
>       "rxjs/Rx"
>     ],
>     "import-spacing": true,
>     "indent": {
>       "options": [
>         "spaces"
>       ]
>     },
>     "max-classes-per-file": false,
>     "max-line-length": [
>       true,
>       140
>     ],
>     "member-ordering": [
>       true,
>       {
>         "order": [
>           "static-field",
>           "instance-field",
>           "static-method",
>           "instance-method"
>         ]
>       }
>     ],
>     "no-console": [
>       true,
>       "debug",
>       "info",
>       "time",
>       "timeEnd",
>       "trace"
>     ],
>     "no-empty": false,
>     "no-inferrable-types": [
>       true,
>       "ignore-params"
>     ],
>     "no-non-null-assertion": true,
>     "no-redundant-jsdoc": true,
>     "no-switch-case-fall-through": true,
>     "no-var-requires": false,
>     "object-literal-key-quotes": [
>       true,
>       "as-needed"
>     ],
>     "quotemark": [
>       true,
>       "single"
>     ],
>     "semicolon": {
>       "options": [
>         "always"
>       ]
>     },
>     "space-before-function-paren": {
>       "options": {
>         "anonymous": "never",
>         "asyncArrow": "always",
>         "constructor": "never",
>         "method": "never",
>         "named": "never"
>       }
>     },
>     "typedef-whitespace": {
>       "options": [
>         {
>           "call-signature": "nospace",
>           "index-signature": "nospace",
>           "parameter": "nospace",
>           "property-declaration": "nospace",
>           "variable-declaration": "nospace"
>         },
>         {
>           "call-signature": "onespace",
>           "index-signature": "onespace",
>           "parameter": "onespace",
>           "property-declaration": "onespace",
>           "variable-declaration": "onespace"
>         }
>       ]
>     },
>     "variable-name": {
>       "options": [
>         "ban-keywords",
>         "check-format",
>         "allow-pascal-case"
>       ]
>     },
>     "whitespace": {
>       "options": [
>         "check-branch",
>         "check-decl",
>         "check-operator",
>         "check-separator",
>         "check-type",
>         "check-typecast"
>       ]
>     },
>     "no-conflicting-lifecycle": true,
>     "no-host-metadata-property": true,
>     "no-input-rename": true,
>     "no-inputs-metadata-property": true,
>     "no-output-native": false,
>     "no-output-on-prefix": true,
>     "no-output-rename": true,
>     "no-outputs-metadata-property": true,
>     "template-banana-in-box": true,
>     "template-no-negated-async": true,
>     "use-lifecycle-interface": true,
>     "use-pipe-transform-interface": true
>   },
>   "rulesDirectory": [
>     "codelyzer"
>   ]
> }
>

**Comment by rafaelss95** [comment]
Could you please tell me which versions are you using: Angular and Codelyzer? Also, please check if there is no other `tslint.json` file across the project overriding this one.

Just a note about the repo, I was asking about a clean repo, with only the `tslint.json` filled and a component to demonstrates the issue.

**Comment by ranouf** [comment]
```
"@angular/core": "~9.1.9"
"codelyzer": "^5.2.2"
```

thanks for the explanation about the repo :)

**Comment by ranouf** [comment]
I finally found the issue, I modified the file in its parent folder instead of using the one in angular app.

Thanks for your help.
