### ISSUE TITLE
component-selector-name - Emits false error when the component uses an attribute selector

### ISSUE THREAD

**Issue by NightkingCH** [mgechev/codelyzer#98]
Hi there

If you don't specify the "component-selector-type" rule but you want to use the "component-selector-name"-rule and you do following:

tslint.json
`
"component-selector-name": [ true, "kebab-case" ]
`

row-performance.component.ts
`
@Component({
    selector: '[row-performance-object]'
})
`

The codlyzer emits an error when the component uses an attribute-selector. In my opinion this is wrong, because within the brackets I'm using the kebab-case-syntax.

I think it should be possible to define the case-syntax regardless of the object type (component | directive). I just want to ensure that everyone who is creating a directive / component uses the same style for an element or attribute selector.

This should be treated the same way until the "directive-selector-type" or "component-selector-type" rule is specified:

`
@Directive({
    selector: '[row-performance-object]'
})
`
`
@Component({
    selector: '[row-performance-object]'
})
`

P.S: 

If I change my component to the directive annotation, it emits the same error. Regardless of the type I have specified.

tslint.json for this case:
`
"directive-selector-name": [ true, "kebab-case" ],
"directive-selector-type": [ true, "attribute" ]`

Thanks in advance!

**Comment by mgechev** [comment]
Hey @NightkingCH, thanks for pointing this out! This is a know issue and we'll include a fix in the next release https://github.com/mgechev/codelyzer/issues/15.
